define(["promise","./dom","./tracker","./table"],function(T,h,I,J){var K=document.querySelector(".results");return function(r,n,L,e,x){var p=this,M=x.trackers,l={},k=[],t=[],f={},q=null,m=[],N=function(b,c){b=void 0===b?!this.selected:!!b;if(this.selected!==b){if(this.selected=b)q&&q!==this&&q.select(!1,!0),q=this;var a=m.indexOf(this.id);b?(this.node.classList.add("tracker-selected"),n.addTracker(this.id),-1===a&&m.push(this.id)):(this.node.classList.remove("tracker-selected"),n.removeTracker(this.id),
-1!==a&&m.splice(a,1));!c&&n.update()}},O=function(b){var c="";c=b.filtered!==b.all?c+(b.filtered+"/"+b.all):c+b.filtered;this.currentCount!==c&&(this.currentCount=c,this.countNode.textContent=c)},P=function(b,c){this.iconNode.classList.remove("tracker__icon-loading");this.iconNode.classList.remove("tracker__icon-error");this.iconNode.title="";"error"===b?(this.iconNode.title=c,this.iconNode.classList.add("tracker__icon-error")):"search"===b&&this.iconNode.classList.add("tracker__icon-loading")},
Q=function(b){var c=this,a=h.el("a",{class:["tracker__login"],target:"_blank",href:b.url,title:chrome.i18n.getMessage("login"),on:["click",function(b){b.stopPropagation()}]});c.countNode.classList.add("counter-hidden");c.node.insertBefore(a,c.countNode);c.auth={node:a,destroy:function(){c.countNode.classList.remove("counter-hidden");a.parentNode.removeChild(a);c.auth=null}}},F=function(){e.on("profileFieldChange",y);e.on("selectTracker",z);e.on("filterChange",A);e.on("search",B);e.on("quickSearch",
C);e.on("stateReset",D);p.id=r.id;p.name=r.name;var b=document.createDocumentFragment();r.trackers.forEach(function(c){var a=null,d=M[c.id];d?(a=new I(d),a.load()):d={id:c.id,meta:{},info:{},code:""};var e="icon_"+d.id,f=h.el("style",{text:"."+e+"{background-image:url("+JSON.stringify(d.meta.icon64||d.meta.icon||"./img/blank.svg")+")}"}),g;var v=d.meta.trackerURL?h.el("a",{class:["tracker__icon",e,"tracker__link"],target:"_blank",href:d.meta.trackerURL,on:["click",function(b){b.stopPropagation()}]}):
h.el("div",{class:["tracker__icon",e]});v.appendChild(f);c=h.el("a",{class:"tracker",href:"#"+d.id,data:{id:d.id},append:[v,h.el("div",{class:"tracker__name",text:d.meta.name||d.id}),g=h.el("div",{class:"tracker__counter",text:0})]});a={id:d.id,name:d.meta.name||d.id,iconClass:e,node:c,iconStyleNode:f,countNode:g,iconNode:v,worker:a,selected:!1,select:N,currentCount:0,count:O,status:P,auth:null,setAuth:Q};k.push(a);l[a.id]=a;b.appendChild(c)});L(b);e.on("trackerChange",E)},E=function(b,c){(b=l[b])&&
-1!==c.indexOf("code")&&b.worker&&b.worker.safeReload()},w=function(){t.splice(0).forEach(function(b){b.destroy()})},u=function(){for(var b={},c,a,d=0;c=t[d];d++)for(a in c=c.counter,c)b[a]||(b[a]={filtered:0,all:0}),b[a].filtered+=c[a].filtered,b[a].all+=c[a].all;k.forEach(function(a){a.count(b[a.id]||{filtered:0,all:0})})},R=function(b){var c={query:b,profileId:r.id,time:parseInt(Date.now()/1E3)};chrome.storage.local.get({history:[]},function(a){var d=-1;a.history.some(function(a,c){if(a.query===
b)return d=c,!0});-1!==d&&a.history.splice(d,1);a.history.unshift(c);a.history.splice(500);chrome.storage.local.set(a)})},G=function(){var b=new J(n,x);b.load();t.push(b);K.appendChild(b.node);return b},C=function(b,c){k.forEach(function(a){a.worker&&(a.status("search"),a.auth&&a.auth.destroy(),a.worker.search(b,function(d){if(!d)throw a.status("error","Tracker response is empty!"),Error("Tracker response is empty!");if(d.success){a.status("success");var e=d.results.length;a.count({filtered:e,all:e});
c(a,b,d.results)}else"AUTH"===d.error?(a.setAuth(d),a.status("success")):"ABORT"===d.message?a.status("success"):a.status("error",d.name+": "+d.message)}))})},B=function(b){ga("send","event","Search","keyword",b);w();var c=G();k.forEach(function(a){m.length&&-1===m.indexOf(a.id)||!a.worker||(a.status("search"),a.auth&&a.auth.destroy(),a.worker.search(b,function(d){if(!d)throw a.status("error","Tracker response is empty!"),Error("Tracker response is empty!");d.success?(a.status("success"),c.insertResults(a,
b,d.results),d.nextPageRequest&&(f[a.id]={message:d.nextPageRequest,query:b},c.insertMoreBtn(H,Object.keys(f))),u()):"AUTH"===d.error?(a.setAuth(d),a.status("success")):"ABORT"===d.message?a.status("success"):a.status("error",d.name+": "+d.message)}))});R(b)},H=function(b){var c=null;Object.keys(f).forEach(function(a){var d=f[a];delete f[a];var e=d.message,h=d.query,g=l[a];g.worker&&(g.status("search"),g.worker.sendMessage(e,function(a){b&&b();b=null;if(!a)throw g.status("error","Tracker response is empty!"),
Error("Tracker response is empty!");if(a.success){g.status("success");c||(c=G());c.insertResults(g,h,a.results);if(a.nextPageRequest){var d=c;f[g.id]={message:a.nextPageRequest,query:h};d.insertMoreBtn(H,Object.keys(f))}u()}else g.status("error",a.error)}))})},A=function(){t.forEach(function(b,c){b.applyFilter()});u()},z=function(b){l[b].select()},S=function(){k.forEach(function(b){b.worker&&b.worker.abort()})},D=function(){S();w();u()},y=function(b,c){b===p.id&&-1!==c.indexOf("trackers")&&p.reload()};
this.trackers=k;this.reload=function(){p.destroy();F()};this.destroy=function(){e.off("profileFieldChange",y);e.off("trackerChange",E);e.off("stateReset",D);e.off("selectTracker",z);e.off("filterChange",A);e.off("search",B);e.off("quickSearch",C);w();q=null;m.splice(0);for(var b in f)delete f[b];k.splice(0).forEach(function(b){b.worker&&b.worker.destroy()});for(b in l)delete l[b];n.clearTrackerFilter()};F()}});
