define(["./utils","./dom"],function(r,a){var y=function(p,D,n,d,y){var E=this,z=function(a,d){y?chrome.storage.sync.set({profiles:a},d):d()},B=function(){var g=this,d,n,q,m=a.el("div",{class:"manager__layer",append:[a.el("div",{class:"manager",append:[a.el("div",{class:"manager__header",append:[d=a.el("div",{class:"header__title"}),a.el("a",{href:"#close",class:"header__close",text:chrome.i18n.getMessage("close"),on:["click",function(a){a.preventDefault();g.destroy()}]})]}),n=a.el("div",{class:"manager__body"}),
q=a.el("div",{class:"manager__footer"})]})]}),p=function(a){m.contains(a.target)||g.destroy()},h=[];this.node=m;this.titleNode=d;this.bodyNode=n;this.footerNode=q;this.show=function(a){!a&&document.body.appendChild(m);document.addEventListener("click",p,!0)};this.destroy=function(a){!a&&m.parentNode.removeChild(m);for(document.removeEventListener("click",p,!0);a=h.shift();)a()};this.onDestroy=function(a){h.push(a)};this.replace=function(a){g.destroy(!0);m.parentNode.replaceChild(a.node,m);a.show(!0)}},
C=function(g){var t=new B;t.titleNode.textContent=chrome.i18n.getMessage("manageProfile");var u=function(){var b=!1,c=null;return{node:a.el("div",{class:["manager__sub_header","sub_header__profile"],append:[a.el("div",{class:["profile__input"],append:[c=a.el("input",{class:["input__input"],type:"text",value:"",on:["keyup",function(a){this.value.length?b&&(b=!1,c.classList.remove("input__error")):b||(b=!0,c.classList.add("input__error"))}]})]})]}),set:function(b){c.value=b;c.dispatchEvent(new CustomEvent("keyup"))},
get:function(){return c.value}}}();u.set(g.name);t.bodyNode.appendChild(u.node);var q=new function(){var b=this,c=null,e="",d=function(k){var a=h.trackerIdItem;Object.keys(a).forEach(function(f){f=a[f];f.removed||(b.isFiltered(k,f)?f.filtered||(f.filtered=!0,f.node.classList.add("item__filtered")):f.filtered&&(f.filtered=!1,f.node.classList.remove("item__filtered")))})},m=r.throttle(d,150);this.type="selected";this.typeItemObj={};this.node=a.el("div",{class:["manager__sub_header","sub_header__filter"],
append:[a.el("div",{class:["filter__box"],append:["all","withoutList","selected"].map(function(k){var l={},f=l.node=a.el("a",{class:["filter__item"],href:"#"+k,data:{type:k},append:[chrome.i18n.getMessage("filter_"+k)," ",l.count=a.el("span",{class:["item__count"],text:"0"})]});b.type===k&&(f.classList.add("item__selected"),c=f);b.typeItemObj[k]=l;return f}),on:["click",function(k){k.preventDefault();if(k=a.closestNode(this,k.target))b.type=k.dataset.type,c.classList.remove("item__selected"),c=k,
k.classList.add("item__selected"),d(b.type)}]}),a.el("div",{class:["filter__search"],append:[a.el("input",{class:["input__input","filter__input"],type:"text",placeholder:chrome.i18n.getMessage("quickSearch"),on:[["keyup",function(b){e=this.value.toLowerCase();m("search")}],["dblclick",function(){this.value=e="";m("search")}]]})]})]});this.isFiltered=function(a,l){l||(l=a,a=b.type);if("all"===a)return!1;if("selected"===a)return!l.checked;if("withoutList"===a)return p.some(function(b){return b!==g?
b.trackers.some(function(b){return b.id===l.id}):l.checked});if("search"===a)return l.searchCache||(a=(n[l.id]||{id:l.id,meta:{}}).meta,l.searchCache=[a.id,a.name,a.author,a.description,a.homepageURL,a.trackerURL,a.updateURL,a.downloadURL,a.supportURL].join(" ").toLowerCase()),-1!==l.searchCache.indexOf(e)?!1:!0};this.updateCount=function(a){a||(a=h.trackerIdItem);var l=0,f=0,c=0;Object.keys(a).forEach(function(k){k=a[k];k.removed||(l++,b.isFiltered("selected",k)||f++,b.isFiltered("withoutList",k)||
c++)});b.typeItemObj.all.count.textContent=l;b.typeItemObj.selected.count.textContent=f;b.typeItemObj.withoutList.count.textContent=c}};t.bodyNode.appendChild(q.node);var m=function(b,c){var e=["item"];c&&e.push("item__selected");return a.el("div",{class:e,data:{id:b.id},append:[a.el("div",{class:"item__move"}),a.el("div",{class:"item__checkbox",append:[a.el("input",{type:"checkbox",checked:c})]}),a.el("img",{class:["item__icon"],src:b.meta.icon||b.meta.icon64||"./img/blank.svg",on:["error",function(){this.src=
"./img/blank.svg"}]}),a.el("div",{class:"item__name",text:b.meta.name||b.id}),a.el("div",{class:["item__cell","item__version"],text:b.meta.version||""}),b.meta.updateURL||b.meta.downloadURL?a.el("a",{class:["item__cell","item__button","button-update"],href:"#update",data:{action:"update"},title:chrome.i18n.getMessage("update")}):"",b.meta.supportURL?a.el("a",{class:["item__cell","item__button","button-support"],target:"_blank",href:b.meta.supportURL}):"",b.meta.homepageURL?a.el("a",{class:["item__cell",
"item__button","button-home"],target:"_blank",href:b.meta.homepageURL}):"",b.meta.author?a.el("div",{class:["item__cell","item__author"],text:b.meta.author}):"",a.el("a",{class:["item__cell","item__button","button-edit"],href:"#edit",data:{action:"edit"},title:chrome.i18n.getMessage("edit")}),a.el("a",{class:["item__cell","item__button","button-remove"],href:"#remove",data:{action:"remove"},title:chrome.i18n.getMessage("remove")})]})},A=function(){var b={},c=function(b){this.checked=b;var a=this.node.querySelector(".item__checkbox input");
b?(this.node.classList.add("item__selected"),a.checked=!0):(this.node.classList.remove("item__selected"),a.checked=!1);q.updateCount()},e=function(){var b=m(n[this.id],this.checked),a=this.node.parentNode;a&&a.replaceChild(b,this.node);this.node=b},d=function(){var b=this.node.parentNode;b&&b.removeChild(this.node);this.removed=!0;q.updateCount()},h=a.el("div",{class:"manager__trackers",append:function(){var a=[],l=function(a,b){a={id:a.id,node:m(a,b),setChecked:c,checked:b,refresh:e,remove:d,removed:!1,
searchCache:"",profileMeta:a.meta,filtered:!1};a.filtered=q.isFiltered(a);a.filtered&&a.node.classList.add("item__filtered");return a};g.trackers.map(function(a){return n[a.id]||{id:a.id,meta:a.meta||{},info:{}}}).forEach(function(f){f=l(f,!0);b[f.id]=f;a.push(f.node)});Object.keys(n).map(function(a){return n[a]}).forEach(function(c){b[c.id]||(c=l(c,!1),b[c.id]=c,a.push(c.node))});q.updateCount(b);return a}(),on:["click",function(c){var e=c.target,f=a.closestNode(this,e);if(f=f&&b[f.dataset.id]){var k=
f.id;if("edit"===e.dataset.action)c.preventDefault(),chrome.tabs.create({url:"editor.html#"+r.param({id:k})});else if("remove"===e.dataset.action)c.preventDefault(),f.remove();else if("update"===e.dataset.action){c.preventDefault();var d=f.node.querySelector(".item__version"),g=d.textContent;d.textContent="...";chrome.runtime.sendMessage({action:"update",id:k,force:!0,profileMeta:f.profileMeta},function(a){a.success?(a=a.results[0],d.textContent=a.success?a.version:a.message):d.textContent=g})}else"checkbox"===
e.type&&e.parentNode.classList.contains("item__checkbox")?f.setChecked(e.checked):(e.classList.contains("item")||e.classList.contains("item__name"))&&f.setChecked(!f.checked)}}]});require(["jquery"],function(){require(["jqueryUi"],function(){$(h).sortable({axis:"y",handle:".item__move",scroll:!1})})});return{node:h,trackerIdItem:b,refreshTracker:function(a){b[a].refresh()},removeTracker:function(a){b[a].remove()},getTrackers:function(){var a=r.clone(n);Object.keys(b).forEach(function(c){c=b[c];c.removed&&
delete a[c.id]});return a},getProfileTrackers:function(){var a=[];[].slice.call(h.childNodes).forEach(function(c){c=c.dataset.id;var e=n[c];if(b[c].checked){var d={};e&&(d.name=e.meta.name,d.author=e.meta.author,d.homepageURL=e.meta.homepageURL,d.updateURL=e.meta.updateURL,d.downloadURL=e.meta.downloadURL);a.push({id:c,meta:d})}});return a}}},h=A();t.bodyNode.appendChild(h.node);var w=function(){var a=A();h.node.parentNode.replaceChild(a.node,h.node);h=a};t.footerNode.appendChild(a.el(document.createDocumentFragment(),
{append:[a.el("a",{href:"#save",class:["button","manager__footer__btn"],text:chrome.i18n.getMessage("save"),on:["click",function(a){a.preventDefault();var b=r.clone(p);a=r.getItemId(b,g.id);a||(a=g,b.push(g));a.name=u.get();a.trackers=h.getProfileTrackers();a.name?(a=h.getTrackers(),chrome.storage.local.set({profiles:b,trackers:a},function(){z(b,function(){d.trigger("selectProfileById",[g.id]);t.destroy()})})):u.set(a.name)}]}),a.el("a",{href:"#add",class:["button","manager__footer__btn"],text:chrome.i18n.getMessage("add"),
on:["click",function(a){a.preventDefault();chrome.tabs.create({url:"editor.html"})}]}),a.el("a",{href:"#createCode",class:["button","manager__footer__btn"],text:chrome.i18n.getMessage("createCode"),on:["click",function(a){a.preventDefault();chrome.tabs.create({url:"magic.html"})}]})]}));var x=function(a,c){-1!==c.indexOf("meta")&&h.refreshTracker(a)},v=function(a){h.removeTracker(a)},e=function(a,c){a===g.id&&(-1!==c.indexOf("name")&&u.set(g.name),-1!==c.indexOf("trackers")&&w())};d.on("trackerChange",
x);d.on("trackerRemoved",v);d.on("trackerInsert",w);d.on("profileFieldChange",e);t.onDestroy(function(){d.off("trackerChange",x);d.off("trackerRemoved",v);d.off("trackerInsert",w);d.off("profileFieldChange",e)});return t},F=function(){var g=new B;g.titleNode.textContent=chrome.i18n.getMessage("manageProfiles");g.bodyNode.appendChild(a.el("div",{class:["manager__sub_header","manager__sub_header-profiles"],append:[a.el("a",{class:["manager__new_profile"],href:"#new_profile",text:chrome.i18n.getMessage("newProfile"),
on:["click",function(a){a.preventDefault();a=E.getDefaultProfile(D);a.name="";a.trackers.splice(0);g.replace(C(a))}]})]}));var n=function(e){return a.el("div",{class:"item",data:{id:e.id},append:[a.el("div",{class:"item__move"}),a.el("div",{class:"item__name",text:e.name}),a.el("a",{class:["item__cell","item__button","button-edit"],href:"#edit",data:{action:"edit"},title:chrome.i18n.getMessage("edit")}),a.el("a",{class:["item__cell","item__button","button-remove"],href:"#remove",data:{action:"remove"},
title:chrome.i18n.getMessage("remove")})]})},u=function(){var a=this.node.parentNode;a&&a.removeChild(this.node)},q=function(){var a=this,b=null;p.some(function(c){if(a.id===c.id)return b=c,!0});var c=n(b),d=this.node.parentNode;d&&d.replaceChild(c,this.node);this.node=c},m=function(){var a=this,b=null;p.some(function(c){if(c.id==a.id)return b=c,!0});g.replace(C(b))},r=function(){var e={},b=a.el("div",{class:"manager__profiles",append:function(){var a=[];p.forEach(function(b){b={id:b.id,node:n(b),
refresh:q,remove:u,edit:m};e[b.id]=b;a.push(b.node)});return a}(),on:["click",function(b){var c=b.target,d=a.closestNode(this,c);if(d=d&&e[d.dataset.id])"remove"===c.dataset.action?(b.preventDefault(),d.remove()):"edit"===c.dataset.action?(b.preventDefault(),d.edit()):(c.classList.contains("item")||c.classList.contains("item__name"))&&d.edit()}]});require(["jquery"],function(){require(["jqueryUi"],function(){$(b).sortable({axis:"y",handle:".item__move",scroll:!1})})});return{node:b,refreshProfile:function(a){e[a].refresh()},
removeProfile:function(a){e[a].remove()},getProfiles:function(){var a={};p.forEach(function(b){a[b.id]=b});var d=[];[].slice.call(b.childNodes).forEach(function(b){d.push(a[b.dataset.id])});return d}}},h=r();g.bodyNode.appendChild(h.node);g.footerNode.appendChild(a.el("a",{href:"#save",class:["button","manager__footer__btn"],text:chrome.i18n.getMessage("save"),on:["click",function(a){a.preventDefault();var b=h.getProfiles();chrome.storage.local.set({profiles:b},function(){z(b,function(){g.destroy()})})}]}));
var w=function(a){h.removeProfile(a)},x=function(a,b){-1!==b.indexOf("name")&&h.refreshProfile(a)},v=function(){var a=r();g.bodyNode.replaceChild(a.node,h.node);h=a};d.on("profileRemoved",w);d.on("profileFieldChange",x);d.on("profileInsert",v);d.on("profilesSortChange",v);g.onDestroy(function(){d.off("profileRemoved",w);d.off("profileFieldChange",x);d.off("profileInsert",v);d.off("profilesSortChange",v)});return g};this.show=function(){F().show()}};y.prototype.getDefaultProfile=function(a){var p=
null;p=/^ru-?/.test(chrome.i18n.getUILanguage())?"nnmclub rutracker kinozal rutor hdclub tfile opentorrent".split(" "):["bitsnoop","extratorrent","thepiratebay"];return{name:chrome.i18n.getMessage("defaultProfileName"),id:a.getProfileId(),trackers:p.map(function(a){return{id:a,meta:{name:a,downloadURL:"./trackers/"+a+".js"}}})}};return y});
