define(["./utils"],function(p){var w=[{match:[{regexp:1,word:"320\\s*(kbps)?",caseSens:0}],rate:{audioFormat:30}},{match:[{regexp:1,word:"256\\s*(kbps)?",caseSens:0}],rate:{audioFormat:25}},{match:[{regexp:1,word:"192\\s*(kbps)?",caseSens:0}],rate:{audioFormat:20}},{match:[{regexp:1,word:"128\\s*(kbps)?",caseSens:0}],rate:{audioFormat:10}},{match:[{regexp:1,word:"96\\s*(kbps)?",caseSens:0}],rate:{audioFormat:0}},{match:[{regexp:1,word:"64\\s*(kbps)?",caseSens:0}],rate:{audioFormat:-10}},{match:[{regexp:1,
word:"32\\s*(kbps)?",caseSens:0}],rate:{audioFormat:-20}}],q={rating:[{name:"videoFormat",unic:!0,rules:[{match:["DCPRip"],rate:{videoFormat:100},label:"DCPRip"},{match:["blu-ray cee",{word:"CEE"}],rate:{videoFormat:100},label:"Blu-ray CEE"},{match:["blu-ray"],rate:{videoFormat:98},label:"Blu-ray"},{match:["bd-remux","bd remux","BDRemux"],rate:{videoFormat:95},label:"BDRemux"},{match:["BDRip-AVC","BD-Rip","BDRip"],rate:{videoFormat:90},label:"BDRip"},{match:["CAMRip","CamRip-AVC"],rate:{videoFormat:10},
label:"CAMRip"},{match:["HDTV-Rip","HDTVRip"],rate:{videoFormat:60},label:"HDTV-Rip"},{match:["DTheater-Rip"],rate:{videoFormat:60},label:"DTheater-Rip"},{match:["LowHDRip","VHSRip"],rate:{videoFormat:10},label:"LowHDRip"},{match:[{word:"HDTV"},"HDRip","HDRip-AVC"],rate:{videoFormat:50},label:"HDTV"},{match:["DVDRip","DVD-Rip","DVDRip-AVC"],rate:{videoFormat:50},label:"DVD-Rip"},{match:["HD-DVD"],rate:{videoFormat:55},label:"HD-DVD"},{match:[{regexp:1,word:"\\d\\s?[x\\*]\\s?DVD\\-?9",caseSens:0}],
rate:{videoFormat:50},label:"DVD-9"},{match:[{regexp:1,word:"\\d\\s?[x\\*]\\s?DVD\\-?5",caseSens:0}],rate:{videoFormat:45},label:"DVD-5"},{match:[{word:"DVD"}],rate:{videoFormat:40},label:"DVD"},{match:["HQSATRip","HQRip","HQRip-AVC"],rate:{videoFormat:38},label:"HDrip"},{match:["TVRip","IPTVRip"],rate:{videoFormat:35},label:"TV-Rip"},{match:["WEBRip"],rate:{videoFormat:35},label:"WebRip"},{match:["WEB-DLRip-AVC","WebDL-Rip","WEB-DLRip","WEB-DL"],rate:{videoFormat:35},label:"WEB-DL"},{match:["SATRip"],
rate:{videoFormat:35},label:"SAT-Rip"},{match:[{word:"DVB"}],rate:{videoFormat:35},label:"DVB"},{match:[{word:"TS"},"TeleSynch"],rate:{videoFormat:15},label:"TeleSynch"},{match:["DVDScr","DVDScreener"],rate:{videoFormat:15},label:"DVD-Screener"}]},{name:"videoQuality",join:"videoFormat",rules:[{match:["4k","2k"],rate:{videoQuality:100}},{match:["2160p","2160i"],rate:{videoQuality:100}},{match:["1080p","1080i"],rate:{videoQuality:90}},{match:["720p"],rate:{videoQuality:50}},{match:["HD"],rate:{videoQuality:40}},
{match:["SD"],rate:{videoQuality:20}}]},{name:"audioFormat",unic:!0,rules:[{match:["ALAC"],rate:{audioFormat:90},label:"ALAC"},{match:["FLAC"],rate:{audioFormat:90},label:"FLAC",sub:[{match:[".cue"],rate:{audioFormat:10}}]},{match:["APE"],rate:{audioFormat:90},label:"APE"},{match:["AAC","\u0410\u0410\u0421"],rate:{audioFormat:50},label:"AAC",sub:w},{match:["MP3","M\u04203"],rate:{audioFormat:50},label:"MP3",sub:w}]},{name:"gameQuality",unic:!0,rules:[{match:[{word:"PS3"}],rate:{gameQuality:80},label:"PS3"},
{match:[{word:"XBOX"},"Xbox360","Xbox 360"],rate:{gameQuality:80},label:"XBOX"},{match:[{word:"PC"}],rate:{gameQuality:80},label:"PC"},{match:[{word:"PS2"},"(ps2)"],rate:{gameQuality:70},label:"PS2"},{match:[{word:"Wii"}],rate:{gameQuality:50},label:"Wii"},{match:[{word:"GOG"}],rate:{gameQuality:80},label:"GOG"},{match:["Steam","SteamRip","Steam-Rip"],rate:{gameQuality:80},label:"SteamRip"}]},{name:"soft",unic:!0,rules:[{match:[{word:"[L]"},{word:"{L}"},{word:"(L)"},"License","\u041b\u0438\u0446\u0435\u043d\u0437\u0438\u044f"],
rate:{soft:80}},{match:["[Native]"],rate:{soft:80}},{match:["repack"],rate:{soft:50}}]},{name:"book",unic:!0,rules:[{match:["fb2","djvu","epub"],rate:{book:70}},{match:["pdf","rtf","doc","D\u041e\u0421","docx"],rate:{book:50}}]}],qualityList:{},readQualityList:function(a){var b=null,d=[],g=[],n={},h={},k={each:{},some:{}};a.forEach(function(a){a.parent?k[a.parent].push(a.name):a.join?k[a.join].push(a.name):k[a.name]=a.unic?k.some[a.name]=[a.name]:k.each[a.name]=[a.name];a.rules.forEach(function(b,
c){b.section=a;b.index=c;b.match&&b.match.forEach(function(a){"string"===typeof a&&(a={word:a,caseSens:!1});if(1===a.regexp){d.push(a.word);var c="g";a.caseSens&&(c+="i");g.push({re:new RegExp(a.word,c),qualityObj:b})}else a.caseSens?h[a.word]?console.error("Word case conflict!",a):h[a.word]=b:(a.word=a.word.toLowerCase(),n[a.word]?console.error("Word conflict!",a):n[a.word]=b),d.push(p.sanitizeTextRe(a.word))});b.sub&&(b.sub=q.readQualityList([{name:a.name,rules:b.sub}]))})});d.length&&(b=new RegExp(d.sort(function(a,
b){return a.length>b.length?-1:1}).join("|"),"ig"));var c=[],r=[];g.length&&(g.sort(function(a,b){return String(a.re).length>String(b.re).length?-1:1}),g.forEach(function(a){r.push(a.re);c.push(a.qualityObj)}));Object.keys(k).forEach(function(a){"each"!==a&&"some"!==a&&delete k[a]});a={};a.wordsRe=b;a.scope=!p.isEmptyObject(n)&&n;a.scopeCase=!p.isEmptyObject(h)&&h;a.scopeRegexp=r.length&&r;a.scopeRegexpIndex=c;a.sections=k;return a},baseQualityList:{},getScheme:function(a){var b={};b.query=a;b.words=
[];a.split(/[-\s]+/).forEach(function(a){for(;a.length&&p.isPunctuation(a[0]);)a=a.substr(1);for(;a.length&&p.isPunctuation(a.slice(-1));)a=a.slice(0,-1);a.length&&b.words.push(a)});b.wordsCase=b.words.map(function(a){return(a=a[0])&&a.toUpperCase()===a?a:null});b.wordsLow=b.words.map(function(a){return a.toLowerCase()});b.years=b.wordsLow.filter(function(a){return/\d{4}/.test(a)});b.wordsRe=b.words.slice(0).sort(function(a,b){return a.length>b.length?-1:1}).map(function(a){return p.sanitizeTextRe(a)});
b.wordsRe=new RegExp(b.wordsRe.join("|"),"ig");b.wordsSpaces=Array(b.wordsLow.length);var d=b.words.slice(0),g=null;a.replace(b.wordsRe,function(a,h,k){var c=a.length;if(!a||!p.isBoundary(k[h-1],k[h+c]))return"";a=d.indexOf(a);-1!==a&&(d.splice(a,1,null),null===g&&(g=h-1),b.wordsSpaces[a]=h-g,g=h+c)});return b},getQualityRating:function(a,b,d,g,n){g=g||[];var h={};a.replace(d.wordsRe,function(){var a=arguments[0],c=a.length,e=arguments.length,k=arguments[e-2];e=arguments[e-1];if(!a||!p.isBoundary(e[k-
1],e[k+c]))return"";var m=d.scopeCase&&d.scopeCase[a];!m&&d.scope&&(c=a.toLowerCase(),(m=d.scope[c])&&(a=c));if(-1!==g.indexOf(a))return"";!m&&d.scopeRegexp&&d.scopeRegexp.some(function(b,c){if(b.test(a))return m=d.scopeRegexpIndex[c],!0});if(!m)return"";g.push(a);c=m.section;k=c.name;var f=h[k];f||(f=h[k]={index:null,rate:{}});if(null===f.index||m.index<f.index){f.index=m.index;f.parent=c.parent;f.label="";for(var l in m.rate)f.rate[l]=n?f.rate[l]+m.rate[l]:m.rate[l];!n&&m.label&&(f.label=m.label);
m.sub&&q.getQualityRating(e,b,m.sub,g,n)}return""});if(!n){a=d.sections;var k=[],c,r,v;for(v in a)for(r in a[v]){var l=a[v][r];var e={};var x=!1;for(var f=0,u=l.length;f<u;f++){var t=h[l[f]];t&&t.parent&&!h[t.parent]&&(t=null);if(t){x=!0;for(c in t.rate)e[c]||(e[c]=0),e[c]+=t.rate[c];t.label&&k.push(t.label)}}if(x){for(c in e)e[c]/=u,b.rate[c]=e[c];b.quality=k.join(";");if("some"===v)break}}}},getTitleReplace:function(a,b){var d=b.words.length,g=b.wordsCase,n=b.wordsLow.slice(0),h=100/d,k=b.wordsSpaces;
a.rate.title=0;a.rate.wordSpaces=0;a.rate.wordOrder=0;a.rate.caseSens=0;var c=null,r=0;return function(d,l,e){var q=d.length;if(!d||!p.isBoundary(e[l-1],e[l+q]))return"";var f=d.toLowerCase();e=n.indexOf(f);if(-1!==e){n.splice(e,1,null);f=-1!==b.years.indexOf(f);a.rate.title+=h;if(f)a.rate.wordSpaces+=h;else{null===c&&(c=l-1);f=l-c;var u=k[e];u>f&&(f=u);a.rate.wordSpaces+=u/f*h;c=l+q}r===e&&(a.rate.wordOrder+=h);(l=g[e])?l===d[0]&&(a.rate.caseSens+=h):a.rate.caseSens+=h;r++}}},getRate:function(a,
b){var d={quality:"",rate:{title:0,wordSpaces:0,wordOrder:0,caseSens:0,videoFormat:0,videoQuality:0,audioFormat:0,gameQuality:0,soft:0,book:0},sum:0},g=a.title;b.query&&(a=a.title.indexOf(b.query),-1!==a&&p.isBoundary(g[a-1],g[a+b.query.length])?(d.rate.title=100,d.rate.wordSpaces=100,d.rate.wordOrder=100,d.rate.caseSens=100):g.replace(b.wordsRe,q.getTitleReplace(d,b)));q.getQualityRating(g,d,q.baseQualityList);for(var n in d.rate)d.sum+=d.rate[n];return d},init:function(){this.baseQualityList=this.readQualityList(JSON.parse(JSON.stringify(this.rating)))}};
q.init();return q});
