define("promise moment ./dom ../lib/filesize.min ./highlight ./rate".split(" "),function(p,n,e,y,w,x){n.locale(chrome.i18n.getUILanguage());var z=function(f){return 0>=f?"\u221e":n(1E3*f).format("lll")},A=function(f){return 0>=f?"\u221e":n(1E3*f).fromNow()},B=function(f,d,a){for(var b,c=[],e,g=0;b=d[g];g++)if(a[g]!==b){b=g;for(e=document.createDocumentFragment();void 0!==d[g]&&d[g]!==a[g];){var r=a.indexOf(d[g],g);-1!==r&&a.splice(r,1);a.splice(g,0,d[g]);e.appendChild(d[g].node);g++}c.push([b,e])}for(a=
0;b=c[a];a++)d=f.childNodes[b[0]],void 0!==d?f.insertBefore(b[1],d):f.appendChild(b[1])},C={date:function(f){var d=-1,a=1;0<f&&(d=1,a=-1);return function(b,c){b=b.torrent.date;c=c.torrent.date;return b===c?0:b>c?d:a}},quality:function(f){var d=-1,a=1;0<f&&(d=1,a=-1);return function(b,c){b=b.torrent.quality;c=c.torrent.quality;return b===c?0:b>c?d:a}},title:function(f){var d=-1,a=1;0<f&&(d=1,a=-1);return function(b,c){b=b.torrent.title;c=c.torrent.title;return b===c?0:b<c?d:a}},size:function(f){var d=
-1,a=1;0<f&&(d=1,a=-1);return function(b,c){b=b.torrent.size;c=c.torrent.size;return b===c?0:b>c?d:a}},seed:function(f){var d=-1,a=1;0<f&&(d=1,a=-1);return function(b,c){b=b.torrent.seed;c=c.torrent.seed;return b===c?0:b>c?d:a}},peer:function(f){var d=-1,a=1;0<f&&(d=1,a=-1);return function(b,c){b=b.torrent.peer;c=c.torrent.peer;return b===c?0:b>c?d:a}}},D=function(f,d){if(f=e.closest("a",f)){var a=null;if(f.classList.contains("title")){a="open";var b=d[f.dataset.index]}else f.classList.contains("cell__download")&&
(a="download",b=d[f.dataset.index]);if(b){var c={type:a,query:b.query,trackerId:b.torrent.trackerId,title:b.torrent.title,url:b.torrent.url,time:parseInt(Date.now()/1E3)};chrome.storage.local.get({clickHistory:[]},function(a){var b=-1;a.clickHistory.some(function(a,d){if(a.query===c.query&&a.url===c.url)return b=d,!0});-1!==b&&a.clickHistory.splice(b,1);a.clickHistory.unshift(c);a.clickHistory.splice(500);chrome.storage.local.set(a)})}}};p=function(f,d){var a=this,b="date quality title size seed peer".split(" ");
d.hidePeerRow&&b.splice(b.indexOf("peer"),1);d.hideSeedRow&&b.splice(b.indexOf("seed"),1);var c=d.sortCells,k={},g=function(){var a={},d=null,f=function(a){this===d?this.sortDirection=0<this.sortDirection?-1:1:d&&(this.sortDirection=0,d.node.classList.remove("cell-sort-up"),d.node.classList.remove("cell-sort-down"));a&&(this.sortDirection=a);0<this.sortDirection?(this.node.classList.remove("cell-sort-down"),this.node.classList.add("cell-sort-up")):(this.node.classList.remove("cell-sort-up"),this.node.classList.add("cell-sort-down"));
d=this;c.splice(0);c.push([this.type,this.sortDirection]);chrome.storage.local.set({sortCells:c});n()},l=e.el("div",{class:["row","head__row"],on:["click",function(b){var d=e.closestNode(this,b.target);d&&(b.preventDefault(),a[d.dataset.type].sort())}]});b.forEach(function(b){var d=chrome.i18n.getMessage("row_"+b),c=chrome.i18n.getMessage("row_"+b+"__short")||d;d=e.el("a",{class:["cell","row__cell","cell-"+b],href:"#cell-"+b,data:{type:b},append:[e.el("span",{class:["cell__title"],title:d,text:c}),
e.el("i",{class:["cell__sort"]})]});a[b]={type:b,sortDirection:0,node:d,sort:f};l.appendChild(d)});return{node:e.el("div",{class:["table__head"],append:l}),cellTypeCell:a}},r=function(a,d,c,f,t){var h=e.el("div",{class:["row","body__row"],data:{filter:c}});b.forEach(function(b){if("date"===b)h.appendChild(e.el("div",{class:["cell","row__cell","cell-"+b],title:z(d.date),text:A(d.date)}));else if("quality"===b){var c=parseInt(d.quality);h.appendChild(e.el("div",{class:["cell","row__cell","cell-"+b],
append:[e.el("div",{class:["quality_box"],title:c,append:[e.el("div",{class:["quality_progress"],style:{width:d.quality/500*100+"%"}}),e.el("span",{class:["quality_value"],text:c})]})]}))}else if("title"===b){c="";d.categoryTitle&&(c=d.categoryUrl?e.el("a",{class:["category"],target:"_blank",href:d.categoryUrl,text:d.categoryTitle}):e.el("span",{class:["category"],text:d.categoryTitle}));var l=e.el("div",{class:["tracker__icon",a.iconClass],title:a.name});h.appendChild(e.el("div",{class:["cell","row__cell",
"cell-"+b],append:[e.el("div",{class:["cell__title"],append:[e.el("a",{class:["title"],data:{index:f},target:"_blank",href:d.url,append:[w.insert(d.title,t)]}),l]}),c&&e.el("div",{class:["cell__category"],append:[c,l]})]}))}else"size"===b?(c=y(d.size),d.downloadUrl&&(c=e.el("a",{class:["cell__download"],data:{index:f},target:"_blank",href:d.downloadUrl,text:c+String.fromCharCode(160)+String.fromCharCode(8595)})),h.appendChild(e.el("div",{class:["cell","row__cell","cell-"+b],append:c}))):"seed"===
b?h.appendChild(e.el("div",{class:["cell","row__cell","cell-"+b],text:d.seed})):"peer"===b&&h.appendChild(e.el("div",{class:["cell","row__cell","cell-"+b],text:d.peer}))});return h},q=[],p=[],n=function(){var a=q.slice(0);c.forEach(function(b){b=C[b[0]](b[1]);a.sort(b)});B(u.node,a,p)},v=null,u=null,m=null;this.counter=k;this.node=null;this.load=function(){v=g();u={node:e.el("div",{class:["body","table__body"],on:[["mouseup",function(a){D(a.target,q)}]]})};m={node:e.el("div",{class:["footer","table__footer"]}),
more:null};a.node=e.el("div",{class:["table","table-results"],append:[v.node,u.node,m.node]});c.forEach(function(a){v.cellTypeCell[a[0]].sort(a[1])})};this.insertResults=function(b,c,e){k[b.id]||(k[b.id]={filtered:0,all:0});var l=w.getMap(c),t=x.getScheme(c);e.forEach(function(e){if(!a.normalizeTorrent(d,b.id,e)){var g=f.getFilterValue(e),h=x.getRate(e,t);e.rate=h;e.quality=h.sum;h=r(b,e,g,q.length,l);q.push({node:h,query:c,torrent:e,tracker:b,filterValue:g});k[b.id].all++;g&&k[b.id].filtered++}});
n();e=!1;for(var g in k)if(k[g].filtered){e=!0;break}e?a.show():a.hide()};this.insertMoreBtn=function(a,b){var d=!1,c=m.more;c||(c=m.more={});c.trackerIds=b;c.node||(c.node=e.el("a",{class:["loadMore","search__submit","footer__loadMore"],href:"#more",text:chrome.i18n.getMessage("loadMore"),on:["click",function(b){b.preventDefault();var c=this;d||(d=!0,c.classList.add("loadMore-loading"),a(function(){c.parentNode&&c.parentNode.removeChild(c);m.more=null}))}]}),c.show=!0,m.node.appendChild(c.node))};
this.applyFilter=function(){var b=!1;for(g in k)k[g]={filtered:0,all:0};for(var d=0,c;c=q[d];d++){var e=f.getFilterValue(c.torrent);var g=c.torrent.trackerId;c.filterValue=e;c.node.dataset.filter=e;k[g].all++;e&&(b=!0,k[g].filtered++)}if(g=m.more)g.trackerIds.every(function(a){return!f.isFilteredTracker(a)})?g.show&&(g.node.classList.add("loadMore-hidden"),g.show=!1):g.show||(g.node.classList.remove("loadMore-hidden"),g.show=!0);b?a.show():a.hide()};this.visible=!0;this.show=function(){a.visible||
(a.node.classList.remove("table-hide"),a.visible=!0)};this.hide=function(){a.visible&&(a.node.classList.add("table-hide"),a.visible=!1)};this.destroy=function(){var b=a.node.parentNode;b&&b.removeChild(a.node)}};p.prototype.normalizeTorrent=function(e,d,a){a.trackerId=d;a.size&&(a.size=parseInt(a.size),isNaN(a.size)&&(a.size=null));a.size||(a.size=0);a.seed&&(a.seed=parseInt(a.seed),isNaN(a.seed)&&(a.seed=null));a.seed||(a.seed=1);a.peer&&(a.peer=parseInt(a.peer),isNaN(a.peer)&&(a.peer=null));a.peer||
(a.peer=0);a.date&&(a.date=parseInt(a.date),isNaN(a.date)&&(a.date=null));a.date||(a.date=-1);a.categoryTitle||(a.categoryTitle="");if(!a.title||!a.url)return console.debug("["+d+"]","Skip torrent:",a),!0;a.titleLow=a.title.toLowerCase();a.categoryTitleLow=a.categoryTitle.toLowerCase();a.wordFilterLow=a.titleLow;e.categoryWordFilter&&(a.wordFilterLow=a.categoryTitleLow+" "+a.wordFilterLow);a.categoryUrl||(a.categoryUrl="");a.downloadUrl||(a.downloadUrl="");return!1};return p});
