define(function(){var g={param:function(a){var b=[],c;for(c in a){var d=a[c];null!==d&&void 0!==d&&b.push(encodeURIComponent(c)+"="+encodeURIComponent(d))}return b.join("&")},parseUrl:function(a,b){b=b||{};a=(!b.params&&/\?/.test(a)?a.match(/[^?]*\?(.*)/)[1]:a).split(b.sep||"&");for(var c={},d=0,f=a.length;d<f;d++){var e=a[d].split("="),g=e[0];e=e[1]||"";if(b.noDecode)c[g]=e;else{try{g=decodeURIComponent(g)}catch(h){g=unescape(g)}try{c[g]=decodeURIComponent(e)}catch(h){c[g]=unescape(e)}}}return c},
hashParam:function(a){var b={},c=0,d;for(d in a)c++,b[d]=btoa(unescape(encodeURIComponent(a[d])));c&&(b.base64=!0);return g.param(b)},hashParseParam:function(a){var b={};a=g.parseUrl(a,{params:!0});if(a.base64)for(var c in a){if("base64"!==c)try{b[c]=decodeURIComponent(escape(atob(a[c])))}catch(d){console.error("Error decode param",c,a[c],d)}}else b=a;return b},parseXhrHeader:function(a){a=a.split(/\r?\n/);var b={};a.forEach(function(a){var c=a.indexOf(":");if(-1!==c){var f=a.substr(0,c).trim().toLowerCase();
a=a.substr(c+1).trim();b[f]=a}});return b},request:function(a,b){var c={},d=function(c,f){d=null;h.timeoutTimer&&clearTimeout(h.timeoutTimer);if(b){var e={};e.statusCode=k.status;e.statusText=k.statusText;e.url=k.responseURL||a.url;var l=null,m=k.getAllResponseHeaders();"string"===typeof m&&(l=g.parseXhrHeader(m));e.headers=l||{};e.body=f;b(c,e)}};"object"!==typeof a&&(a={url:a});var f=a.url,e=a.method||a.type||"GET";e=e.toUpperCase();var l=a.data;"string"!==typeof l&&(l=g.param(l));l&&"GET"===e&&
(f+=(/\?/.test(f)?"&":"?")+l,l=void 0);!1===a.cache&&-1!==["GET","HEAD"].indexOf(e)&&(f+=(/\?/.test(f)?"&":"?")+"_="+Date.now());a.headers=a.headers||{};l&&(a.headers["Content-Type"]=a.contentType||a.headers["Content-Type"]||"application/x-www-form-urlencoded; charset=UTF-8");var h={};h.url=f;h.method=e;l&&(h.data=l);a.json&&(h.json=!0);a.timeout&&(h.timeout=a.timeout);a.mimeType&&(h.mimeType=a.mimeType);a.withCredentials&&(h.withCredentials=!0);Object.keys(a.headers).length&&(h.headers=a.headers);
0<h.timeout&&(h.timeoutTimer=setTimeout(function(){d&&d(Error("ETIMEDOUT"));k.abort()},h.timeout));f=function(){var a={0:200,1223:204}[k.status]||k.status;try{if(200<=a&&300>a||304===a){var b=k.responseText;if("string"!==typeof b)throw Error("Response is not string!");h.json&&(b=JSON.parse(b));return d&&d(null,b)}throw Error(k.status+" "+k.statusText);}catch(q){return d&&d(q)}};var n=function(){d&&d(Error(k.status+" "+k.statusText))};try{var k=new XMLHttpRequest;k.open(h.method,h.url,!0);h.mimeType&&
k.overrideMimeType(h.mimeType);h.withCredentials&&(k.withCredentials=!0);for(var p in h.headers)k.setRequestHeader(p,h.headers[p]);k.onload=f;k.onerror=n;void 0!==k.onabort?k.onabort=n:k.onreadystatechange=function(){4===k.readyState&&d&&setTimeout(function(){return n()})};k.send(h.data||null)}catch(m){setTimeout(function(){d&&d(m)})}c.abort=function(){d=null;k.abort()};return c},getUuid:function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;return("x"==
a?b:b&3|8).toString(16)})},bindClearBtn:function(a,b){var c=!1;b.addEventListener("keyup",function(){0<this.value.length?c||(c=!0,a.classList.add("input__clear_visible")):c&&(c=!1,a.classList.remove("input__clear_visible"))});a.addEventListener("click",function(a){a.preventDefault();b.value="";b.dispatchEvent(new CustomEvent("keyup"));b.focus()})},bindDblClickClear:function(a){Array.isArray(a)||(a=[a]);a.forEach(function(a){a.addEventListener("dblclick",function(){this.value="";this.dispatchEvent(new CustomEvent("keyup"))})})}},
r=/[\-\[\]{}()*+?.,\\\^$|#\s]/g;g.sanitizeTextRe=function(a){return a.replace(r,"\\$&")};g.throttle=function(a,b){var c=0,d=null;return function(){clearTimeout(d);var f=arguments,e=Date.now();e-c>b?(c=e,a.apply(null,f)):d=setTimeout(function(){a.apply(null,f)},b)}};g.parseMeta=function(a){var b={},c=!1,d={name:"string",version:"string",author:"string",description:"string",homepageURL:"string",icon:"string",icon64:"string",trackerURL:"string",updateURL:"string",downloadURL:"string",supportURL:"string",
require:"array",connect:"array"};a.split(/\r?\n/).some(function(a){if(/^\s*\/\//.test(a)){!c&&/[=]+UserScript[=]+/.test(a)&&(c=!0);if(c&&/[=]+\/UserScript[=]+/.test(a))return c=!1,!0;if(c){var e=/^\s*\/\/\s*@([A-Za-z0-9]+)\s+(.+)$/.exec(a);if(e){a=e[1];e=e[2].trim();var f=d[a];"string"===f?b[a]=e:"array"===f&&(b[a]||(b[a]=[]),b[a].push(e))}}}});if(!Object.keys(b).length)throw Error("Meta data is not found!");if(!b.name)throw Error("Name field is not found!");if(!b.version)throw Error("Version field is not found!");
if(!b.connect)throw Error("Connect field is not found!");b.connect=b.connect.filter(function(a){return!!a});if(!b.connect.length)throw Error("Connect field is empty!");if(!/^[\d.]+$/.test(b.version))throw Error("Version field is not correct!");return b};g.isNewVersion=function(a,b){var c=/^[\d.]+$/;if(!c.test(a)||!c.test(b))throw Error("Incorrect version");c=function(a,b){for(;a.length<b;)a="0"+a;return a};a=a.split(".");b=b.split(".");for(var d=0;d<b.length;d++){var f=a[d]||"",e=b[d]||"",g=Math.max(f.length,
e.length);f=parseInt(c(f,g));e=parseInt(c(e,g));if(e!==f)return e>f}return!1};g.escapeRegex=function(a){return a.replace(/[\-\[\]{}()*+?.,\\\^$|#\s]/g,"\\$&")};g.urlPatternToStrRe=function(a){a=/^(\*|http|https):\/\/([^\/]+)(?:\/(.*))?$/.exec(a);if(!a)throw Error("Invalid url-pattern");var b=a[1];"*"===b&&(b="https?");var c=a[2];c=g.escapeRegex(c);c=c.replace(/^\\\*\\\./,"(?:[^/]+\\.)?");b=["^",b,":\\/\\/",c];a=a[3];a?"*"===a?b.push("(?:|/.*)","$"):a&&(a=g.escapeRegex("/"+a),a=a.replace(/\\\*/g,".*"),
b.push(a,"$")):b.push("$");return b.join("")};g.getDiffObj=function(a,b){var c=[],d=[],f=[],e;for(e in a)a.hasOwnProperty(e)&&(b.hasOwnProperty(e)?JSON.stringify(a[e])!==JSON.stringify(b[e])&&d.push(e):c.push(e));for(e in b)b.hasOwnProperty(e)&&(a.hasOwnProperty(e)||f.push(e));return{removed:c,modified:d,new:f}};g.clone=function(a){return JSON.parse(JSON.stringify({w:a})).w};g.isPunctuation=function(a){if(void 0===a)return!0;a=a.charCodeAt(0);return 31>a?!1:31<a&&48>a||57<a&&65>a||90<a&&97>a||122<
a&&127>a||-1!==[171,174,169,187,8222,8221,8220].indexOf(a)?!0:!1};g.isBoundary=function(a,b){return g.isPunctuation(a)&&g.isPunctuation(b)};g.extend=function(){for(var a=arguments[0],b=1,c=arguments.length;b<c;b++){var d=arguments[b],f;for(f in d)void 0!==d[f]&&(a[f]=d[f])}return a};g.isEmptyObject=function(a){for(var b in a)return!1;return!0};g.getItemId=function(a,b){var c=null;if(Array.isArray(a))a.some(function(a){if(a.id===b)return c=a,!0});else if("object"===typeof a)for(var d in a){var f=a[d];
if(f.id===b){c=f;break}}return c};g.trackerObjToUserScript=function(a){var b=[],c=[];c.unshift("==UserScript==");c.push(["@name",a.title].join(" "));a.desc&&c.push(["@description",a.desc].join(" "));a.icon&&c.push(["@icon",a.icon].join(" "));a.downloadUrl&&c.push(["@downloadURL",a.downloadUrl].join(" "));var d=/\/\/([^\/]+)/.exec(a.search.searchUrl);d&&c.push(["@connect","*://"+d[1]+"/*"].join(" "));a.search.baseUrl&&c.push(["@trackerURL",a.search.baseUrl].join(" "));a.tVersion?c.push(["@version",
a.tVersion].join(" ")):c.push("@version 1.0");c.push("@require exKit");c.push("==/UserScript==");b.push.apply(b,c.map(function(a){return["//",a].join(" ")}));b.push("");b.push("var code = "+JSON.stringify(a,null,2)+";");b.push("");b.push("API_exKit(code);");return b.join("\n")};return g});
