
var JSON;if(!JSON){JSON={};}
(function(){"use strict";function f(n){return n<10?'0'+n:n;}
if(typeof Date.prototype.toJSON!=='function'){Date.prototype.toJSON=function(key){return isFinite(this.valueOf())?this.getUTCFullYear()+'-'+
f(this.getUTCMonth()+1)+'-'+
f(this.getUTCDate())+'T'+
f(this.getUTCHours())+':'+
f(this.getUTCMinutes())+':'+
f(this.getUTCSeconds())+'Z':null;};String.prototype.toJSON=Number.prototype.toJSON=Boolean.prototype.toJSON=function(key){return this.valueOf();};}
var cx=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,escapable=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,gap,indent,meta={'\b':'\\b','\t':'\\t','\n':'\\n','\f':'\\f','\r':'\\r','"':'\\"','\\':'\\\\'},rep;function quote(string){escapable.lastIndex=0;return escapable.test(string)?'"'+string.replace(escapable,function(a){var c=meta[a];return typeof c==='string'?c:'\\u'+('0000'+a.charCodeAt(0).toString(16)).slice(-4);})+'"':'"'+string+'"';}
function str(key,holder){var i,k,v,length,mind=gap,partial,value=holder[key];if(value&&typeof value==='object'&&typeof value.toJSON==='function'){value=value.toJSON(key);}
if(typeof rep==='function'){value=rep.call(holder,key,value);}
switch(typeof value){case'string':return quote(value);case'number':return isFinite(value)?String(value):'null';case'boolean':case'null':return String(value);case'object':if(!value){return'null';}
gap+=indent;partial=[];if(Object.prototype.toString.apply(value)==='[object Array]'){length=value.length;for(i=0;i<length;i+=1){partial[i]=str(i,value)||'null';}
v=partial.length===0?'[]':gap?'[\n'+gap+partial.join(',\n'+gap)+'\n'+mind+']':'['+partial.join(',')+']';gap=mind;return v;}
if(rep&&typeof rep==='object'){length=rep.length;for(i=0;i<length;i+=1){if(typeof rep[i]==='string'){k=rep[i];v=str(k,value);if(v){partial.push(quote(k)+(gap?': ':':')+v);}}}}else{for(k in value){if(Object.prototype.hasOwnProperty.call(value,k)){v=str(k,value);if(v){partial.push(quote(k)+(gap?': ':':')+v);}}}}
v=partial.length===0?'{}':gap?'{\n'+gap+partial.join(',\n'+gap)+'\n'+mind+'}':'{'+partial.join(',')+'}';gap=mind;return v;}}
if(typeof JSON.stringify!=='function'){JSON.stringify=function(value,replacer,space){var i;gap='';indent='';if(typeof space==='number'){for(i=0;i<space;i+=1){indent+=' ';}}else if(typeof space==='string'){indent=space;}
rep=replacer;if(replacer&&typeof replacer!=='function'&&(typeof replacer!=='object'||typeof replacer.length!=='number')){throw new Error('JSON.stringify');}
return str('',{'':value});};}
if(typeof JSON.parse!=='function'){JSON.parse=function(text,reviver){var j;function walk(holder,key){var k,v,value=holder[key];if(value&&typeof value==='object'){for(k in value){if(Object.prototype.hasOwnProperty.call(value,k)){v=walk(value,k);if(v!==undefined){value[k]=v;}else{delete value[k];}}}}
return reviver.call(holder,key,value);}
text=String(text);cx.lastIndex=0;if(cx.test(text)){text=text.replace(cx,function(a){return'\\u'+
('0000'+a.charCodeAt(0).toString(16)).slice(-4);});}
if(/^[\],:{}\s]*$/.test(text.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,'@').replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,']').replace(/(?:^|:|,)(?:\s*\[)+/g,''))){j=eval('('+text+')');return typeof reviver==='function'?walk({'':j},''):j;}
throw new SyntaxError('JSON.parse');};}}());(function(){var
JSTORAGE_VERSION="0.4.8",$=window.jQuery||window.$||(window.$={}),JSON={parse:window.JSON&&(window.JSON.parse||window.JSON.decode)||String.prototype.evalJSON&&function(str){return String(str).evalJSON();}||$.parseJSON||$.evalJSON,stringify:Object.toJSON||window.JSON&&(window.JSON.stringify||window.JSON.encode)||$.toJSON};if(!("parse"in JSON)||!("stringify"in JSON)){throw new Error("No JSON support found, include //cdnjs.cloudflare.com/ajax/libs/json2/20110223/json2.js to page");}
var
_storage={__jstorage_meta:{CRC32:{}}},_storage_service={jStorage:"{}"},_storage_elm=null,_storage_size=0,_backend=false,_observers={},_observer_timeout=false,_observer_update=0,_pubsub_observers={},_pubsub_last=+new Date(),_ttl_timeout,_XMLService={isXML:function(elm){var documentElement=(elm?elm.ownerDocument||elm:0).documentElement;return documentElement?documentElement.nodeName!=="HTML":false;},encode:function(xmlNode){if(!this.isXML(xmlNode)){return false;}
try{return new XMLSerializer().serializeToString(xmlNode);}catch(E1){try{return xmlNode.xml;}catch(E2){}}
return false;},decode:function(xmlString){var dom_parser=("DOMParser"in window&&(new DOMParser()).parseFromString)||(window.ActiveXObject&&function(_xmlString){var xml_doc=new ActiveXObject("Microsoft.XMLDOM");xml_doc.async="false";xml_doc.loadXML(_xmlString);return xml_doc;}),resultXML;if(!dom_parser){return false;}
resultXML=dom_parser.call("DOMParser"in window&&(new DOMParser())||window,xmlString,"text/xml");return this.isXML(resultXML)?resultXML:false;}};function _init(){var localStorageReallyWorks=false;if("localStorage"in window){try{window.localStorage.setItem("_tmptest","tmpval");localStorageReallyWorks=true;window.localStorage.removeItem("_tmptest");}catch(BogusQuotaExceededErrorOnIos5){}}
if(localStorageReallyWorks){try{if(window.localStorage){_storage_service=window.localStorage;_backend="localStorage";_observer_update=_storage_service.jStorage_update;}}catch(E3){}}
else if("globalStorage"in window){try{if(window.globalStorage){if(window.location.hostname=="localhost"){_storage_service=window.globalStorage["localhost.localdomain"];}
else{_storage_service=window.globalStorage[window.location.hostname];}
_backend="globalStorage";_observer_update=_storage_service.jStorage_update;}}catch(E4){}}
else{_storage_elm=document.createElement("link");if(_storage_elm.addBehavior){_storage_elm.style.behavior="url(#default#userData)";document.getElementsByTagName("head")[0].appendChild(_storage_elm);try{_storage_elm.load("jStorage");}catch(E){_storage_elm.setAttribute("jStorage","{}");_storage_elm.save("jStorage");_storage_elm.load("jStorage");}
var data="{}";try{data=_storage_elm.getAttribute("jStorage");}catch(E5){}
try{_observer_update=_storage_elm.getAttribute("jStorage_update");}catch(E6){}
_storage_service.jStorage=data;_backend="userDataBehavior";}else{_storage_elm=null;return;}}
_load_storage();_handleTTL();_setupObserver();_handlePubSub();if("addEventListener"in window){window.addEventListener("pageshow",function(event){if(event.persisted){_storageObserver();}},false);}}
function _reloadData(){var data="{}";if(_backend=="userDataBehavior"){_storage_elm.load("jStorage");try{data=_storage_elm.getAttribute("jStorage");}catch(E5){}
try{_observer_update=_storage_elm.getAttribute("jStorage_update");}catch(E6){}
_storage_service.jStorage=data;}
_load_storage();_handleTTL();_handlePubSub();}
function _setupObserver(){if(_backend=="localStorage"||_backend=="globalStorage"){if("addEventListener"in window){window.addEventListener("storage",_storageObserver,false);}else{document.attachEvent("onstorage",_storageObserver);}}else if(_backend=="userDataBehavior"){setInterval(_storageObserver,1000);}}
function _storageObserver(){var updateTime;clearTimeout(_observer_timeout);_observer_timeout=setTimeout(function(){if(_backend=="localStorage"||_backend=="globalStorage"){updateTime=_storage_service.jStorage_update;}else if(_backend=="userDataBehavior"){_storage_elm.load("jStorage");try{updateTime=_storage_elm.getAttribute("jStorage_update");}catch(E5){}}
if(updateTime&&updateTime!=_observer_update){_observer_update=updateTime;_checkUpdatedKeys();}},25);}
function _checkUpdatedKeys(){var oldCrc32List=JSON.parse(JSON.stringify(_storage.__jstorage_meta.CRC32)),newCrc32List;_reloadData();newCrc32List=JSON.parse(JSON.stringify(_storage.__jstorage_meta.CRC32));var key,updated=[],removed=[];for(key in oldCrc32List){if(oldCrc32List.hasOwnProperty(key)){if(!newCrc32List[key]){removed.push(key);continue;}
if(oldCrc32List[key]!=newCrc32List[key]&&String(oldCrc32List[key]).substr(0,2)=="2."){updated.push(key);}}}
for(key in newCrc32List){if(newCrc32List.hasOwnProperty(key)){if(!oldCrc32List[key]){updated.push(key);}}}
_fireObservers(updated,"updated");_fireObservers(removed,"deleted");}
function _fireObservers(keys,action){keys=[].concat(keys||[]);if(action=="flushed"){keys=[];for(var key in _observers){if(_observers.hasOwnProperty(key)){keys.push(key);}}
action="deleted";}
for(var i=0,len=keys.length;i<len;i++){if(_observers[keys[i]]){for(var j=0,jlen=_observers[keys[i]].length;j<jlen;j++){_observers[keys[i]][j](keys[i],action);}}
if(_observers["*"]){for(var j=0,jlen=_observers["*"].length;j<jlen;j++){_observers["*"][j](keys[i],action);}}}}
function _publishChange(){var updateTime=(+new Date()).toString();if(_backend=="localStorage"||_backend=="globalStorage"){try{_storage_service.jStorage_update=updateTime;}catch(E8){_backend=false;}}else if(_backend=="userDataBehavior"){_storage_elm.setAttribute("jStorage_update",updateTime);_storage_elm.save("jStorage");}
_storageObserver();}
function _load_storage(){if(_storage_service.jStorage){try{_storage=JSON.parse(String(_storage_service.jStorage));}catch(E6){_storage_service.jStorage="{}";}}else{_storage_service.jStorage="{}";}
_storage_size=_storage_service.jStorage?String(_storage_service.jStorage).length:0;if(!_storage.__jstorage_meta){_storage.__jstorage_meta={};}
if(!_storage.__jstorage_meta.CRC32){_storage.__jstorage_meta.CRC32={};}}
function _save(){_dropOldEvents();try{_storage_service.jStorage=JSON.stringify(_storage);if(_storage_elm){_storage_elm.setAttribute("jStorage",_storage_service.jStorage);_storage_elm.save("jStorage");}
_storage_size=_storage_service.jStorage?String(_storage_service.jStorage).length:0;}catch(E7){}}
function _checkKey(key){if(typeof key!="string"&&typeof key!="number"){throw new TypeError("Key name must be string or numeric");}
if(key=="__jstorage_meta"){throw new TypeError("Reserved key name");}
return true;}
function _handleTTL(){var curtime,i,TTL,CRC32,nextExpire=Infinity,changed=false,deleted=[];clearTimeout(_ttl_timeout);if(!_storage.__jstorage_meta||typeof _storage.__jstorage_meta.TTL!="object"){return;}
curtime=+new Date();TTL=_storage.__jstorage_meta.TTL;CRC32=_storage.__jstorage_meta.CRC32;for(i in TTL){if(TTL.hasOwnProperty(i)){if(TTL[i]<=curtime){delete TTL[i];delete CRC32[i];delete _storage[i];changed=true;deleted.push(i);}else if(TTL[i]<nextExpire){nextExpire=TTL[i];}}}
if(nextExpire!=Infinity){_ttl_timeout=setTimeout(_handleTTL,nextExpire-curtime);}
if(changed){_save();_publishChange();_fireObservers(deleted,"deleted");}}
function _handlePubSub(){var i,len;if(!_storage.__jstorage_meta.PubSub){return;}
var pubelm,_pubsubCurrent=_pubsub_last;for(i=len=_storage.__jstorage_meta.PubSub.length-1;i>=0;i--){pubelm=_storage.__jstorage_meta.PubSub[i];if(pubelm[0]>_pubsub_last){_pubsubCurrent=pubelm[0];_fireSubscribers(pubelm[1],pubelm[2]);}}
_pubsub_last=_pubsubCurrent;}
function _fireSubscribers(channel,payload){if(_pubsub_observers[channel]){for(var i=0,len=_pubsub_observers[channel].length;i<len;i++){try{_pubsub_observers[channel][i](channel,JSON.parse(JSON.stringify(payload)));}catch(E){};}}}
function _dropOldEvents(){if(!_storage.__jstorage_meta.PubSub){return;}
var retire=+new Date()-2000;for(var i=0,len=_storage.__jstorage_meta.PubSub.length;i<len;i++){if(_storage.__jstorage_meta.PubSub[i][0]<=retire){_storage.__jstorage_meta.PubSub.splice(i,_storage.__jstorage_meta.PubSub.length-i);break;}}
if(!_storage.__jstorage_meta.PubSub.length){delete _storage.__jstorage_meta.PubSub;}}
function _publish(channel,payload){if(!_storage.__jstorage_meta){_storage.__jstorage_meta={};}
if(!_storage.__jstorage_meta.PubSub){_storage.__jstorage_meta.PubSub=[];}
_storage.__jstorage_meta.PubSub.unshift([+new Date,channel,payload]);_save();_publishChange();}
function murmurhash2_32_gc(str,seed){var
l=str.length,h=seed^l,i=0,k;while(l>=4){k=((str.charCodeAt(i)&0xff))|((str.charCodeAt(++i)&0xff)<<8)|((str.charCodeAt(++i)&0xff)<<16)|((str.charCodeAt(++i)&0xff)<<24);k=(((k&0xffff)*0x5bd1e995)+((((k>>>16)*0x5bd1e995)&0xffff)<<16));k^=k>>>24;k=(((k&0xffff)*0x5bd1e995)+((((k>>>16)*0x5bd1e995)&0xffff)<<16));h=(((h&0xffff)*0x5bd1e995)+((((h>>>16)*0x5bd1e995)&0xffff)<<16))^k;l-=4;++i;}
switch(l){case 3:h^=(str.charCodeAt(i+2)&0xff)<<16;case 2:h^=(str.charCodeAt(i+1)&0xff)<<8;case 1:h^=(str.charCodeAt(i)&0xff);h=(((h&0xffff)*0x5bd1e995)+((((h>>>16)*0x5bd1e995)&0xffff)<<16));}
h^=h>>>13;h=(((h&0xffff)*0x5bd1e995)+((((h>>>16)*0x5bd1e995)&0xffff)<<16));h^=h>>>15;return h>>>0;}
$.jStorage={version:JSTORAGE_VERSION,set:function(key,value,options){_checkKey(key);options=options||{};if(typeof value=="undefined"){this.deleteKey(key);return value;}
if(_XMLService.isXML(value)){value={_is_xml:true,xml:_XMLService.encode(value)};}else if(typeof value=="function"){return undefined;}else if(value&&typeof value=="object"){value=JSON.parse(JSON.stringify(value));}
_storage[key]=value;_storage.__jstorage_meta.CRC32[key]="2."+murmurhash2_32_gc(JSON.stringify(value),0x9747b28c);this.setTTL(key,options.TTL||0);_fireObservers(key,"updated");return value;},get:function(key,def){_checkKey(key);if(key in _storage){if(_storage[key]&&typeof _storage[key]=="object"&&_storage[key]._is_xml){return _XMLService.decode(_storage[key].xml);}else{return _storage[key];}}
return typeof(def)=="undefined"?null:def;},deleteKey:function(key){_checkKey(key);if(key in _storage){delete _storage[key];if(typeof _storage.__jstorage_meta.TTL=="object"&&key in _storage.__jstorage_meta.TTL){delete _storage.__jstorage_meta.TTL[key];}
delete _storage.__jstorage_meta.CRC32[key];_save();_publishChange();_fireObservers(key,"deleted");return true;}
return false;},setTTL:function(key,ttl){var curtime=+new Date();_checkKey(key);ttl=Number(ttl)||0;if(key in _storage){if(!_storage.__jstorage_meta.TTL){_storage.__jstorage_meta.TTL={};}
if(ttl>0){_storage.__jstorage_meta.TTL[key]=curtime+ttl;}else{delete _storage.__jstorage_meta.TTL[key];}
_save();_handleTTL();_publishChange();return true;}
return false;},getTTL:function(key){var curtime=+new Date(),ttl;_checkKey(key);if(key in _storage&&_storage.__jstorage_meta.TTL&&_storage.__jstorage_meta.TTL[key]){ttl=_storage.__jstorage_meta.TTL[key]-curtime;return ttl||0;}
return 0;},flush:function(){_storage={__jstorage_meta:{CRC32:{}}};_save();_publishChange();_fireObservers(null,"flushed");return true;},storageObj:function(){function F(){}
F.prototype=_storage;return new F();},index:function(){var index=[],i;for(i in _storage){if(_storage.hasOwnProperty(i)&&i!="__jstorage_meta"){index.push(i);}}
return index;},storageSize:function(){return _storage_size;},currentBackend:function(){return _backend;},storageAvailable:function(){return!!_backend;},listenKeyChange:function(key,callback){_checkKey(key);if(!_observers[key]){_observers[key]=[];}
_observers[key].push(callback);},stopListening:function(key,callback){_checkKey(key);if(!_observers[key]){return;}
if(!callback){delete _observers[key];return;}
for(var i=_observers[key].length-1;i>=0;i--){if(_observers[key][i]==callback){_observers[key].splice(i,1);}}},subscribe:function(channel,callback){channel=(channel||"").toString();if(!channel){throw new TypeError("Channel not defined");}
if(!_pubsub_observers[channel]){_pubsub_observers[channel]=[];}
_pubsub_observers[channel].push(callback);},publish:function(channel,payload){channel=(channel||"").toString();if(!channel){throw new TypeError("Channel not defined");}
_publish(channel,payload);},reInit:function(){_reloadData();},noConflict:function(saveInGlobal){delete window.$.jStorage
if(saveInGlobal){window.jStorage=this;}
return this;}};_init();})();var CATEGORY_ALL=-1;var CATEGORY_FREE=0;var CATEGORY_DEAL=1;var CATEGORY_BEST=2;var CATEGORY_BOOK_OF_DAY=3;var CATEGORY_FEATIURED_BOOK=4;var MSEC_IN_DAY=86400000;Genre={ROMANCE:0,EROTICA:1,THRILLERS:2,FANTASY:3,HIST_FICTION:4,CHRISTIAN:5,RELIGIOUS:6,CHILDREN:7,VARIOUS:8,NON_FICTION:9,OTHER_LANG:10};var filter={showOnlyRecommended:false,showFree:true,showDeals:true};var genres=[{id:Genre.EROTICA,name:'Erotica',pattern:/Erotic|Steamy|Explicit/i,description:"Erotica",value:false},{id:Genre.CHRISTIAN,name:'Christian',pattern:/Christian/i,description:"Christian",value:true},{id:Genre.RELIGIOUS,name:'Religious',pattern:/Religio|Spiritual/i,description:"Religious (non-Christian Religious)",value:true},{id:Genre.CHILDREN,name:'Children',pattern:/Child|YA|Young Adult|Kid|Teen/i,description:"Children & Young Adult",value:true},{id:Genre.ROMANCE,name:'Romance',pattern:/Romance|Romantic|Love/i,description:"Romance",value:true},{id:Genre.THRILLERS,name:'Thriller',pattern:/Thriller|Myster|Suspense/i,description:"Thrillers & Mysteries",value:true},{id:Genre.FANTASY,name:'Fantasy',pattern:/Fantasy|Science Fiction|Horror/i,description:"Fantasy, Science Fiction & Horror",value:true},{id:Genre.HIST_FICTION,name:'HistFiction',pattern:/Historical/i,description:"Historical Fiction",value:true},{id:Genre.OTHER_LANG,name:'OtherLang',pattern:/Language/i,description:"Other Languages (Very Rare)",value:true},{id:Genre.VARIOUS,name:'Various',pattern:/Fiction|Litera|Adventure|Contemporary|Poetry|Classics/i,exclude:/Non Fiction/i,description:"Various Genres (Fiction) including Adventure",value:true},{id:Genre.NON_FICTION,name:'NonFiction',pattern:/.*/,description:"Non Fiction",value:true}];var sortedGenres=genres.slice().sort(function(a,b){if(a.id==b.id)return 0;else if(a.id<b.id)return-1;else return 1;});function getBooks(sourceDef,completedFunc){sourceDef.isError=false;var results=[];$.get(sourceDef.url,function(xml){var todayDate=new Date();todayDate.setHours(0,0,0,0);var posts=0;$(xml).find("item").each(function(){try{var item=$(this);var title=item.find("> title").text();var pubDate=new Date(item.find("pubDate").text());var cpPubDate=new Date(pubDate.getTime());var content=item.text();pubDate.setHours(0,0,0,0);if(pubDate.getTime()==todayDate.getTime()){if(parseBooks(sourceDef.bookPattern,sourceDef.category,content,results)>0){posts++;if(!sourceDef.isToday){sourceDef.lastPostTime=cpPubDate;}
sourceDef.isToday=true;}}else if((todayDate.getTime()-pubDate.getTime())/MSEC_IN_DAY<=sourceDef.maxDaysOld&&posts==0){if(parseBooks(sourceDef.bookPattern,sourceDef.category,content,results)>0)posts++;}else{return false;}}
catch(e){console.log(e);}});completedFunc(results);}).error(function(){console.log('Error');sourceDef.isError=true;completedFunc();});}
function parseBooks(pattern,category,content,books){var count=0;var re=new RegExp(pattern,"ig");var reFree=/^(free|\$?0|\$?0.00)$/i;var reBookOfDay=/of the Day/i;var reFeatured=/featured|sponsor/i;for(;;){var match=re.exec(content);if(match===null)break;var priceStr=match[5];var isFree=reFree.test(priceStr);var isBookOfDay=reBookOfDay.test(match[0]);if(category===CATEGORY_FREE){if(!isFree)continue;}else if(category===CATEGORY_DEAL){if(isFree)continue;}else if(category===CATEGORY_BOOK_OF_DAY){if(!isBookOfDay)continue;}
var bookData={url:match[2],title:match[3],author:match[4],price:isFree?'Free':priceStr,category:isFree?CATEGORY_FREE:CATEGORY_DEAL,genres:match[6],rating:match[7],reviews:match[8],recommend:match[1].length,bookOfDay:isBookOfDay,featured:reFeatured.test(match[0])};for(var j=0;j<genres.length;j++){var genre=genres[j];if(genre.exclude){if(genre.exclude.test(bookData.genres))continue;}
if(genre.pattern.test(bookData.genres)){bookData.genre=genre.id;break;}}
books.push(bookData);count++;}
return count;}
function getRecommendedString(recommend){var s=null;switch(recommend){case 0:break;case 1:s="Recommended";break;case 2:s="Strongly Recommended";break;default:s="Get it Now!";break;}
return s;}
var booksSources=[{id:'Free',title:'Kindle Free Books',url:'http://kebooks.com/category/free-kindle-books/feed/',category:CATEGORY_FREE,maxDaysOld:1,bookPattern:'<li.*?>(\\**).*?<a href="(.*?)">(.*?)<.*?<strong>(.*?)</strong>.*?Price:\\s+(.*?)\\.\\s+.*?Genre:\\s+(.*?)\\..*?Rated.*?(\\d(?:\\.\\d)?)\\s+stars.*?(\\d+)',subscribeId:'Kindle',subscribeUrl:'http://forms.aweber.com/form/84/1845176184.htm',blogUrl:'http://www.kebooks.com'},{id:'Deals',title:'Kindle Book Deals',url:'http://kebooks.com/category/free-kindle-books/feed/',category:CATEGORY_DEAL,maxDaysOld:1,bookPattern:'<li.*?>(\\**).*?<a href="(.*?)">(.*?)<.*?<strong>(.*?)</strong>.*?Price:\\s+(.*?)\\.\\s+.*?Genre:\\s+(.*?)\\..*?Rated.*?(\\d(?:\\.\\d)?)\\s+stars.*?(\\d+)',subscribeId:'Kindle',subscribeUrl:'http://forms.aweber.com/form/84/1845176184.htm',blogUrl:'http://www.kebooks.com'}];var firstBookSource='Free';var showBooksOfDayPopup=true;var showFeaturedBooks=true;var selectedBookSource;$(document).delegate("#mainPage","pagebeforecreate",function(){$('#formHeader').bind("keyup keypress",function(e){var code=e.keyCode||e.which;if(code==13){e.preventDefault();return false;}});initSourceSelector();initFilter();initSorting();$('#filterBasic-input').attr('placeholder','Search for book title or author\'s name...');$('#btnBlog').click(function(){chrome.tabs.create({url:selectedBookSource.blogUrl});});$('#btnZFB').click(function(){chrome.tabs.create({url:'http://www.zerofrictionbooks.com/free/today'});});$('#centerMessage').hide();if(showBooksOfDayPopup){$('#btnBookOfDay').click(function(){openBooksOfTheDayPopup();});initBooksOfTheDayPopup();}else{$('#btnBookOfDay').hide();}});$(document).delegate("#mainPage","pageinit",function(){});$(function(){document.title=chrome.runtime.getManifest().name;setTimeout(function(){allLoading();},200);});function initSourceSelector(){var selectedBookSourceId=$.jStorage.get('SelectedBookSource',firstBookSource);if(booksSources.length>1){var selectorFieldset=$('#sourceSelector');var groupId='radio-books-source';for(var i=0;i<booksSources.length;i++){var item=booksSources[i];var radioId=groupId+item.id;var radio=$('<input/>',{'name':groupId,'id':radioId,'type':'radio','value':item.id});if(item.id==selectedBookSourceId){selectedBookSource=item;updateSusbcribing(selectedBookSource);radio.attr('checked','checked');}
selectorFieldset.append(radio);selectorFieldset.append($('<label/>',{'for':radioId,'text':item.title}));}
selectorFieldset.on('change',function(){var id=$(this).find(':checked').val();$.jStorage.set('SelectedBookSource',id);for(var i=0;i<booksSources.length;i++){var item=booksSources[i];if(item.id==id){selectedBookSource=item;break;}}
$('#filterBasic-input').val('');updateSusbcribing(selectedBookSource);refreshList();});}else{$('#sourceSelector').hide();selectedBookSource=booksSources[0];updateSusbcribing(selectedBookSource);}}
function initFilter(){var checkOnlyRecommended=$('#checkOnlyRecommended');filter.showOnlyRecommended=$.jStorage.get('ShowOnlyRecommended',filter.showOnlyRecommended);checkOnlyRecommended.prop('checked',filter.showOnlyRecommended);checkOnlyRecommended.on('change',function(){filter.showOnlyRecommended=$(this).prop('checked');$.jStorage.set('ShowOnlyRecommended',filter.showOnlyRecommended);refreshList();});var genresFieldset=$('#genresChecks');for(var i=0;i<sortedGenres.length;i++){var genre=sortedGenres[i];genre.value=$.jStorage.get('Genre'+genre.name,genre.value);var id="genre_"+genre.id;genresFieldset.append($('<input/>',{'name':id,'id':id,'type':'checkbox','value':genre.id,'checked':genre.value}));genresFieldset.append($('<label/>',{'for':id,'text':genre.description}));}
genresFieldset.find(':checkbox').on('change',function(){var genre=sortedGenres[$(this).val()];genre.value=$(this).prop('checked');$.jStorage.set('Genre'+genre.name,genre.value);refreshList();});}
function initSorting(){$('#selectSorting').val($.jStorage.get('Sorting','genre'));$('#selectSorting').on('change',function(){$.jStorage.set('Sorting',$('#selectSorting').val());refreshList();});}
function updateSusbcribing(source){if(source.subscribeId){$('#btnSubscribe').text('Get More Free '+source.subscribeId+' Books - Free Book Emails!');}else{$('#btnSubscribe').text('Get More Free '+source.id+' Books - Free Book Emails!');}
$('#subscribePopup iframe').attr('src',source.subscribeUrl);}
function allLoading(){$('#loadingPopup').popup('open');booksLoading(0,booksSources.length,function(){refreshList();$('#loadingPopup').popup('close');if(showBooksOfDayPopup){showIfNeedBooksOfDay();}});}
function booksLoading(curIndex,length,completed){booksSources[curIndex].books=null;getBooks(booksSources[curIndex],function(items){booksSources[curIndex].books=items;curIndex++;if(curIndex<length){booksLoading(curIndex,length,completed);}else
completed();});}
function refreshList(){var centerMessage=$('#centerMessage');centerMessage.html('');window.scrollTo(0,0);var list=$('#list');list.empty();var hint="Please Scroll Down for More Free Books.<br />";$('#topHint').html(hint+'Check Price BEFORE Buying!');if(selectedBookSource){if(selectedBookSource.books&&selectedBookSource.books.length>0){var count=0;var featuredCount=0;var books=selectedBookSource.books;var isSortingByGenres=false;if($('#selectSorting').val()=='genre'){isSortingByGenres=true;books=books.slice().sort(function(a,b){if(a.genre==b.genre){if(a.category==b.category)return 0;else if(a.category<b.category)return-1;else return 1;}else if(a.genre<b.genre)return-1;else return 1;});}
var subscribeRow=$('<li/>',{'data-role':'list-divider','html':'Want more free books? Subscribe.'}).click(function(){$('#subscribePopup').popup('open');return false;}).addClass('subscribe-row');list.append(subscribeRow);if(showFeaturedBooks){var featured=books.filter(function(item){return item.featured;});for(var i=0;i<featured.length&&i<5;i++){var book=featured[i];if(filter.showOnlyRecommended&&book.recommend==0)continue;if(!sortedGenres[book.genre].value)continue;list.append(getBookRow(book).addClass('featured-row'));}}
if(isSortingByGenres){var prevGenre=-1;var curCategory;for(var i=0;i<books.length;i++){var book=books[i];if(filter.showOnlyRecommended&&book.recommend==0)continue;if(!sortedGenres[book.genre].value)continue;if(prevGenre!=book.genre){var genre=sortedGenres[book.genre];curCategory='genre-'+genre.name;list.append($('<li/>',{'data-role':'list-divider','data-link':curCategory}).html(sortedGenres[book.genre].description).addClass('cat-divider ui-btn ui-icon-minus ui-btn-icon-right'));prevGenre=book.genre;}
list.append(getBookRow(book).addClass(curCategory));count++;}
list.find('[data-role="list-divider"]').on('click',function(){if($(this).hasClass('ui-icon-minus')){$('.'+$(this).attr('data-link')).hide();$(this).removeClass('ui-icon-minus').addClass('ui-icon-plus');}else{$('.'+$(this).attr('data-link')).show();$(this).removeClass('ui-icon-plus').addClass('ui-icon-minus');}
return false;});}else{for(var i=0;i<books.length;i++){var book=books[i];if(filter.showOnlyRecommended&&book.recommend==0)continue;if(!sortedGenres[book.genre].value)continue;list.append(getBookRow(book));count++;}}
list.append(subscribeRow.clone(true));var booksCatStr='';switch(selectedBookSource.category){case CATEGORY_FREE:booksCatStr='Free Books';break;case CATEGORY_DEAL:booksCatStr='Book Deals';break;default:booksCatStr='Books';}
if(selectedBookSource.isToday===true){if(selectedBookSource.lastPostTime){$('#topHint').html(hint+count+' '+booksCatStr+' Added Today at '+getTimeString(selectedBookSource.lastPostTime,true)
+' - PLEASE check prices BEFORE Buying! Prices Change!');}else{$('#topHint').html(hint+count+' '+booksCatStr+' Today - Check Prices BEFORE Buying!');}}else{if(selectedBookSource.maxDaysOld>1){$('#topHint').html(hint+booksCatStr+' from Yesterday or Earlier - Check Prices BEFORE Buying!');}else{$('#topHint').html(hint+booksCatStr+' from Yesterday - Check Prices BEFORE Buying!');}}
if(count>0){list.show();centerMessage.hide();}else{list.hide();centerMessage.show();centerMessage.html('There are no new books of the Genres you have selected. If you like, you can select different Genres.');}}else{list.hide();centerMessage.show();if(selectedBookSource.isError===true){centerMessage.html('Can\'t connect to the server. Please check your internet connection, then press "Refresh" button.');}else{centerMessage.html('There are no new books.');}}}else{list.hide();centerMessage.show();centerMessage.html('');}
list.listview('refresh');}
function getBookRow(book){var cell=$('<li/>',{'data-filtertext':book.title+' '+book.author});var link=$('<a/>',{'href':book.url});link.click(function(){chrome.tabs.create({url:$(this).attr('href')});return false;});var leftDiv=$('<div class="book-cell-left-div" />');var bookThumb='';var bookAlt='';if(book.category==CATEGORY_FREE){bookThumb='img/thumb_free.png';bookAlt='FREE';}else if(book.category==CATEGORY_DEAL){bookThumb='img/thumb_deal.png';bookAlt='DEAL';}
leftDiv.append($('<img />',{'src':bookThumb,'alt':bookAlt}));leftDiv.append($('<div class="price-tag" />').html(book.price));var rightDiv=$('<div class="book-cell-right-div" />');rightDiv.append($('<p  />',{'html':book.title}).addClass('book-title'));var recommended=getRecommendedString(book.recommend);if(recommended){rightDiv.append($('<p  />',{'html':recommended}).addClass('book-recommended'));}
rightDiv.append($('<p  />',{'html':'by '+book.author}).addClass('book-info'));rightDiv.append($('<p />',{'html':book.genres}).addClass('book-info'));if(book.reviews>0){var fullStars=Math.floor(book.rating);var hasHalfStar=book.rating-fullStars>=0.5?true:false;var left=-(5-(hasHalfStar?fullStars+1:fullStars))*27;var top=hasHalfStar?-25:0;var ratingBarDiv=$('<div class="rating-bar" />');ratingBarDiv.css('background-position',left+'px '+top
+'px');rightDiv.append(ratingBarDiv);rightDiv.append($('<span />',{'html':book.rating+", "+book.reviews+" reviews"}).addClass('rating-text'));}
link.append(leftDiv);link.append(rightDiv);cell.append(link);return cell;}
function showIfNeedBooksOfDay(){var today=new Date();today.setHours(0,0,0,0);var lastTime=$.jStorage.get('BooksOfDayPopup_LastTime',0);if(today.getTime()>lastTime){var hasTodayBooksOfDay=false;for(var i=0;i<booksSources.length;i++){var bookSourceItem=booksSources[i];if(bookSourceItem.isToday===true){if(bookSourceItem.books){if(bookSourceItem.books.filter(function(item){return item.bookOfDay;}).length>0){hasTodayBooksOfDay=true;break;}}}}
if(hasTodayBooksOfDay===true){openBooksOfTheDayPopup();$.jStorage.set('BooksOfDayPopup_LastTime',today.getTime());}}}
function initBooksOfTheDayPopup(){$('#booksOfTheDayPopup').on('popupbeforeposition',function(){var height=$(window).height();height=height-$('#booksOfDayHeaderPopup').outerHeight()-40;$('#listPopup').css('height',height);});var selectorFieldset=$('#sourceSelectorPopup');if(booksSources.length>1){var groupId='radio-booksofday';for(var i=0;i<booksSources.length;i++){var item=booksSources[i];var radioId=groupId+'-'+item.id;var radio=$('<input/>',{'name':groupId,'id':radioId,'type':'radio','value':item.id});selectorFieldset.append(radio);selectorFieldset.append($('<label/>',{'for':radioId,'text':item.title}));}
selectorFieldset.on('change',function(){fillBooksOfDayList();});}else{selectorFieldset.hide();}}
function openBooksOfTheDayPopup(){var sourceSelectorPopup=$('#sourceSelectorPopup');if(booksSources.length>1){var selected=$('#sourceSelector').find(':checked').val();sourceSelectorPopup.find(':checked').prop('checked',false).checkboxradio('refresh');sourceSelectorPopup.find('#radio-booksofday-'+selected).prop('checked',true).checkboxradio('refresh');}else{sourceSelectorPopup.hide();}
fillBooksOfDayList();$('#booksOfTheDayPopup').popup('open');}
function fillBooksOfDayList(){var selected=booksSources[0];if(booksSources.length>1){var sourceId=$('#sourceSelectorPopup').find(':checked').val();for(var i=0;i<booksSources.length;i++){var item=booksSources[i];if(item.id==sourceId){selected=item;break;}}}
var popupTitle=$('#booksOfDayPopupTitle');if(selected.isToday){popupTitle.text('Featured Books for Today');}else{if(selected.maxDaysOld>1){popupTitle.text('Featured Books from Yesterday or Earlier');}else{popupTitle.text('Featured Books from Yesterday');}}
var listPopup=$('#listPopup');listPopup.empty();if(selected&&selected.books){var booksOfDay=selected.books.filter(function(item){return item.bookOfDay;});for(var i=0;i<booksOfDay.length;i++){var book=booksOfDay[i];listPopup.append(getBookRow(book));}}
listPopup.listview('refresh');}
function getTimeString(date,is12){if(is12===true){var hours=date.getHours();var ampm;var hours12;if(hours===0){hours12=12;ampm=' AM';}else if(hours>12){hours12=hours-12;ampm=' PM';}else{hours12=hours;ampm=' AM';}
var minutes=date.getMinutes();return hours12+':'+(minutes<10?"0"+minutes:minutes)+ampm;}else{var minutes=date.getMinutes();return date.getHours()+':'+(minutes<10?"0"+minutes:minutes);}}