/* Copyright (C) Sergey Barbushin, 2013. All Rights Reserved.
 * This file can be used only within Google Chrome extension "PHP Console" installed from https://chrome.google.com/webstore/detail/php-console/nfhmhhlpfleoednkpnnnkolmclajemef
 * Unauthorized copying and using of this file, via any medium is strictly prohibited
 * Proprietary and confidential
 * Written by Sergey Barbushin <barbushin@gmail.com>, June 2013
 */
window.app=new function(){function f(a,b,k){v.getServer(b,function(w){var B={"php-console-client":v.protocol};(w=m.j(w))&&(w=w.v())&&(B.auth=w);p[0]!=e[2][0]&&e[0][3]!=p[2]&&(a=1);var q=d.g[b]||!1,c=(q?"https":"http")+"://"+b,g=btoa(JSON.stringify(B));chrome.cookies.get({url:c,name:"php-console-client"},function(b){!b||b.value!=g||q&&b.secure!=q?chrome.cookies.set({url:c,name:"php-console-client",secure:q,value:g},function(){k?k(!0):chrome.tabs.reload(a,{bypassCache:!0})}):k()})})}function h(a,b,
k){var w=z[b];v.getServer(d.a(w),function(B){r.m(w,{__PHP_Console:{eval:{data:a,signature:m.j(B).w(a)},getBackData:{tabId:b}}},k,k)})}function x(a,b,k,w){p[2]!="history"[0]&&"history"[0]!=p[15]&&(b=a);k!=v.protocol&&d.o({tabId:a,protocol:k});z[a]=b;b=d.a(b);k=d.u(b);var B=!1;y[k]||(y[k]=!0,r.addListener(k),B=!0);f(a,b,function(k){id=q++;g.f[a]=id;w(id,B||k)})}var g=this,z={},y={},t=!1,v=null,m=null,p=chrome.runtime,c=p.getManifest(),d=null,r=null,n=null,b=/^https:\/\//i,a=p.getURL("manifest.json"),
e=["eval","console","notify"],q=0;this.f={};this.getOptions=function(){return v};this.l=function(a,b){b._id=g.f[a];chrome.tabs.sendMessage(a,b)};this.getActiveTab=function(a){chrome.tabs.query({currentWindow:!0,active:!0},function(b){var k=b[0].id;a(k,d.a(d.i[k]?d.i[k]:b[0].url))})};chrome.extension.onMessage.addListener(function(a,e,k){if(a._registerTab){var w=a.url;if(0==w.indexOf("chrome-extension://"))return!0;x(e.tab.id,w,a.protocol,function(a,e){k({id:a,url:d.g[d.a(w)]&&!b.exec(w)?w.replace("http://",
"https://"):e?w:""})});return!0}if(a._setPassword)g.getActiveTab(function(k,b){m.C(b,a.password);f(k,b,null);chrome.tabs.reload(k)});else if(a._logout)g.getActiveTab(function(a,k){m.s(k);f(a,k,null);chrome.tabs.reload(a)});else if(a._evalCode)return v.evalClearConsole&&g.l(a.tabId,{_clearConsole:!0}),h(a.code,a.tabId,k),!0});v=new D(function(b){p=p.id;m=new E(b);n=new F(b);d=new G(b,m,n,g);r=new H(d);a=a.substr(19);var e=parseFloat(/^\d+\.\d+/.exec(c.version)[0]);chrome.extension.inIncognitoContext||
b.version==e||(b.version?2.9>=b.version?(t=!0,chrome.tabs.onRemoved.addListener(function(){t&&(t=!1,b.version=e,n.showNotification({type:"update",subject:"PHP Console MEGA Update",permanent:!0,data:"\u271a Dump any type variable\n\u271a Execute PHP code remotely\n\u271a Protect access by password\n\u271a Group console logs by request\n\u271a New communication protocol\n\u271a Jump to error file:line in your text editor",openUrlOnClose:"https://github.com/barbushin/php-console/wiki/PHP-Console-v3-Release-(November-2013)",
buttons:[{title:"IMPORTANT: PHP Console server library must be updated",url:"https://github.com/barbushin/php-console/wiki/PHP-Console-v3-Release-(November-2013)"},{title:"Changelog & server library update instructions",url:"https://github.com/barbushin/php-console/wiki/PHP-Console-v3-Release-(November-2013)",icon:"img/right.png"}]}))})):b.version=e:(n.showNotification({type:"update",subject:c.name+" installed",permanent:!0,data:"To use PHP Console on your server you need to install PHP Console server library.",
buttons:[{title:"PHP Console server library Installation & Usage Guide",url:"https://github.com/barbushin/php-console#php-console-server-library",icon:"img/right.png"}]}),b.version=e),a[1]!="force"[0]&&"force"[0]!=a[4]&&(b={}))})};document.addEventListener("DOMContentLoaded",window.app,!1);
function E(f){function h(x,g){f.updateServer(x,{auth:g},null,!0)}this.B=function(f){var g=f.auth;g&&h(f.domain,{publicKey:g.publicKey,isSuccess:g.isSuccess})};this.j=function(f){var g=f.auth;if(g.publicKey&&g.hash)return new I(f.domain,g.publicKey,g.hash)};this.C=function(f,g){h(f,{hash:window.CryptoJS.SHA256(g+"NeverChangeIt:)").toString()})};this.s=function(f){h(f,{hash:null})}}
function I(f,h,x){this.domain=f;this.b=h;this.hash=x;this.getAuthToken=function(){if(this.hash&&this.b)return window.CryptoJS.SHA256(this.hash+this.b).toString()};this.w=function(f){if(this.hash&&this.b)return window.CryptoJS.SHA256(this.hash+this.b+f).toString()};this.v=function(){var f=this.getAuthToken();if(f&&this.b)return{publicKey:this.b,token:f}}}
function H(f){function h(b,a,e){for(var d in b)if(b[d].name===a||b[d].name===e)return b[d].value;return null}function x(b,a,e,d,c){var l=b||!1;l||(b={tabId:0>=d?null:d,redirectUrl:y(e,c),url:e,domain:f.a(e)});if(a){m[b.domain]=b.url;a=JSON.parse(a);if(a.isPostponed){n.push(b);g(a.id,b);return}for(var k in a)b[k]=a[k];a.getBackData&&a.getBackData.tabId&&(b.tabId=+a.getBackData.tabId);b.sourcesBasePath&&(b.sourcesBasePath=f.c(b.sourcesBasePath));if(b.messages&&b.messages.length)for(k in b.messages)a=
b.messages[k],a.redirectUrl=b.redirectUrl,a.url=b.url,a.tabId=b.tabId,a.basePath=b.sourcesBasePath,a.isLocal=b.isLocal,a["class"]?a.tags=[a["class"]]:"debug"!=a.type||a.tags?a.tags||(a.tags=[a.type]):a.tags=["debug"],a.file&&p.exec(a.file)&&(a.file="terminal")}b.tabId&&chrome.tabs.get(b.tabId,function(a){b.tabUrl=a.url;l||n.push(b);!b.redirectUrl&&n.length&&(a=n.slice(0),n=[],f.A(a))})}function g(b,a){v.m(a.url,{__PHP_Console:{getPostponedResponse:b}},function(b){x(a,b,null,null,null)},null)}function z(b){var a=
f.a(b.url),e=h(b.responseHeaders,"PHP-Console","php-console");e||(e=h(b.responseHeaders,"PHP-Console-Postpone","php-console-postpone"));(m[a]==b.url||e)&&x(null,e,b.url,b.tabId,b.redirectUrl)}function y(b,a){a&&!d.exec(a)&&(a=(r.exec(b)||[b])[0]+a);return a}function t(b,a){var e=[],d;for(d in b){var c=a?a+"["+d+"]":d,f=b[d];e.push("object"==typeof f?t(f,c):encodeURIComponent(c)+"="+encodeURIComponent(f))}return e.join("&")}var v=this,m={},p=/EvalProvider.php.*?eval/i,c=/^[\d]+\.[\d]+\.[\d]+\.[\d]+$/,
d=/^http/i,r=/^(.+[/\\])/,n=[];this.m=function(b,a,d,c){try{var f=new XMLHttpRequest;f.open("POST",b,!0);f.setRequestHeader("Content-type","application/x-www-form-urlencoded");f.onreadystatechange=function(){4==f.readyState&&200==f.status&&d&&d(f.responseText)};f.send(t(a))}catch(g){c&&c()}};this.addListener=function(b){c.exec(b)||(b="*."+b);b={urls:["*://"+b+"/*"],types:["main_frame","sub_frame","xmlhttprequest","other"]};chrome.webRequest.onCompleted.addListener(z,b,["responseHeaders"]);chrome.webRequest.onBeforeRedirect.addListener(z,
b,["responseHeaders"])}}
function G(f,h,x,g){function z(a,b){var d=!1,e=setInterval(function(){chrome.tabs.get(a,function(f){"complete"==f.status&&!d&&g.f[a]&&(d=!0,clearInterval(e),b())})},100)}function y(a,b){var d=b.ignoreErrors,e=b.ignoreDebug,c={},q=[],g;for(g in a){var n=!1,l=a[g];if("debug"==l.type){if("object"==typeof l.tags)for(var m in l.tags){var u=l.tags[m];if("undefined"!=typeof e[u]){if(e[u]){n=!0;break}}else c[u]||(c[u]=!0)}}else"error"==l.type&&d[l["class"]]&&(n=!0);n||q.push(l)}d=Object.keys(c);if(d.length){d.sort();
c={};n=[];l=[];for(u in e)e[u]?n.push(u):l.push(u);for(g=0;20>g;g++)if(u=n.shift())c[u]=!0;else if(u=d.shift()||l.shift())c[u]=!1;else break;f.updateServer(b.domain,{ignoreDebug:c})}return q}function t(a){if("eval_result"==a.type){var b=[];a.output&&b.push(["%c output ","color: white; background: black",a.output]);b.push(["%c return ","color: white; background: black",a["return"]]);a.time&&f.evalShowTime&&b.push(["%c time ","color: white; background: black",a.time])}else if(b=["%c "+a.tags.join(".")+
" ","color: white; background: "+("debug"==a.type?"blue":"red"),a.data],a.path||a.trace)b.push("-"),a.path&&b.push(a.path+(a.line?":"+a.line:"")),a.trace&&b.push("\n"+a.trace);a.args=b}function v(a){if(a.trace){var b=[],d;for(d in a.trace){var e="#"+(+d+1)+" ",c=a.trace[d];c.file?(e+=m(a.basePath,c.file),c.line&&(e+=":"+c.line)):e+="[internal call]";c.call&&(e+=" - "+c.call);b.unshift(e)}a.trace=b.join("\n")}a.file&&(a.path=m(a.basePath,a.file))}function m(a,b){b=l.c(b);return a&&b.substr(0,a.length)==
a?b.substr(a.length):b}this.g={};this.i={};var p={},c={},d={},r=/\\/g,n=/:\/\/([^:/]+)/,b=/:\/\/(([0-9a-fA-F]{1,4}:){7,7}[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,7}:|([0-9a-fA-F]{1,4}:){1,6}:[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,5}(:[0-9a-fA-F]{1,4}){1,2}|([0-9a-fA-F]{1,4}:){1,4}(:[0-9a-fA-F]{1,4}){1,3}|([0-9a-fA-F]{1,4}:){1,3}(:[0-9a-fA-F]{1,4}){1,4}|([0-9a-fA-F]{1,4}:){1,2}(:[0-9a-fA-F]{1,4}){1,5}|[0-9a-fA-F]{1,4}:((:[0-9a-fA-F]{1,4}){1,6})|:((:[0-9a-fA-F]{1,4}){1,7}|:)|fe80:(:[0-9a-fA-F]{0,4}){0,4}%[0-9a-zA-Z]{1,}|::(ffff(:0{1,4}){0,1}:){0,1}((25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9]).){3,3}(25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])|([0-9a-fA-F]{1,4}:){1,4}:((25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9]).){3,3}(25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9]))/,
a=/^[\d]+\.[\d]+\.[\d]+\.[\d]+$/,e=/^([0-9a-fA-F]{1,4}:){7,7}[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,7}:|([0-9a-fA-F]{1,4}:){1,6}:[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,5}(:[0-9a-fA-F]{1,4}){1,2}|([0-9a-fA-F]{1,4}:){1,4}(:[0-9a-fA-F]{1,4}){1,3}|([0-9a-fA-F]{1,4}:){1,3}(:[0-9a-fA-F]{1,4}){1,4}|([0-9a-fA-F]{1,4}:){1,2}(:[0-9a-fA-F]{1,4}){1,5}|[0-9a-fA-F]{1,4}:((:[0-9a-fA-F]{1,4}){1,6})|:((:[0-9a-fA-F]{1,4}){1,7}|:)|fe80:(:[0-9a-fA-F]{0,4}){0,4}%[0-9a-zA-Z]{1,}|::(ffff(:0{1,4}){0,1}:){0,1}((25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9]).){3,3}(25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])|([0-9a-fA-F]{1,4}:){1,4}:((25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9]).){3,3}(25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])$/,
q=/(^|\.)([^.]+\.[\w]+)$/,A=/^\w+:\/\/.*?(\/.*\.(js|htm|html))($|\?)/,l=this;this.c=function(a){return a.replace(r,"/")};this.o=function(a){var b=a.tabId;if(a.protocol){var d="logo_16.png",e="options/layout.html",c="PHP Console is active on server.";a.protocol!=f.protocol?(d="logo_16_fail.png",e="wrong_protocol.html",c="Wrong version of PHP Console server. Click on this icon to get update instructions."):a.auth&&(a.isEvalEnabled?(d="terminal_16.png",c="PHP Console eval is enabled on server. Click on this icon to access eval & options form.",
e="terminal/popup.html"):a.auth.isSuccess?(c="PHP Console is active on server protected by password. Click on this icon to see options.",e="logout/popup.html"):(d="key_16.png",c="PHP Console authorization required. Click on this icon to see authorization form.",e="auth/popup.html"));z(b,function(){chrome.pageAction.setTitle({tabId:b,title:c});chrome.pageAction.setIcon({tabId:b,path:"img/"+d});chrome.pageAction.setPopup({tabId:b,popup:e});chrome.pageAction.show(b)})}else chrome.pageAction.hide(b)};
l.A=function(a){var b=[],e=a[a.length-1];"undefined"!=typeof e.isSslOnlyMode&&(l.g[e.domain]=e.isSslOnlyMode);l.i[e.tabId]=e.url;l.o(e);e.protocol==f.protocol&&(h.B(e),e.docRoot&&(p[e.domain]=l.c(e.docRoot)),e.sourcesBasePath&&(c[e.domain]=l.c(e.sourcesBasePath)),e.isLocal&&(d[e.domain]=e.isLocal),f.getServer(e.domain,function(d){for(var c in a){var q=a[c];if(q.messages){var l=y(q.messages,d),n=[],m=[],p=!1,u=!1,A;for(A in l){var h=l[A];v(h);var r="eval_result"==h.type,r=r|(f.consoleErrors&&"error"==
h.type);if(r|=f.consoleDebug&&"debug"==h.type)"error"==h.type?p=!0:"eval_result"==h.type&&(u=!0),t(h),n.push(h);r=!1;r|=f.notifyErrors&&"error"==h.type;r|=f.notifyDebug&&"debug"==h.type;(r|="protocol_error"==h.type)&&m.push(h)}if(n.length){l=[];if(u)for(A in h=["debug","eval_result","error"],h)for(var C in n)n[C].type==h[A]&&l.push(n[C]);b.push({url:q.url,redirectUrl:q.redirectUrl,groupName:q.redirectUrl?q.url+" --\x3e "+q.redirectUrl:q.url,collapse:!u&&!p&&(q.redirectUrl||f.consoleCollapseNoErrors),
messages:l.length?l:n})}if(m.length&&!u){l=[];for(A in m)"error"==m[A].type&&(l.push(m[A]),delete m[A]);for(A in m)"error"!=m[A].type&&l.push(m[A]);x.h(l)}}}b.length&&z(e.tabId,function(){g.l(e.tabId,{_handleConsolePacks:!0,packs:b})})}))};chrome.extension.onMessage.addListener(function(a,b){if(a._handleJavascriptError){var e=a.text,q=a.url,g=a.line,n=b.tab.id;if(f.notifyJavaScriptErrors){if(e){var e=e.replace(/^Uncaught /g,""),h=/(.+): *(.+)/.exec(e);if(h)var r="JavaScript "+h[1],e=h[2];else r="JavaScript error"}else e=
"... see details in JavaScript Console",r="JavaScript unknown error";var v=!1,t=q;if(t){var u=l.a(q);(h=A.exec(q))&&p[u]&&(q=p[u]+h[1],v=d[u],c[u]&&(t=m(c[u],q)))}x.showNotification({tabId:n,type:"js_error",subject:r,data:e,file:q,line:g,path:t,isLocal:v},!0)}}});this.a=function(a){var e=b.exec(a);return e?e[1]:n.exec(a)[1]};this.u=function(b){var d=a.exec(b);return d||(d=e.exec(b))?d[0]:(d=q.exec(b))?d[2]:b}}
function F(f){function h(a,b){b=b||"";if("object"==typeof a&&null!==a){var d="",c;for(c in a){var f="";f="object"==typeof a[c]&&null!==a[c]?(f=h(a[c],b+"  "))?"\n"+f:-1!=c.indexOf(":")?"{}":"[]":a[c]+"\n";d=d+b+c+": "+f}return d}return b+a+"\n"}function x(a,b){if("debug"==b.type)return a.message;var d=a.title+": "+a.message;b.path&&(d+="\n"+b.path+(b.line?":"+b.line:""));b.trace&&(d+="\n"+b.trace);return d}function g(a,b){r++;var c="n"+r,g={type:"basic",buttons:[],priority:"error"==a.type?2:0,iconUrl:n[a.type]?
"img/"+n[a.type]:null,title:a.subject?a.subject:"debug"==a.type?a.tags.join("."):a["class"],message:h(a.data).trim()},l={isPermanent:a.permanent||!1,openUrlOnClose:a.openUrlOnClose||null,buttons:[]};if(a.path){var k=f.notifyJumpToFile&&a.isLocal&&"eval_result"!=a.type&&a.line,p=a.path+(a.line?" "+a.line:"");g.buttons.push({title:50>=p.length?p:"..."+p.substr(-47),iconUrl:k?"img/jump.png":"img/file.png"});l.buttons.push({type:"source",open:k,file:a.file,line:a.line,tabId:a.tabId})}!f.notifyCopyToClipboard||
"error"!=a.type&&"js_error"!=a.type&&"debug"!=a.type||(g.buttons.push({title:"Copy to clipboard",iconUrl:"img/clipboard.png"}),l.buttons.push({type:"copy",text:x(g,a)}));if(a.buttons)for(var t in a.buttons)k=a.buttons[t],g.buttons.push({title:k.title,iconUrl:k.icon||null}),l.buttons.push({type:"link",url:k.url});d[c]=l;l.isPermanent&&setTimeout(function(){d[c]&&(m(c),y(c,!0))},3E4);chrome.notifications.create(c,g,b)}function z(){!c&&f.notifyLifeTime&&(c=setTimeout(function(){y();c=null;Object.keys(d).length&&
z()},1E3*f.notifyLifeTime))}function y(a,b){if(!a)for(var c in d){a=c;break}!a||d[a].permanent&&!b||(delete d[a],chrome.notifications.clear(a,function(){}))}function t(a){var b=a.shift();b&&g(b,function(){t(a)})}function v(){var a=Object.keys(d);if(500<(new Date).getTime()-p)for(var b in a)y(a[b]);p=(new Date).getTime();c&&(clearTimeout(c),c=null)}function m(a){d[a].openUrlOnClose&&chrome.tabs.create({url:d[a].openUrlOnClose,active:!0})}var p=null,c=null,d={},r=1,n={update:"ok.png",js_error:"js_error.png",
error:"error.png",ahtung:"ahtung.png",debug:"info.png"},b=this;chrome.extension.onRequest.addListener(function(a){a.showNotifications?b.h(a.showNotifications):a.showNotification&&b.showNotification(a.message)});b.h=function(a,b){b||v();t(a);z()};b.showNotification=function(a,d){b.h([a],d)};chrome.notifications.onClosed.addListener(function(a,b){d[a]&&m(a);b&&v()});chrome.notifications.onClicked.addListener(function(a){d[a]&&(m(a),delete d[a])});chrome.notifications.onButtonClicked.addListener(function(a,
b){if(d[a]){var c=d[a].buttons[b];if("link"==c.type)chrome.tabs.create({url:c.url,active:!0});else if("source"==c.type)/:\/\//.exec(c.file)?chrome.tabs.create({url:"view-source:"+c.file,active:!0}):c.open&&document.getElementById("debug").setAttribute("src","editor://open/?file="+encodeURIComponent(c.file)+"&line="+encodeURIComponent(c.line));else if("copy"==c.type){var f=document.getElementById("textarea");f.value=c.text;f.select();document.execCommand("Copy",!1,null)}delete d[a]}})}
function D(f){function h(c,d){localStorage[c]="object"==typeof d?JSON.stringify(d):d}function x(c){return function(){return t[c]}}function g(c){return function(d){t[c]=d;h(c,d)}}function z(){return m.transaction("servers","readwrite").objectStore("servers")}var y=this;this.protocol=5;var t={version:null,consoleDebug:!0,consoleErrors:!0,consoleCollapseNoErrors:!1,notifyDebug:!0,notifyErrors:!0,notifyJavaScriptErrors:!0,notifyLifeTime:"",notifyCopyToClipboard:!1,notifyJumpToFile:!1,evalClearConsole:!0,
evalShowTime:!0},v={auth:{},ignoreErrors:{},ignoreDebug:{}},m=null;this.getServer=function(c,d,f){(f||z()).index("domain").get(c).onsuccess=function(f){f=f.target.result||{};f.domain=c;for(var b in v)"undefined"==typeof f[b]&&(f[b]=v[b]);d(f)}};this.updateServer=function(c,d,f,g){var b=z();y.getServer(c,function(a){for(var c in d)if(g&&a[c]&&"object"==typeof d[c])for(var h in d[c])a[c][h]=d[c][h];else a[c]=d[c];a=b.put(a);f&&(a.onsuccess=f)},b)};var p=indexedDB.open("php-console");p.onupgradeneeded=
function(){m=p.result;m.createObjectStore("servers",{keyPath:"domain",autoIncrement:!1}).createIndex("domain","domain",{unique:!0})};p.onsuccess=function(){m=p.result;if("undefined"==typeof localStorage.evalShowTime)for(var c in localStorage)"version"!=c&&delete localStorage[c];for(var d in t)c=localStorage.getItem(d),c="true"==c?!0:"false"==c?!1:null!==c&&"{"==c.charAt(0)&&"}"==c.charAt(c.length-1)?JSON.parse(c):c,null===c?(c=t[d],h(d,c)):t[d]=c,y.__defineGetter__(d,x(d)),y.__defineSetter__(d,g(d));
f(y)}};