/*

// ==UserScript==
// @name LinguaLeoHelpers
// @all-frames true
// @include http://*
// @include https://*
// @include file://*
// @include file:///*
// @exclude http*://lingualeo.com/*
// @exclude http*://lingualeo.ru/*
// @exclude http*://*facebook.com/plugins/*
// @exclude http*://*twitter.com/widgets/*
// @exclude http*://plusone.google.com/*
// ==/UserScript==
*/
var Event=function(){function c(a){a=a||window.event;if(a.isFixed)return a;a.isFixed=!0;a.preventDefault=a.preventDefault||function(){this.returnValue=!1};a.stopPropagation=a.stopPropagaton||function(){this.cancelBubble=!0};a.target||(a.target=a.srcElement);!a.relatedTarget&&a.fromElement&&(a.relatedTarget=a.fromElement==a.target?a.toElement:a.fromElement);if(null==a.pageX&&null!=a.clientX){var b=document.documentElement,c=document.body;a.pageX=a.clientX+(b&&b.scrollLeft||c&&c.scrollLeft||0)-(b.clientLeft||
0);a.pageY=a.clientY+(b&&b.scrollTop||c&&c.scrollTop||0)-(b.clientTop||0)}!a.which&&a.button&&(a.which=a.button&1?1:a.button&2?3:a.button&4?2:0);return a}function b(a){a=c(a);var b=this.custom_universal_events[a.type],e;for(e in b){var g=b[e].handler;a.customData=b[e].data;!1===g.call(this,a)&&(a.preventDefault(),a.stopPropagation())}}var a=0,e={add:function(c,f,h,g){c.setInterval&&c!=window&&!c.frameElement&&(c=window);h.guid||(h.guid=++a);c.custom_universal_events||(c.custom_universal_events={},
c.handle=function(a){if("undefined"!==typeof e)return b.call(c,a)});c.custom_universal_events[f]||(c.custom_universal_events[f]={},c.addEventListener?c.addEventListener(f,c.handle,!1):c.attachEvent&&c.attachEvent("on"+f,c.handle));c.custom_universal_events[f][h.guid]={handler:h,data:g}},remove:function(a,b,c){var e=a.custom_universal_events&&a.custom_universal_events[b];if(e){delete e[c.guid];for(var k in e)return;a.removeEventListener?a.removeEventListener(b,a.handle,!1):a.detachEvent&&a.detachEvent("on"+
b,a.handle);delete a.custom_universal_events[b];for(k in a.custom_universal_events)return;try{delete a.handle,delete a.custom_universal_events}catch(l){a.removeAttribute("handle"),a.removeAttribute("custom_universal_events")}}}};return e}(),browserDetector=function(){var c=null;return{userAgent:window.navigator.userAgent.toLowerCase(),getVersion:function(){return(this.userAgent.match(/.+(?:rv|it|ra|ie|me)[\/: ]([\d.]+)/)||[])[1]},isChrome:function(){return/chrome/.test(this.userAgent)},isSafari:function(){return/webkit/.test(this.userAgent)&&
!/chrome/.test(this.userAgent)},isOpera:function(){return/opera/.test(this.userAgent)},isIE:function(){return/msie/.test(this.userAgent)&&!/opera/.test(this.userAgent)},isFirefox:function(){return/firefox/.test(this.userAgent)&&!/(compatible|webkit)/.test(this.userAgent)},canPlayMp3:function(){if(null!==c)return c;try{var b=document.createElement("audio").canPlayType("audio/mpeg");return c="maybe"===b||"probably"===b}catch(a){return c=!1}}}}(),i18n=function(){var c=null,b={getLocaleMessage:function(a){return null!==
c&&"undefined"!==typeof c[a]?c[a]:a},updateLocaleMessages:function(a,b){"function"!==typeof b&&(b=function(){});!0===a||null===c?"undefined"!==typeof kango&&"undefined"!==typeof kango.invokeAsync&&kango.invokeAsync("kango.i18n.getMessages",function(a){c=a;b()}):b()},localizeDom:function(a){a=a.querySelectorAll?a.querySelectorAll("[data-i18n]"):a.getElementsByTagName("*");for(var c=0,d;d=a[c];c++)b.localizeElement(d,d.getAttribute("data-i18n"),d.getAttribute("data-i18n-attr"))},localizeElement:function(a,
c,d){if(c)if(c=b.getLocaleMessage(c),d)a.setAttribute(d,c);else switch(a.tagName){case "INPUT":a.value=c;break;default:a.innerHTML=c}}};b.updateLocaleMessages(!1,null);return b}(),domHelper=function(){var c={},b=null;c.Fragment=function(){this.initialize(arguments)};c.Fragment.prototype={initialize:function(){this._frag=document.createDocumentFragment();this._nodes=[]},appendSource:function(a){var b=document.createElement("div");b.innerHTML=a;for(a=0;a<b.childNodes.length;a++){var c=b.childNodes[a].cloneNode(!0);
this._nodes.push(c);this._frag.appendChild(c)}},appendTo:function(a){a&&a.appendChild(this._frag)},insertAsFirst:function(a){a&&a.insertBefore(this._frag,a.firstChild)},insertBefore:function(a,b){a&&b&&a.insertBefore(this._frag,b)},insertAfter:function(a){a&&a.parentNode.insertBefore(this._frag,a.nextSibling)},reclaim:function(){for(var a=0;a<this._nodes.length;a++)this._frag.appendChild(this._nodes[a])}};c.getBody=function(){return b||(b=document.getElementsByTagName("body")[0]||null)};c.appendHtmlToElement=
function(a,b){var d=new c.Fragment;d.appendSource(b);d.appendTo(a)};c.insertHtmlAsFirstElement=function(a,b){var d=new c.Fragment;d.appendSource(b);d.insertAsFirst(a)};c.insertHtmlAsNextElement=function(a,b){var d=new c.Fragment;d.appendSource(b);d.insertAfter(a)};c.removeAllChilds=function(a){"string"==typeof a&&(a=document.getElementById(a));if("undefined"==typeof a||null==a)return!1;for(;a.hasChildNodes();)a.removeChild(a.firstChild);return!0};c.removeChild=function(a){a&&a.parentNode.removeChild(a)};
c.getStyleValues=function(a,b){for(var c={},f=a.style,h=0,g;g=b[h];h++)c[g]=f[g];return c};c.setStyleValues=function(a,b){var c=a.style,f;for(f in b)b.hasOwnProperty(f)&&(c[f]=b[f])};c.isElementVisible=function(a){return 0<a.offsetWidth||0<a.offsetHeight};return c}(),cssHelper=function(){var c={hasClass:function(b,a){return b?b.className.match(new RegExp("(\\s|^)"+a+"(\\s|$)")):!1},clearClass:function(b){b.className=""},addClass:function(b,a){null==b||c.hasClass(b,a)||(b.className+=" "+a)},removeClass:function(b,
a){b&&c.hasClass(b,a)&&(b.className=b.className.replace(new RegExp("(\\s|^)"+a+"(\\s|$)")," "))},addCss:function(b,a){a&&(a="lleo_css_"+a);if(!a||!document.getElementById(a)){var c=document.createElement("style");c.type="text/css";a&&(c.id=a);c.styleSheet?c.styleSheet.cssText=b:c.appendChild(document.createTextNode(b));var d=null,f=document.getElementsByTagName("head");0<f.length?d=f[0]:(f=document.getElementsByTagName("body"),0<f.length&&(d=f[0]));null!=d&&d.appendChild(c)}}};return c}(),sizeHelper=
function(){var c={clientSize:function(){var b=document,a=domHelper.getBody();return{width:(null==b.compatMode||"undefined"==typeof b.compatMode||"CSS1Compat"==b.compatMode)&&b.documentElement&&b.documentElement.clientWidth||a&&a.clientWidth,height:(null==b.compatMode||"undefined"==typeof b.compatMode||"CSS1Compat"==b.compatMode)&&b.documentElement&&b.documentElement.clientHeight||a&&a.clientHeight}},scrollOffset:function(){var b=document,a=domHelper.getBody();return{left:b.documentElement&&b.documentElement.scrollLeft||
a&&a.scrollLeft,top:b.documentElement&&b.documentElement.scrollTop||a&&a.scrollTop}},scrollSize:function(){var b=document,a=domHelper.getBody();return{width:b.documentElement&&b.documentElement.scrollWidth||a&&a.scrollWidth,height:b.documentElement&&b.documentElement.scrollHeight||a&&a.scrollHeight}},getOffsetSum:function(b){for(var a=0,c=0;b;)a+=parseInt(b.offsetTop),c+=parseInt(b.offsetLeft),b=b.offsetParent;return{top:a,left:c}},getOffsetRect:function(b){b=b.getBoundingClientRect();var a=domHelper.getBody(),
c=document.documentElement,d=b.left+(window.pageXOffset||c.scrollLeft||a.scrollLeft)-(c.clientLeft||a.clientLeft||0);return{top:Math.round(b.top+(window.pageYOffset||c.scrollTop||a.scrollTop)-(c.clientTop||a.clientTop||0)),left:Math.round(d)}},getOffset:function(b){return b.getBoundingClientRect&&"fixed"!==window.getComputedStyle(b,null).position?c.getOffsetRect(b):c.getOffsetSum(b)},pointInRect:function(b,a){return b.y>a.bottom||b.y<a.top||b.x>a.right||b.x<a.left?!1:!0}};return c}(),arrayHelper=
{convertFromObject:function(c){var b=[],a;for(a in c)c.hasOwnProperty(a)&&b.push(c[a]);return b},map:function(c,b){for(var a=c.length,e=Array(a),d=0;d<a;d++)e[d]=b(c[d]);return e},indexOf:function(c,b,a){a=a||0;for(var e=c.length;a<e;a+=1)if(c[a]===b)return a;return-1}},selectionHelper=function(){var c={getSelection:function(){if("function"===typeof window.getSelection){var b=window.getSelection();return"function"===typeof b.getRangeAt?b:document.getSelection()}return document.selection},saveSelection:function(){var b=
{},a=null,e=document.activeElement,d=e.tagName;"undefined"!==typeof d&&(d=d.toLowerCase(),"textarea"===d||"input"===d&&"text"===e.type.toLowerCase())&&(a=e);a?(b.type="input",b.element=a,b.start=a.selectionStart,b.end=a.selectionEnd):(a=c.getSelection(),b.type="simple","function"===typeof a.getRangeAt&&0<a.rangeCount&&(b.range=a.getRangeAt(0).cloneRange()));return b},restoreSelection:function(b){var a=!1;if("undefined"!==typeof b.type)if("input"===b.type)b.element.focus(),b.element.setSelectionRange(b.start,
b.end),a=!0;else if("simple"===b.type){var e=c.getSelection();if("function"===typeof e.removeAllRanges){try{e.removeAllRanges()}catch(d){}"undefined"!==typeof b.range&&(e.addRange(b.range),a=!0)}}return a},selectNode:function(b){if(document.createRange){var a=document.createRange();a.selectNode(b);b=window.getSelection();b.removeAllRanges();b.addRange(a)}}};return c}(),htmlHelper={escapeReplacements:{"&":"&amp;",'"':"&quot","<":"&lt;",">":"&gt;"},escapeHTML:function(c){return null===c||0===c?c:(c+
"").replace(/[&"<>]/g,function(b){return htmlHelper.escapeReplacements[b]})}},dictionariesHelper={linkTemplate:'<a href="{href}" target="_blank" class="{className}" title="{title}"></a>',items:{multitran:{className:"lleo_multitran",title:"Multitran",isAvailable:function(c){return"ru"==c},getLink:function(c,b){return"http://multitran.ru/c/m.exe?CL=1&l1=1&s="+encodeURIComponent(c)}},google:{className:"lleo_google",title:"Google",isAvailable:function(c){return!0},getLink:function(c,b){"pt_br"==b&&(b=
"pt");return"http://translate.google.com/#en|"+("en"==b?"ru":b)+"|"+encodeURIComponent(c)}},lingvo:{className:"lleo_lingvo",title:"Abbyy Lingvo",isAvailable:function(c){return"ru"==c},getLink:function(c,b){return"http://lingvopro.abbyyonline.com/en/Search/en-ru/"+encodeURIComponent(c)}},dictionary:{className:"lleo_dict",title:"Dictionary.com",isAvailable:function(c){return!0},getLink:function(c,b){return"http://dictionary.reference.com/browse/"+encodeURIComponent(c)}},theFreeDictionary:{className:"",
title:"TheFreeDictionary.com",isAvailable:function(c){return!0},getLink:function(c,b){return"http://www.thefreedictionary.com/"+encodeURIComponent(c)}},linguee:{className:"lleo_linguee",title:"Linguee",isAvailable:function(c){return"pt"==c},getLink:function(c,b){return"http://www.linguee.com.br/ingles-portugues/search?source=auto&query="+encodeURIComponent(c)}},michaelis:{className:"lleo_michaelis",title:"Michaelis",isAvailable:function(c){return"pt"==c},getLink:function(c,b){return"http://michaelis.uol.com.br/moderno/ingles/index.php?lingua=ingles-portugues&palavra="+
encodeURIComponent(c)}}},getHtml:function(c){var b="",a;for(a in dictionariesHelper.items){var e=dictionariesHelper.items[a];e.isAvailable(c.locale)&&(b+=stringHelper.formatStr(dictionariesHelper.linkTemplate,{title:e.title,className:e.className,href:e.getLink(c.text,c.locale)}))}return b}},lingualeoHelper={canTranslate:function(c){return/[a-z0-9'-]/i.test(c)},getTemplate:function(c,b){kango.invokeAsync("window.lingualeo.getTemplate",c,!0,function(a){b(a.html)})},getTemplates:function(c,b,a){kango.invokeAsync("window.lingualeo.getTemplates",
c,b,function(b){a(b)})},getWordArticleUrl:function(c){return stringHelper.formatStr(LinguaLeoConfig().domain+LinguaLeoConfig().path.dictionaryFromInternet,{originalText:encodeURIComponent(c)})},isTopWindow:function(){try{if(window.top!=window)return!1}catch(c){return!1}return!0}},contentHelper={findSentence:function(c,b){var a=[".","!","?"],e=function(b){for(var c=b.toString(),d=!1;!d;)0<b.startOffset?(b.setStart(b.startContainer,b.startOffset-1),-1!==a.indexOf(b.toString().charAt(0))&&(d=!0,b.setStart(b.startContainer,
b.startOffset+1))):d=!0,c===b.toString()&&(d=!0);return b},d=function(b){for(var c=b.toString(),d=!1;!d;){if(b.endOffset<b.endContainer.textContent.length){try{b.setEnd(b.endContainer,b.endOffset+1)}catch(e){d=!0}-1!==a.indexOf(b.toString().charAt(b.toString().length-1))&&(d=!0,b.setEnd(b.endContainer,b.endOffset-1))}else d=!0;c===b.toString()&&(d=!0)}return b},f=function(a,b,c){b=stringHelper.trimText(b);for(var d=a.indexOf(b);-1!==d;){var e=a.search(new RegExp("[\\"+c.join("\\")+"](\\s|$)","gim"));
if(-1===e)return a;if(d<e)return a.substr(0,e+1);a=a.substr(e+1);d=a.indexOf(b)}return b},h=function(a){for(var b="font b i span u em a strong".split(" "),c=!1;!c;)if("undefined"!==typeof a.parentNode&&null!==a.parentNode){a=a.parentNode;var d;a:{d="div p form ul ol dl li table pre dt dd h1 h2 h3 h4 h5 h6".split(" ");for(var e=a.parentNode.firstChild;null!==e;){if("undefined"!==typeof e.nodeName&&-1!==arrayHelper.indexOf(d,e.nodeName.toLowerCase())){d=!1;break a}if("undefined"!==typeof e.style&&"inline"!==
e.style.display&&""!==e.style.display){d=!1;break a}e=e.nextSibling}d=!0}if(!d||"undefined"!==typeof a.nodeName&&-1===arrayHelper.indexOf(b,a.nodeName.toLowerCase()))c=!0}else c=!0;return a};if(b){for(var g=b.selectionStart,e=b.selectionEnd,d=b.value+".",h=a.join("");-1===h.indexOf(d.charAt(g-1))&&1!==g;)g-=1;for(;-1===h.indexOf(d.charAt(e+1))&&e!==d.length-1;)e+=1;g=d.substring(g,e);f=f(b.value,g,a)}else g=c.getRangeAt(0),g=e(g),g=d(g),e=h(g.startContainer).textContent,f=f(e,g.toString(),a);return f},
extractContext:function(c){var b=null,a=selectionHelper.getSelection(),e=selectionHelper.saveSelection(),d="";if(c)d=c.value.substring(c.selectionStart,c.selectionEnd);else if("function"===typeof a.toString)d=a.toString();else try{d=document.selection.createRange().text}catch(f){}d=stringHelper.trimText(d);lingualeoHelper.canTranslate(d)&&0<d.length&&(b=null,browserDetector.isChrome()||browserDetector.isSafari()?(a.modify("move","left","sentence"),a.modify("extend","right","sentence"),b=stringHelper.trimText(a.toString())):
"function"===typeof a.getRangeAt?b=contentHelper.findSentence(a,c):(a=document.selection.createRange(),c=a.parentElement().innerText||"",a.moveStart("sentence",-1),a.moveEnd("sentence",1),b=a.text,c.length&&b.length>c.length&&(b=c)),b={text:d,context:b===d||b.length<d.length?null:b});selectionHelper.restoreSelection(e);return b}};
