/*

   LinguaLeo English Translator Extension
   (c) 2009-2015, LinguaLeo
   http://lingualeo.com

*/
var lingualeo={browserButtonDefaultHint:"LinguaLeo is cool!",isAuth:!1,userName:"",templates:{},currentOptions:null,translationImageUrls:{},untrainedTimer:null,untrainedWordsCount:0,disabledLanguageDetectionUrls:[/^https:\/\/.*/],regex:{allTags:/<(.|\s)*?>/gi,allSpaces:/ |\t|\r|\n/gim,ieTags:/\x3c!--\[if(.|\s)*?endif\]--\x3e/gi,doubleSpaces:/[\n\r\t]{2,}/gi,doubleLineFeeds:/(\n\s*\n)+/gi,englishSentences:/[^.!?\u0430-\u044f]{30}[.!?]+\s|$/gi,englishWords:/\b\w+\b/gi},isAuthorized:function(){return lingualeo.isAuth},
getUserName:function(){return lingualeo.userName||kango.i18n.getMessage("defaultUserName")},localizeHtml:function(a){if("string"!==typeof a)return a;for(var b={},c=/\{i18n:(.*?)\}/gi,d;null!==(d=c.exec(a));)b["i18n:"+d[1]]=kango.i18n.getMessage(d[1],{USERNAME:lingualeo.getUserName()});return stringHelper.formatStr(a,b)},getTemplate:function(a,b){if(!(a in lingualeo.templates)){var c=a.indexOf("Style")===a.length-5;lingualeo.templates[a]=kango.io.getExtensionFileContents("lingualeo/templates/"+a+(c?
".css":".html"))}return{html:b?lingualeo.localizeHtml(lingualeo.templates[a]):lingualeo.templates[a]}},getTemplates:function(a,b){for(var c={},d=0,e;e=a[d];d++)c[e]=lingualeo.getTemplate(e,b).html;return c},showLoginDialog:function(){kango.browser.tabs.getCurrent(function(a){a.dispatchMessage("showLoginDialog")&&(!a._tab||0!==a._tab.url.indexOf("chrome-extension://")&&0!=a._tab.url.indexOf("chrome://"))||lingualeo.openLinguaLeoPage("profile")})},getQueryParamsDelimiter:function(a){var b=a.indexOf("?");
return b===a.length-1?"":-1===b?"?":"&"},addArgumentsToUrl:function(a,b){b=b||{};var c=Object.keys(b).map(function(a){return a+"="+encodeURIComponent(b[a])}).join("&");return c?a+this.getQueryParamsDelimiter(a)+c:a},openLinguaLeoPage:function(a,b){b=b||{};var c=this.addArgumentsToUrl(lingualeo.config.domain+lingualeo.config.path[a],b);kango.browser.tabs.create({url:c})},openDictionaryPage:function(a){kango.browser.tabs.create({url:lingualeoHelper.getWordArticleUrl(a)})},enableEnjoyContentMode:function(){kango.browser.tabs.getCurrent(function(a){a.dispatchMessage("simplifyPage")})},
getClickableContent:function(a,b){var c=$("<div>"+a+"</div>");lingualeo.nodeWordsWrapper.wrapNodeWords(c);b(c.html())},clearContentOfHtmlTags:function(a){a=$((new DOMParser).parseFromString("<div data-ll-html>"+a+"</div>","text/html"));a.find("footer,style,script,noscript").remove();return a.find("[data-ll-html]").html().replace(lingualeo.regex.ieTags,"").replace(lingualeo.regex.allTags," ")},isContentInEnglish:function(a,b){guessLanguage.detect(lingualeo.clearContentOfHtmlTags(a),function(a){b("en"===
a)})},getPageLanguage:function(a,b,c){if(b)for(var d=0,e;e=lingualeo.disabledLanguageDetectionUrls[d];d++)if(e.test(b))return c(null);a=lingualeo.clearContentOfHtmlTags(a).replace(/(^|(\s\s))[^.!?]+((\s\s)|$)/gi,"\n\n");d=b=0;e=[];for(var g=[],f=a.split(lingualeo.regex.doubleLineFeeds)||[],k=0;k<f.length;k++){var l=f[k],h=l.match(lingualeo.regex.englishSentences)||[];3<=h.length&&(g.push(l),e.push(h.length),3===h.length?b++:5<=h.length&&d++)}4<=b||2<=d||2<=b&&1<=d?guessLanguage.detect(a,c):c(null)},
moveCookiesToBHO:function(){try{var a=kango.lang.getGlobalContext().KangoEngine;if(a){var b=kango.browser.getActiveTab();if(b){var c=b.getBHO();if(c)for(var d=a.getCookie("http://lingualeo.com/api/login",null).split("; "),a=0;a<d.length;a++)-1==d[a].indexOf("remember=")&&-1==d[a].indexOf("lingualeo=")||c.setCookie("http://lingualeo.com/api/login",null,d[a]+"; expires = Sat,01-Jan-2020 00:00:00 GMT; path=/")}}}catch(e){kango.console.log("Error in lingualeo.moveCookiesToBHO. Details: "+e.message)}},
setExtensionCookie:function(){null===kango.storage.getItem("isCookieSet")&&lingualeo.server.setCookieWithServer(function(){kango.storage.setItem("isCookieSet",!0)})},setExtensionOptions:function(a){var b=!1,c;for(c in a)a.hasOwnProperty(c)&&c in lingualeo.defaultOptions&&(kango.storage.setItem(c,a[c]),b=!0);b&&lingualeo.updateOptionsForAllTabs()},getExtensionOptions:function(){var a={},b;for(b in lingualeo.defaultOptions)lingualeo.defaultOptions.hasOwnProperty(b)&&(a[b]=null!=kango.storage.getItem(b)?
kango.storage.getItem(b):lingualeo.defaultOptions[b]);return a},setWizardOptions:function(a){kango.storage.setItem("wizardOptions",JSON.stringify(a||{}))},getWizardOptions:function(){try{return JSON.parse(kango.storage.getItem("wizardOptions"))}catch(a){}return{}},updateExtensionOptionsForBackgroundPage:function(){var a=lingualeo.currentOptions;lingualeo.currentOptions=lingualeo.getExtensionOptions();null!==a&&a.showUntrainedWordsCount===lingualeo.currentOptions.showUntrainedWordsCount||lingualeo.updateUntrainedWordsCounter()},
updateOptionsForAllTabs:function(){lingualeo.sendMessageForAllTabs("updateOptions");lingualeo.updateExtensionOptionsForBackgroundPage()},sendMessageForAllTabs:function(a){kango.browser.tabs.getAll(function(b){for(var c=0;c<b.length;c++)b[c].dispatchMessage(a)})},checkExtensionVersion:function(){kango.storage.getItem("version")||window.setTimeout(function(){kango.ui.optionsPage.open("changelog");var a=window.navigator.userAgent.toLowerCase();/webkit/.test(a)&&!/chrome/.test(a)&&kango.browser.tabs.create({url:lingualeo.config.domain,
focused:!1})},500);kango.storage.setItem("version",kango.getExtensionInfo().version)},disableWizards:function(){lingualeo.setExtensionOptions({wizardsEnabled:!1})},setTranslationImage:function(a,b){b&&(lingualeo.translationImageUrls[a]=b);return b},getTranslationImageUrl:function(a){return a?lingualeo.translationImageUrls[a]:null},getNativeLang:function(){return lingualeo.getUserData("lang_native")||kango.i18n.getCurrentLocale()},isUserHasAccount:function(){return!!lingualeo.getUserData().nickname},
loginUser:function(a,b,c){lingualeo.server.login(a,b,function(a){a.error_msg||(lingualeo.moveCookiesToBHO(),lingualeo.setUserData(a.user),lingualeo.ext.setAuthState(!0),lingualeo.updateUntrainedWordsCounter(),lingualeo.syncLocalDictionary());c(a)})},loadUserData:function(){lingualeo.isAuth&&lingualeo.server.getUserData(function(a){a.error_msg||lingualeo.setUserData(a.user)})},setUserData:function(a){if("object"===typeof a){var b=lingualeo.config.userStorageData,c;for(c in b)b.hasOwnProperty(c)&&c in
a&&(kango.storage.setItem(lingualeo.config.userStorageDataPrefix+c,a[c]),b[c].broadcastMessage&&lingualeo.sendMessageForAllTabs(b[c].broadcastMessage));lingualeo.userName=a.fname||a.nickname;lingualeo.server.setUserLocale(lingualeo.getNativeLang())}},getUserData:function(a){if("string"===typeof a)return kango.storage.getItem(lingualeo.config.userStorageDataPrefix+a);a={};var b=lingualeo.config.userStorageData,c;for(c in b)b.hasOwnProperty(c)&&(a[c]=kango.storage.getItem(lingualeo.config.userStorageDataPrefix+
c));return a},clearUserData:function(){var a=lingualeo.config.userStorageData,b;for(b in a)a.hasOwnProperty(b)&&!a[b].persistent&&kango.storage.removeItem(lingualeo.config.userStorageDataPrefix+b)},checkAuthorization:function(a){lingualeo.ext.setAuthState(!1);lingualeo.ext.setStateHints(kango.i18n.getMessage("stateAuthorization"),"...");lingualeo.server.checkAuthorization(!0,function(b){lingualeo.ext.setAuthState(b);lingualeo.updateUntrainedWordsCounter();lingualeo.loadUserData();b&&lingualeo.syncLocalDictionary();
a&&a(b)},function(){lingualeo.ext.setAuthState(!1);a&&a(!1)})},syncLocalDictionary:function(){lingualeo.isAuth&&lingualeo.localDictionary.getTranslationsCount()&&lingualeo.server.setWordTranslationMultiple(lingualeo.localDictionary.getTranslationsAsArray(),function(){lingualeo.localDictionary.clearTranslations()},function(a,b,c){b.error_code&&12!==b.error_code&&lingualeo.ext.showNotification({title:kango.i18n.getMessage("errorSyncingDictionary"),text:"Error code: "+b.error_code+". Response status: "+
c,forceShowing:!0})})},getHistoryHtml:function(){return lingualeo.history.getHistoryHtml()},clearHistory:function(){return lingualeo.history.clearHistory()},translateWithGoogle:function(a,b,c,d){lingualeo.server.translateCustomText(a,b,c,function(a){a.error||!a.translation?d({error:!0,error_msg:kango.i18n.getMessage("translationErrorMessage"),error_code:a.error_code}):d(a)})},getTranslations:function(a,b,c){a.length>lingualeo.config.maxTextLengthToTranslate?(lingualeo.ext.showNotification({title:kango.i18n.getMessage("textTooLong"),
text:kango.i18n.getMessage("mustBeLessThan").replace(/\$1/,""+lingualeo.config.maxTextLengthToTranslate),forceShowing:!0}),c({error:!0,error_msg:kango.i18n.getMessage("textTooLong")})):lingualeo.server.loadTranslations(a,function(d){c({context:b,originalText:a,word_forms:d.word_forms,translations:d.translate,transcription:d.transcription,soundUrl:(""+d.sound_url).replace("http://","https://"),picUrl:lingualeo.setTranslationImage(a,(d.pic_url||"").replace("http://","https://"))})},function(a,b,g){c({error:!0,
error_msg:a,error_code:b?b.error_code:null,status:g})})},setWordTranslation:function(a,b,c,d,e,g,f){lingualeo.isAuth?lingualeo.server.setWordTranslation(a,b,c,d,e,function(){lingualeo.history.addItem(a,b,c,d,e);!1!==g&&lingualeo.ext.showNotificationForTranslation(a,b,!1,function(){lingualeo.openDictionaryPage(a)});lingualeo.updateUntrainedWordsCounter(6E5);f&&f(!0)},function(a,b){f&&f(!1)}):lingualeo.localDictionary.getTranslationsCount()<lingualeo.config.localDictionaryMaxWordsCount?(lingualeo.localDictionary.addTranslation(a,
b,c,d,e),lingualeo.history.addItem(a,b,c,d,e),!1!==g&&lingualeo.ext.showNotification({title:kango.i18n.getMessage("dictUpdated"),text:a+" \u2014 "+b,originalText:a,forceShowing:!1,handler:function(){lingualeo.openLinguaLeoPage("registerViaExtension",{utm_campaign:"notification"})}}),f&&f(!0)):(kango.browser.tabs.getCurrent(function(a){a.dispatchMessage("showLocalDictionaryLimitDialog")&&(!a._tab||0!==a._tab.url.indexOf("chrome-extension://")&&0!=a._tab.url.indexOf("chrome://"))||lingualeo.ext.showNotification({title:kango.i18n.getMessage("registrationRequired_Title1"),
text:kango.i18n.getMessage("notificationTitleSignIn"),forceShowing:!0,handler:function(){lingualeo.openLinguaLeoPage("registerViaExtension",{utm_campaign:"notification"})}})}),f&&f(!1))},updateUntrainedWordsCounter:function(a){lingualeo.untrainedTimer&&(clearTimeout(lingualeo.untrainedTimer),lingualeo.untrainedTimer=null);lingualeo.isAuth&&(lingualeo.currentOptions.showUntrainedWordsCount?(lingualeo.server.getUntrainedWordsCount(function(a){lingualeo.isAuth&&lingualeo.ext.setUntrainedWordsCount(a.count)}),
kango.storage.setItem("lastUntrainedWordsCountUpdate",(new Date).getTime()),lingualeo.untrainedTimer=setTimeout(lingualeo.updateUntrainedWordsCounter,a||lingualeo.config.untrainedWordsCheckingTimeout)):lingualeo.ext.setUntrainedWordsCount(null))},initContextMenu:function(){lingualeo.contextMenu.createTranslationItem(function(){kango.browser.tabs.getCurrent(function(a){a.dispatchMessage("getContext")})});lingualeo.contextMenu.setTranslationItemVisibility(!0)},toggleContextMenu:function(a){lingualeo.contextMenu.setTranslationItemVisibility(a)},
assignServerEvents:function(){lingualeo.server.responseStatusErrorHandler=function(a,b){var c,d=kango.i18n.getMessage("error");404==a||0==a?(d=kango.i18n.getMessage("error404"),c=kango.i18n.getMessage("errorNoConnection")):503==a?(b=!1,d=kango.i18n.getMessage("error503"),c=kango.i18n.getMessage("serverUpdating")):(d=kango.i18n.getMessage("responseCode").replace(/\$1/,""+a),c=kango.i18n.getMessage("errorNoConnection"));b||lingualeo.ext.showNotification({title:d,text:c})};lingualeo.server.responseErrorHandler=
function(a,b,c){12===b?kango.browser.tabs.getCurrent(function(a){(!a.dispatchMessage("showNoMeatballsDialog")||a._tab&&(0<a._tab.url.indexOf("://lingualeo.com")||0===a._tab.url.indexOf("chrome-extension://")||0==a._tab.url.indexOf("chrome://")))&&lingualeo.ext.showNotification({title:kango.i18n.getMessage("noMeatballs"),text:kango.i18n.getMessage("noMeatballsText"),hideTimeout:6E4,handler:function(){lingualeo.openLinguaLeoPage("meatballs")},forceShowing:!0})}):c||lingualeo.ext.showNotification({title:kango.i18n.getMessage("error"),
text:a,forceShowing:!0})}},showSiteNotifications:function(a){for(var b=0;b<a.length;b++)(function(a){var b=a.notification_url,e=a.notification_header,g={forceShowing:!1,text:a.notification_text,title:e,mainImageUrl:a.notification_pic_url,url:"http:"+b+(-1<b.indexOf("?")?"&":"?")+"utm_source=ll_plugin&utm_medium=referral&utm_campaign=notification&utm_content="+e};lingualeo.ext.showNotification(g,function(){kango.browser.tabs.create({url:g.url})})})(a[b])},checkSiteNotifications:function(){if(lingualeo.isAuth&&
lingualeo.currentOptions.showBrowserPopups&&lingualeo.currentOptions.showSiteNotifications){var a=kango.storage.getItem("lastSiteNotificationsCheck")||0,b=(new Date).getTime();36E5<b-a&&(kango.storage.setItem("lastSiteNotificationsCheck",b),(a=lingualeo.getUserData("user_id"))&&lingualeo.server.checkSiteNotifications(a,function(a){lingualeo.isAuth&&a.notification&&a.notification.length&&lingualeo.showSiteNotifications(a.notification)}))}window.setTimeout(lingualeo.checkSiteNotifications,36E5)},approveYoutubeCaptionsInfo:function(a,
b){lingualeo.server.getYoutubeCaptionsInfo(a,function(a){b(!(!a.text||!/lang_code="en"/gi.test(a.text)))})},exportYoutubeContent:function(a,b){lingualeo.server.exportYoutubeContentToJungle(a,lingualeo.config.defaultExportedYoutubeContentGenre,b)},init:function(){lingualeo.config=new LinguaLeoConfig;lingualeo.ext=new LinguaLeoExt;lingualeo.localDictionary=new LinguaLeoLocalDictionary;lingualeo.history=new LinguaLeoHistory;lingualeo.defaultOptions=new LinguaLeoDefaultOptions;lingualeo.contextMenu=new LinguaLeoContextMenu;
lingualeo.initContextMenu();lingualeo.nodeWordsWrapper=new NodeWordsWrapper;lingualeo.server=new LingualeoServer(lingualeo.config.api,lingualeo.getNativeLang());lingualeo.assignServerEvents();lingualeo.updateExtensionOptionsForBackgroundPage();lingualeo.checkExtensionVersion();lingualeo.setExtensionCookie();lingualeo.checkAuthorization();kango.browser.addEventListener(kango.browser.event.DOCUMENT_COMPLETE,function(a){var b=/^.*\/\/([^\/]+).*$/i,c=a.url.replace(b,"$1"),b=lingualeo.config.domain.replace(b,
"$1");0<a.url.indexOf("ll_reset_extension")&&kango.storage.clear();c===b&&(lingualeo.setExtensionCookie(),kango.browser.cookies.getCookies("http://"+c,function(a){for(var b=!1,c=0;c<a.length;c++)if(a[c]&&"remember"===a[c].name){b=!0;break}b!=lingualeo.isAuth&&window.setTimeout(lingualeo.checkAuthorization,100)}))});kango.ui.browserButton.setCaption("LinguaLeo");window.setTimeout(lingualeo.checkSiteNotifications,3E5)}};lingualeo.init();
