var NodeWordsWrapper=function(a){this.params=$.extend({},{locale:"en",re:{chars:{delims:'\u20ac\u00a3\\$\\s,.\u2026!\\?:;\\|\\\u201c\\\u201d\u00ab\u00bb"\\[\\]\\(\\)\\{\\}\u2018\u2019',wrappingWordAdd:"-\u2013`'\u20190-9"},localeChars:{en:{wrappingWord:"a-z"},ru:{wrappingWord:"\u0430-\u044f"}}}},a);$.extend(this.params.re.chars,this.params.re.localeChars[this.params.locale]);$.extend(this.params.re,{expressions:{correctWordForWrapping:new RegExp("^(["+this.getWordCharacters()+this.getWordAddCharacters()+
"]+)$","i"),onlyAddWordChars:new RegExp("^["+this.getWordAddCharacters()+"]+$","i"),delimiter:new RegExp("["+this.getDelimCharacters()+"]+","gi")}})};
NodeWordsWrapper.prototype={unwrapTranElements:function(a){a=$(a).find("tran");var c=a.length;a.each(function(){$(this).contents().insertAfter(this)});a.remove();return c},wrapElementWordsAndCheckIntegrity:function(a){var c=this,b=$(a),d=b.clone();d.find(".no-tran").remove();d.hide().insertBefore(a);d.each(function(){$(this).text(c.getNodeText(this))});this.wrapNodeWords(b);this.wrapNodeWords(d);a=b.find("tran");var f=d.find("tran");return{isIntegral:a.length==f.length,$clearCloneWords:f,$clearClone:d,
$words:a,$container:b}},fixIntegrity:function(a){for(var c=a.$clearCloneWords,b=a.$words,d=0,f=!0,e=0;e<c.length;e++){var h=c.eq(e),g=b.eq(e+d),k={};if(g.text()!=h.text()){for(;g.text()!=h.text()&&g.text().length<h.text().length&&d<b.length;){k=this.joinSiblingTrans(g,b.eq(e+1+d));if(!k.joined){f=!1;break}g=k.$word;d+=k.addDelta}if(d>=b.length||0==d||g.text()!=h.text())f=!1;if(!f)break}}return $.extend({},a,{fixed:f})},joinSiblingTrans:function(a,c){if(!a.length||!c.length)return{joined:!1};var b=
a,d="getNodeLeftSibling",f="append",e=c,h=a.parents(),g=c.parents(),k=!1,l=void 0;if(h.length>g.length)b=c,e=a,d="getNodeRightSibling",f="prepend";else if(h.length==g.length){h=a;for(g=c;h&&g&&!this.getNodeRightSibling(h).is(g);)h=this.getNodeParent(h),g=this.getNodeParent(g);h&&g&&(b=$("<tran>").insertBefore(h),b.append(h).append(g),k=!0,l=b.find("tran").length-1)}if(!k){for(;e&&!this[d](e).is(b);)e=this.getNodeParent(e);e&&(b[f](e),k=!0)}k&&(d=this.unwrapTranElements(b),void 0===l&&(l=d));return{joined:k,
$word:b,addDelta:l}},getNodeParent:function(a){return(a=$(a).parent())&&a.length?a:null},getNodeRightSibling:function(a){a=$(a)[0].nextSibling;return $(a)},getNodeLeftSibling:function(a){a=$(a)[0].previousSibling;return $(a)},replaceNodeWith:function(a,c,b){var d=a.parentNode;c instanceof Array||(c=[c]);c.forEach(function(b){d.insertBefore(b,a)});b||a.parentNode.removeChild(a)},getNodeText:function(a){var c=$(a),b=c.clone().hide(),d={BR:"\n"},f=[];c.closest("html").length?b.insertBefore(a):b.appendTo("body");
b.each(function(){var a=$(this);a.find("*").each(function(){var a=getComputedStyle(this).display,b=d[this.nodeName]||"inline"!=a?" ":void 0;b&&"none"!=a&&(this.nextSibling&&this.parentNode.insertBefore(document.createTextNode(b),this.nextSibling),this.previousSibling&&this.parentNode.insertBefore(document.createTextNode(b),this))});f.push(a.text().trim())});b.remove();return f.join("\n\n")},filterChildren:function(a){return a.not(a.children())},wrapNodeWords:function(a){var c=this;a=this.filterChildren($(a));
a.hasClass("no-tran")||a.contents().each(function(){c.isTextNode(this)?c.wrapTextNodeWords(this):c.wrapNodeWords(this)})},isTextNode:function(a){return 3===a.nodeType},wrapTextNodeWords:function(a){var c=this.mkWrappedNodesArray(a.data);this.replaceNodeWith(a,c)},getWordCharacters:function(){return this.params.re.chars.wrappingWord},getWordAddCharacters:function(){return this.params.re.chars.wrappingWordAdd},getDelimCharacters:function(){return this.params.re.chars.delims},isWordForWrapping:function(a){var c=
this.params.re.expressions.onlyAddWordChars;return this.params.re.expressions.correctWordForWrapping.test(a)&&!c.test(a)},mkWordNode:function(a,c){var b;c?(b=document.createElement(c),b.innerHTML=a):b=document.createTextNode(a);return b},mkWrappedNodesArray:function(a,c){for(var b=this,d=this.params.re.expressions.delimiter,f=a.match(d)||[],d=a.split(d)||[],e=[],d=d.map(function(a){return b.mkWordNode(a,b.isWordForWrapping(a)?"tran":void 0)});d.length;)e.push(d.shift(),this.mkWordNode(f.shift()||
""));f.length&&(e=[this.mkWordNode(a)]);e=e.filter(function(a){return a.data||a.innerHTML});if(c)c(e);else return e},wrapElementWordsWithIntegrityFixing:function(a,c){var b=this.wrapElementWordsAndCheckIntegrity(a);b.isIntegral||(b=this.fixIntegrity(b));b.$clearClone.remove();var d=b.isIntegral||b.fixed;d||this.unwrapTranElements(a);b=$.extend({},b,{wrapped:d});if(c)c(b);else return b}};
