/*

   LinguaLeo English Translator Extension
   (c) 2009-2015, LinguaLeo
   http://lingualeo.com

*/
KangoAPI.onReady(function(){function C(){kango.invokeAsync("window.lingualeo.enableEnjoyContentMode");KangoAPI.closeWindow()}function D(){kango.invokeAsync("window.lingualeo.showLoginDialog");KangoAPI.closeWindow()}function r(){kango.invokeAsync("window.lingualeo.openLinguaLeoPage","root");KangoAPI.closeWindow()}function E(){kango.ui.optionsPage.open();KangoAPI.closeWindow()}function F(){e.val("").trigger("input").focus()}function G(){kango.invokeAsync("window.lingualeo.clearHistory",function(){s()})}
function t(){var a=$("#soundIcon");if(browserDetector.canPlayMp3()){var b=$("#player").get(0);browserDetector.isChrome()&&(b.src=b.src);b.play()}else b='<iframe id="soundFrame" src="'+(H.path.audio_player+g.soundUrl)+'" width="0" height="0" style="width:0; height:0; visibility:hidden !important; border:0; overflow:hidden; margin:0; padding:0;" marginwidth="0" marginheight="0" hspace="0" vspace="0" frameborder="0" scrolling="no"></iframe>',a.find("#soundFrame").remove().end().append(b);setTimeout(function(){a.addClass("playing");
setTimeout(function(){a.removeClass("playing");a=null},500)},400);return!1}function u(a){var b=stringHelper.trimText(e.val());f!==b&&(f=null,n.css("display",b?"block":"none"),s(),p(),l&&clearTimeout(l),b&&(l=setTimeout(function(){f=b;I.test(b)?J(b,"ru","en"):v(b,null);l=null},null==a?0:1200)))}function K(a){if(27===a.keyCode){if(e.val())return n.click(),!1}else if(13===a.keyCode)return e.val()||L(),u(null),!1;return!0}function M(){if(g){var a=+$(this).data("index");kango.invokeAsync("window.lingualeo.setWordTranslation",
g.originalText,g.translations[a].value,null,null,"via LinguaLeo Browser Extension",!0);KangoAPI.closeWindow()}}function N(a){for(var b="",c=0,d;d=a[c];c++)b+=stringHelper.formatStr('<li><a href="#" class="translation-item" data-index="{index}">{text}</a></li>',{index:c,text:htmlHelper.escapeHTML(d.value)});return b}function J(a,b,c){m.addClass("animated");kango.invokeAsyncCallback("window.lingualeo.translateWithGoogle",a,b,c,function(b){a===f&&(p(),b.error?w(b):(f=b.translation,v(f,function(){d.append(stringHelper.formatStr(h["popup/translationsFromGoogle"],
{translation:htmlHelper.escapeHTML(b.translation)}));k()})))})}function v(a,b){m.addClass("animated");kango.invokeAsyncCallback("window.lingualeo.getTranslations",a,null,function(c){a===f&&(p(),c.error?101==c.error_code||102==c.error_code?x(a):w(c):"[object Array]"!==Object.prototype.toString.call(c.translations)||!c.translations.length||1===c.translations.length&&c.translations[0].value===c.originalText?x(a):(b&&b(),g=c,d.append(stringHelper.formatStr(h["popup/translations"],{soundUrl:c.soundUrl,
transcription:c.transcription||"---",translations:N(c.translations)})),y(c.originalText),z.autoplaySound&&t()))})}function p(){m.removeClass("animated")}function w(a){var b=a.error_msg;a.error_code&&(b+="<br/>"+stringHelper.formatStr(i18n.getLocaleMessage("serverResponseCode"),{code:a.error_code}));d.append(stringHelper.formatStr(h["popup/translationsError"],{message:b}));k()}function L(){e.addClass("horizontal-shake");setTimeout(function(){e.removeClass("horizontal-shake")},1E3)}function y(a){a=
stringHelper.formatStr(h["popup/dictionaries"],{html:dictionariesHelper.getHtml({text:a,locale:A})});d.append(a);k()}function x(a){d.html(stringHelper.formatStr(h["popup/noTranslations"],{text:i18n.getLocaleMessage("noTranslationsMessage")}));y(a)}function s(){d.html()&&(d.empty(),g=null,k())}function O(){kango.invokeAsync("window.lingualeo.getHistoryHtml",function(a){a&&(d.html(a),k())})}function k(){browserDetector.isFirefox()&&KangoAPI.resizeWindow(document.documentElement.offsetWidth,document.documentElement.offsetHeight)}
function P(a){a&&($("#btnLogin,#btnProfile").hide(),q.show())}function Q(){m=$("#loader");d=$("#translationsContainer");$("#btnLogin").on("click",D);$("#btnProfile").on("click",r);$("#btnOptions").on("click",E);n=$("#btnClearInput").on("click",F);$("#container").on("click",".translation-item",M).on("click","#soundIcon",t);e=$("#inptOriginalText").on("input",u).on("keydown",K);B=$("#btnEnjoyContent").on("click",C);$("body").on("click","#btnClearHistory",G);q=$("#imgAvatar").on("click",r);kango.invokeAsync("window.lingualeo.getUserData",
null,function(a){q.attr("src",a.avatar_mini||"data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==")});kango.browser.tabs.getCurrent(function(a){a.dispatchMessage("")&&(!a._tab||0!==a._tab.url.indexOf("chrome-extension://")&&0!=a._tab.url.indexOf("chrome://"))||B.attr("disabled",!0)});kango.invokeAsync("window.lingualeo.isAuthorized",P);lingualeoHelper.getTemplates(R,!0,function(a){h=a})}var H=new LinguaLeoConfig,z=null,A="en",l,f,g=null,m,e,q,n,B,d,h,I=/[\u0430-\u044f]/i,R=
["popup/translations","popup/translationsFromGoogle","popup/translationsError","popup/dictionaries","popup/noTranslations"];k();kango.invokeAsync("window.lingualeo.getNativeLang",function(a){A=a});kango.invokeAsync("window.lingualeo.getExtensionOptions",function(a){z=a;i18n.updateLocaleMessages(!1,function(){i18n.localizeDom(domHelper.getBody());Q();setTimeout(O,100)});setTimeout(function(){e.focus()},400)});$(function(){var a=$("#container");setTimeout(function(){a.width(a.width()+1)},150)})});
