/*

// ==UserScript==
// @name LinguaLeoContent
// @all-frames true
// @include http://*
// @include https://*
// @include file://*
// @include file:///*
// @exclude http*://lingualeo.com/*
// @exclude http*://lingualeo.ru/*
// @exclude http*://*facebook.com/plugins/*
// @exclude http*://*twitter.com/widgets/*
// @exclude http*://plusone.google.com/*
// ==/UserScript==
*/
(function(){var a=LinguaLeoConfig().modules,b;for(b in a)a.hasOwnProperty(b)&&("undefined"!==typeof window[b]&&a[b]||(window[b]=null))})();
var llContent={config:null,options:null,nativeLang:null,timerPageLanguageDetection:null,lastTextSentToTranslation:null,isMac:-1<window.navigator.userAgent.toLowerCase().indexOf("macintosh"),updateNativeLanguage:function(a){kango.invokeAsync("window.lingualeo.getNativeLang",function(b){llContent.nativeLang=b;a&&a()})},updateOptions:function(a){kango.invokeAsync("window.lingualeo.getExtensionOptions",function(b){llContent.options=b;a&&a()})},injectStyle:function(){lingualeoHelper.getTemplate("content/commonStyle",
cssHelper.addCss)},showMeatballsDialog:function(){LinguaLeoWizardManager.activateWizard("meatballsLimit",null,null)},showLocalDictionaryLimitDialog:function(){LinguaLeoWizardManager.activateWizard("localDictionaryLimit",null,null)},openSettings:function(){kango.invokeAsync("kango.ui.optionsPage.open")},getTranslationsHtml:function(a,b){var c=[];if(a&&a.length){var e=0;b&&(a.splice(0,1),e++);a=a.slice(0,5);c=arrayHelper.map(a,function(a){return stringHelper.formatStr('<div class="ll-translation-item" data-index="{index}"><div class="ll-translation-text" data-index="{index}"><span class="ll-translation-marker"></span><a href="javascript:void 0" data-index="{index}">{text}</a></div>\x3c!--<div class="ll-translation-counter">{votesCount}</div>--\x3e</div>',
{index:e++,text:htmlHelper.escapeHTML(a.value),votesCount:htmlHelper.escapeHTML(a.votes)})})}return c.join("")},getArticleTemplateData:function(){var a=llContent.dialog.curData;if("undefined"===typeof a.translations.length){for(var b=[],c=0,e;e=a.translations[c];c++)b.push(e);a.translations=b}b=null;c=!0;e=a.originalText;var f=!!a.inDictionary,g=!(!a.translations||!a.translations.length);a.word_forms&&a.word_forms.length&&stringHelper.trimText(e.toLowerCase())!=stringHelper.trimText(a.word_forms[0].word.toLowerCase())&&
(c=!1,b=a.word_forms[0].word);var d="";llContent.options.showDictIcons&&(d=dictionariesHelper.getHtml({text:e,locale:llContent.nativeLang}));return{originalText:htmlHelper.escapeHTML(e),inDict:f,soundUrl:htmlHelper.escapeHTML(a.soundUrl)||"",hasPic:!(!llContent.options.showPicture||!a.picUrl),imagesUrl:htmlHelper.escapeHTML(llContent.config.path.images),transcription:htmlHelper.escapeHTML(a.transcription)||"---",showDicts:htmlHelper.escapeHTML(llContent.options.showDictIcons),transItems:llContent.getTranslationsHtml(a.translations,
f),seeAlsoHint:htmlHelper.escapeHTML(i18n.getLocaleMessage("seeAlsoHint")),soundHint:htmlHelper.escapeHTML(i18n.getLocaleMessage("soundButtonHint")),optionsBtnHint:htmlHelper.escapeHTML(i18n.getLocaleMessage("optionsBtnHint")),addTranHint:htmlHelper.escapeHTML(i18n.getLocaleMessage("enterCustomTranslation")),translateContextHint:htmlHelper.escapeHTML(i18n.getLocaleMessage("translateContextHint")),picUrl:htmlHelper.escapeHTML(llContent.options.showPicture&&a.picUrl||llContent.config.path.images+"/blank.gif"),
context:llContent.options.showContext?a.context?stringHelper.wrapWordWithTag(htmlHelper.escapeHTML(a.context),e,"b"):null:null,dictionariesLinksHTML:d,translatedText:b&&!c?htmlHelper.escapeHTML(i18n.getLocaleMessage("baseFormHint"))+":":f?htmlHelper.escapeHTML(a.translations[0].value):g?htmlHelper.escapeHTML(i18n.getLocaleMessage("chooseTranslationHint"))+":":htmlHelper.escapeHTML(i18n.getLocaleMessage("noTranslationHint"))+".",baseForm:htmlHelper.escapeHTML(b)}},playSound:function(){if(browserDetector.canPlayMp3()){var a=
document.getElementById("lleo_player");browserDetector.isChrome()&&(a.src=a.src);a.play();var b=document.getElementById("lleo_soundWave");cssHelper.addClass(b,"lleo_beforePlaying");setTimeout(function(){cssHelper.addClass(b,"lleo_playing");setTimeout(function(){b.style.display="none !important";cssHelper.removeClass(b,"lleo_beforePlaying");cssHelper.removeClass(b,"lleo_playing");b=null},500)},400)}else a='<iframe id="lleo_soundFrame" src="'+(llContent.config.path.audio_player+llContent.dialog.curData.soundUrl)+
'" width="0" height="0" style="width:0; height:0; visibility:hidden !important; border:0; overflow:hidden; margin:0; padding:0;" marginwidth="0" marginheight="0" hspace="0" vspace="0" frameborder="0" scrolling="no"></iframe>',domHelper.removeChild(document.getElementById("lleo_soundFrame")),domHelper.appendHtmlToElement(document.getElementById("lleo_sound"),a);return!1},showTranslations:function(a){llContent.dialog.elem&&(llContent.dialog.curData=a,lingualeoHelper.getTemplate("content/translations",
function(a){a=stringHelper.formatStrExt(a,llContent.getArticleTemplateData());llContent.dialog.elem.className="lleo_show";llContent.dialog.setContent(a);Event.add(document.getElementById("lleo_sound"),"click",llContent.playSound);Event.add(document.getElementById("lleo_trans"),"click",llContent.handlers.clickTranslationsList);Event.add(document.getElementById("lleo_baseForm"),"click",llContent.handlers.baseFormClick);Event.add(document.getElementById("lleo_setTransForm"),"submit",llContent.handlers.submitCustomTranslation);
if(browserDetector.isSafari()||browserDetector.isIE())a=document.getElementById("lleo_optionsBtn"),cssHelper.addClass(llContent.dialog.elem,"lleo_optionsShown"),Event.add(a,"click",llContent.openSettings);llContent.options.autoplaySound&&llContent.playSound();llContent.options.showContext&&(llContent.options.autoTranslateContext?llContent.handlers.clickTranslateContext():Event.add(document.getElementById("lleo_translateContextLink"),"click",llContent.handlers.clickTranslateContext))}))},showLoginDialog:function(a){if(lingualeoHelper.isTopWindow())if("undefined"!==
typeof showLoginDialog){var b=selectionHelper.saveSelection();showLoginDialog(a,function(a){a&&(selectionHelper.restoreSelection(b),llContent.showTranslationsDialog())})}else kango.invokeAsync("window.lingualeo.openLinguaLeoPage","profile")},showTranslatesDialog:function(a){llContent.dialog.create();llContent.lastTextSentToTranslation=a.text;kango.invokeAsyncCallback("window.lingualeo.getTranslations",a.text,a.context,function(b){a.text===llContent.lastTextSentToTranslation&&(b.error?llContent.dialog.remove():
llContent.showTranslations(b))})},showDialogForCurrentSelection:function(a,b){if(!a||!a.getAttribute||"password"!==a.getAttribute("type")){var c;try{c=selectionHelper.getSelection()}catch(e){return}if(!a&&b&&c.isCollapsed)try{c.modify("move","left","word"),c.modify("extend","right","word")}catch(f){}var g=contentHelper.extractContext(a);if(g&&(/\s/ig.test(g.text)||(g.text=g.text.replace(/^(\w+)[.,;:\u201d"']*$/gi,"$1")),!/^\d+$/i.test(g.text))){var d=null;if(a)d=a.getBoundingClientRect();else if("function"===
typeof c.getRangeAt){if(c=c.getRangeAt(0),d=c.getBoundingClientRect(),browserDetector.isOpera()||browserDetector.isFirefox()){var h=sizeHelper.clientSize();if(!sizeHelper.pointInRect({x:d.left,y:d.top},{left:0,top:0,right:h.width,bottom:h.height})){for(d=c.startContainer;"undefined"===typeof d.tagName;)d=d.parentNode;c=sizeHelper.getOffset(d);h=llContent.dialog.scrollOffsetOnClick||sizeHelper.scrollOffset();c.left-=h.left;c.top-=h.top;d={left:c.left,top:c.top,width:d.offsetWidth,height:d.offsetHeight};
d.right=d.left+d.width;d.bottom=d.top+d.height}}}else d=document.selection.createRange().getClientRects()[0];llContent.dialog.scrollOffsetOnClick=sizeHelper.scrollOffset();llContent.dialog.rect=d;llContent.showTranslatesDialog(g)}}},showTranslationsDialog:function(){var a=null;"undefined"===typeof document.activeElement.tagName||"INPUT"!==document.activeElement.tagName&&"TEXTAREA"!==document.activeElement.tagName||(a=document.activeElement);llContent.showDialogForCurrentSelection(a,!0)},tryToSimplifyPage:function(){llSimplified&&
(clearTimeout(llContent.timerPageLanguageDetection),llSimplified.simplifyPage(function(a){LinguaLeoWizardManager.activateWizard(a?"enjoyContentExplain":"enjoyContentNoContent",2E3)}))},detectPageLanguage:function(){llSimplified&&llContent.options.enjoyContentControlsEnabled&&(llContent.timerPageLanguageDetection=setTimeout(function(){var a=domHelper.getBody().innerHTML;kango.invokeAsyncCallback("window.lingualeo.getPageLanguage",a,window.location.href,function(a){"en"===a&&LinguaLeoWizardManager.activateWizard("enjoyContentWelcome",
0,function(a){a||LinguaLeoWizardManager.activateWizard("enjoyContentControlsExplain",0,function(a){LinguaLeoWizardManager.activateWizard("enjoyContentControls",a?2E3:0)})})})},llContent.config.languageDetectionTimeout))},bindEventHandlers:function(){var a=llContent.config.userStorageData.lang_native;a&&kango.addMessageListener(a.broadcastMessage,function(){llContent.updateNativeLanguage(null)});(a=llContent.config.userStorageData.lang_interface)&&kango.addMessageListener(a.broadcastMessage,function(){i18n.updateLocaleMessages(!0)});
Event.add(document,"contextmenu",llContent.handlers.contextMenu);Event.add(window,"resize",llContent.dialog.remove);Event.add(document,"dblclick",llContent.handlers.dblClick);Event.add(document,"keydown",llContent.handlers.keyDown);Event.add(document,"mousedown",llContent.dialog.remove);browserDetector.isOpera()&&Event.add(document,"mouseup",llContent.handlers.operaMouseUp);kango.addMessageListener("getContext",llContent.showTranslationsDialog);kango.addMessageListener("updateOptions",function(){llContent.updateOptions(null)});
kango.addMessageListener("showLoginDialog",function(){llContent.showLoginDialog(!0)});kango.addMessageListener("showNoMeatballsDialog",llContent.showMeatballsDialog);kango.addMessageListener("simplifyPage",llContent.tryToSimplifyPage);kango.addMessageListener("showLocalDictionaryLimitDialog",llContent.showLocalDictionaryLimitDialog)},init:function(){llContent.config=new LinguaLeoConfig;llContent.bindEventHandlers();llContent.injectStyle();llContent.updateNativeLanguage(function(){llContent.updateOptions(function(){llContent.detectPageLanguage();
llYoutube&&llYoutube.init()})})},dialog:{elem:null,rect:null,curData:null,scrollOffsetOnClick:null,handlerStopEventPropagation:function(a){a.stopPropagation()},create:function(){lingualeoHelper.getTemplate("content/dialog",function(a){a=stringHelper.formatStrExt(a,{imagesUrl:htmlHelper.escapeHTML(llContent.config.path.images),closeBtnHint:htmlHelper.escapeHTML(i18n.getLocaleMessage("dlgCloseHint")+" (Esc)")});llContent.dialog.remove();domHelper.appendHtmlToElement(domHelper.getBody(),a);llContent.dialog.elem=
document.getElementById("lleo_dialog");Event.add(llContent.dialog.elem,"mouseup",llContent.dialog.handlerStopEventPropagation);Event.add(llContent.dialog.elem,"dblclick",llContent.dialog.handlerStopEventPropagation);Event.add(llContent.dialog.elem,"mousedown",llContent.dialog.handlerStopEventPropagation);Event.add(llContent.dialog.elem,"contextmenu",llContent.dialog.handlerStopEventPropagation);llContent.dialog.setContent('<div class="lleo_empty">Loading...</div>');setTimeout(function(){llContent.dialog.elem&&
cssHelper.addClass(llContent.dialog.elem,"lleo_show lleo_show_small")},0)})},remove:function(){var a=document.getElementById("lleo_dialog");a&&(a.parentNode.removeChild(a),llContent.dialog.elem=null)},setContent:function(a){document.getElementById("lleo_dialogContent").innerHTML=a;llContent.dialog.updatePosition()},updatePosition:function(){var a=domHelper.getBody(),b=a.getBoundingClientRect(),c=llContent.dialog.scrollOffsetOnClick||sizeHelper.scrollOffset(),b=b.top+c.top;llContent.dialog.scrollOffsetOnClick=
null;var e=c.left+llContent.dialog.rect.left-12,f=c.top+llContent.dialog.rect.top-llContent.dialog.elem.offsetHeight-10-b;f<c.top&&(f=c.top+llContent.dialog.rect.bottom+10-b);e<c.left+5?e=c.left+5:e+llContent.dialog.elem.offsetWidth>c.left+a.offsetWidth-35&&(e=c.left+a.offsetWidth-llContent.dialog.elem.offsetWidth-35);llContent.dialog.elem.style.left=e+"px";llContent.dialog.elem.style.top=f+"px"},setTranslatedContext:function(a){llContent.dialog.elem&&(document.getElementById("lleo_context").innerHTML=
a)}},handlers:{contextMenu:function(){kango.invokeAsyncCallback("window.lingualeo.toggleContextMenu",!window.getSelection().isCollapsed)},baseFormClick:function(){var a=llContent.dialog.curData.word_forms;(a=a&&a.length?a[0].word:null)&&llContent.showTranslatesDialog({text:a,context:null});return!1},dblClick:function(a){if(!llContent.options.useDblClick||llSimplified&&llSimplified.isSimplifiedModeOn())return!0;if(!llContent.options.dblClickWithCtrl&&!llContent.options.dblClickWithAlt||llContent.options.dblClickWithCtrl&&
(llContent.isMac?a.metaKey:a.ctrlKey)||llContent.options.dblClickWithAlt&&a.altKey){if("undefined"!==typeof a.target.tagName&&("INPUT"===a.target.tagName||"TEXTAREA"===a.target.tagName))return!0;llContent.showDialogForCurrentSelection(null,!1);return!1}},keyDown:function(a){27===a.keyCode?llContent.dialog.remove():a.ctrlKey&&76===a.keyCode&&llContent.showTranslationsDialog()},saveTranslation:function(a){if(a){var b=llSimplified&&llSimplified.isSimplifiedModeOn();kango.invokeAsyncCallback("window.lingualeo.setWordTranslation",
llContent.dialog.curData.originalText,a,llContent.dialog.curData.context,document.URL,document.title,!b,function(a){a&&b&&llSimplified.addWordToList(llContent.dialog.curData.originalText)})}llContent.dialog.elem.className="lleo_show lleo_collapse";setTimeout(function(){llContent.dialog.remove()},450)},submitCustomTranslation:function(){var a=stringHelper.trimText(document.getElementById("lleo_transField").value);llContent.handlers.saveTranslation(a);return!1},clickTranslationsList:function(a){if("A"===
a.target.tagName||"DIV"===a.target.tagName)a=parseInt(a.target.getAttribute("data-index")),isNaN(a)||llContent.handlers.saveTranslation(llContent.dialog.curData.translations[a].value);return!1},clickTranslateContext:function(){null!=llContent.dialog.curData.context&&"undefined"!==typeof llContent.dialog.curData.context&&(document.getElementById("lleo_translateContextLink").className+="hidden",kango.invokeAsyncCallback("window.lingualeo.translateWithGoogle",llContent.dialog.curData.context,"en",llContent.nativeLang&&
"en"!==llContent.nativeLang?llContent.nativeLang:"ru",function(a){llContent.dialog.setTranslatedContext(a.error_msg?i18n.getLocaleMessage("errorContextTranslation"):a.translation)}));return!1},operaMouseUp:function(a){if(llContent.isMac?a.metaKey:a.ctrlKey){var b=null;"undefined"===typeof a.target.tagName||"input"!==a.target.tagName.toLowerCase()&&"textarea"!==a.target.tagName.toLowerCase()||(b=a.target);llContent.showDialogForCurrentSelection(b,!1)}return!1}}};llContent.init();
