KangoAPI.onReady(function(){function l(b){g.on("click",".control-checkbox",function(a){a=$(this);if(!a.attr("disabled")){var c=a.find("> .custom-checkbox");a.trigger(c.hasClass("checked")?"setUnchecked":"setChecked");if(b.onClick)b.onClick()}}).on("updateState",".control",function(){var a=$(this);a.hasClass("sub-control")||a.parent(".controls-group").find(".sub-control").not(a).trigger(a.attr("checked")?"setEnabled":"setDisabled");a.trigger("sceneChange",{checked:!!a.attr("checked")})}).on("setDisabled",
".control-checkbox",function(){$(this).addClass("disabled").attr("disabled",!0)}).on("setEnabled",".control-checkbox",function(){$(this).removeClass("disabled").removeAttr("disabled")}).on("setChecked",".control-checkbox",function(){var a=$(this);a.find("> .custom-checkbox").addClass("checked");a.addClass("checked").attr("checked",!0);a.trigger("updateState")}).on("setUnchecked",".control-checkbox",function(){var a=$(this);a.find("> .custom-checkbox").removeClass("checked");a.removeClass("checked").removeAttr("checked");
a.trigger("updateState")}).on("sceneChange",".control-checkbox",function(a,c){var d=$(this);if(b.onSceneChange){var e=d.data("sceneChecked"),h=d.data("sceneUnchecked");if(e)b.onSceneChange({enable:c.checked,page:d.data("page"),scene:e});if(h)b.onSceneChange({enable:!c.checked,page:d.data("page"),scene:h})}}).find(".control-checkbox").trigger("updateState")}function m(){browserDetector.isFirefox()&&$("#demoGroupPaper").addClass("group-paper-mozilla");var b=$("#demoContainer");l({onSceneChange:function(a){var c=
b.find('[data-page="'+a.page+'"]');a.enable?c.addClass(a.scene):c.removeClass(a.scene)},onClick:function(){n()}});$("#releaseNotesButton").click(function(){k(!1)});$("#btnOptions").click(p);$("#btnClosePage").click(function(){window.close()});$("#btnCreateAccount").click(function(){kango.invokeAsync("window.lingualeo.openLinguaLeoPage","registerViaExtension",{utm_campaign:"options"})});$("#btnLogin").click(function(){kango.invokeAsync("window.lingualeo.openLinguaLeoPage","login")})}function q(){i18n.localizeDom($("#container").get(0));
var b=stringHelper.formatStrExt(f["options/content"],{"custom-checkbox":f["options/custom-checkbox"]});g.html(b);-1<window.navigator.userAgent.toLowerCase().indexOf("macintosh")?$("#ctrlKeyText").hide():$("#cmdKeyText").hide()}function k(b){$("#releaseNotes").show();for(var a=$("#releaseNotesBlocksContainer"),c=0;5>c;c++)for(var d=0;5>d;d++)if(b)$('<div class="block show"></div>').appendTo(a);else{var e=70*(c+d)+"ms";$('<div class="block"></div>').css({webkitTransitionDelay:e,mozTransitionDelay:e,
msTransitionDelay:e,transitionDelay:e}).appendTo(a)}b||setTimeout(function(){for(var b=a.find(".block"),c=0;c<b.size();c++)b.eq(c).addClass("show")},10);setTimeout(function(){$("#releaseNotes").addClass("show")},300)}function p(){$("#releaseNotes").hide().removeClass("show");$("#releaseNotesBlocksContainer").empty();window.location.hash=""}function r(){function b(a,b){$("#"+a).trigger(b?"setChecked":"setUnchecked")}kango.invokeAsync("window.lingualeo.getExtensionOptions",function(a){b("controlUseDblClick",
a.useDblClick);b("controlUseDblClickWithCtrl",a.dblClickWithCtrl);b("controlUseDblClickWithAlt",a.dblClickWithAlt);b("controlShowPicture",a.showPicture);b("controlShowContext",a.showContext);b("controlAutoTranslateContext",a.autoTranslateContext);b("controlAutoplaySound",a.autoplaySound);b("controlShowUntrainedWordsCount",a.showUntrainedWordsCount);b("controlShowBrowserPopups",a.showBrowserPopups);b("controlShowHints",a.wizardsEnabled)})}function n(){function b(a){return $("#"+a).attr("checked")?
1:0}var a=new LinguaLeoDefaultOptions;a.useDblClick=b("controlUseDblClick");a.dblClickWithCtrl=b("controlUseDblClickWithCtrl");a.dblClickWithAlt=b("controlUseDblClickWithAlt");a.showPicture=b("controlShowPicture");a.showContext=b("controlShowContext");a.autoTranslateContext=b("controlAutoTranslateContext");a.autoplaySound=b("controlAutoplaySound");a.showUntrainedWordsCount=b("controlShowUntrainedWordsCount");a.showBrowserPopups=b("controlShowBrowserPopups");a.wizardsEnabled=b("controlShowHints");
kango.invokeAsync("window.lingualeo.setExtensionOptions",a)}function s(){var b="#changelog"===window.location.hash;q();m();r();$("#extVersion").text("v"+kango.getExtensionInfo().version);b&&k(!0);kango.invokeAsync("window.lingualeo.isAuthorized",function(a){a||(kango.invokeAsync("window.lingualeo.isUserHasAccount",function(a){$(a?"#btnLogin":"#btnCreateAccount").css("display","block")}),$("#registerContainer").show())})}var t=["options/content","options/custom-checkbox"],g=$("#content"),f;i18n.updateLocaleMessages(!0,
function(){kango.invokeAsync("kango.getExtensionInfo",function(b){lingualeoHelper.getTemplates(t,!0,function(a){f=a;s()})})})});
