require.config({baseUrl:"./js",paths:{jquery:"./lib/jquery-3.1.1.min",promise:"./lib/promise.min",EventEmitter:"./lib/EventEmitter.min",baseApi:"./module/baseApi",exKit:"./module/exKit"}});
require("promise EventEmitter ./module/pageController ./module/i18nDom ./module/utils ./module/dom ./module/dialog exKit ./module/counter ../codeMirror/lib/codemirror ../codeMirror/mode/javascript/javascript ../codeMirror/addon/edit/matchbrackets ../codeMirror/addon/edit/closebrackets ../codeMirror/addon/comment/continuecomment ../codeMirror/addon/selection/active-line".split(" "),function(k,r,t,u,l,e,v,w,x,y){(new k(function(e){u();chrome.storage.local.get({trackers:{}},e)})).then(function(k){document.body.classList.remove("loading");
var c=new r,h=null;(function(){document.querySelector(".head__action-close").addEventListener("click",function(a){a.preventDefault();window.close()});var b=document.querySelector(".head__action-save");b.addEventListener("click",function(a){a.preventDefault();var b=this;if("..."!==b.textContent){var f=b.textContent;b.textContent="...";c.trigger("save",[function(){setTimeout(function(){b.textContent=f},750)}])}});document.querySelector(".head__action-add-code").addEventListener("click",function(a){a.preventDefault();
c.trigger("showCodeDialog")});var a=document.querySelector(".editor__textarea");h=y.fromTextArea(a,{mode:"javascript",lineWrapping:!0,lineNumbers:!0,matchBrackets:!0,autoCloseBrackets:!0,continueComments:!0,styleActiveLine:!0,extraKeys:{"Ctrl-S":function(){b.dispatchEvent(new MouseEvent("click",{cancelable:!0}))},"Cmd-S":function(){b.dispatchEvent(new MouseEvent("click",{cancelable:!0}))}}})})();var g=new t;(function(){g.applyUrl=function(){var b=g.get("id");b=document.title=b?"Edit tracker "+b:"New tracker";
var a=g.get("id");a?c.trigger("editTracker",[a]):c.trigger("newTracker");g.get("code")&&c.trigger("showCodeDialog");a=g.getUrl();history.replaceState(null,b,a)}})();(function(){var b=document.querySelector(".option__auto-update");b.addEventListener("change",function(){c.trigger("autoUpdate",[this.checked])});c.on("setAutoUpdate",function(a){var f=a;a.info.disableAutoUpdate&&(f=!1);b.checked=!!f})})();var q=function(b){var a=this,f=b.info,d=function(b){var d=h.getValue(),e={};try{e=l.parseMeta(d)}catch(p){throw alert("Parse meta error!\n"+
p.message),b(),p;}var m={id:a.id,meta:e,info:f,code:d};c.trigger("setAutoUpdate",[m]);chrome.storage.local.get({trackers:{}},function(f){f.trackers[m.id]=m;chrome.storage.local.set(f,function(){g.clear().set("id",a.id).go();b()})})},e=function(a){f.disableAutoUpdate=!a};c.on("save",d);c.on("autoUpdate",e);this.id=b.id||l.getUuid();this.setCode=function(a){h.setValue(a)};this.destroy=function(){c.off("save",d);c.off("autoUpdate",e)};c.trigger("setAutoUpdate",[b]);this.setCode(b.code);h.focus()},d=
null;(function(){var b=null,a=function(){var a=new v;e.el(a.body,{class:["dialog-code"],append:[e.el("span",{class:"dialog__label",text:chrome.i18n.getMessage("enterTrackerCode")}),a.addInput(e.el("textarea",{class:"dialog__textarea",name:"code"})),e.el("div",{class:["dialog__button_box"],append:[e.el("a",{class:["button","button-add"],href:"#add",text:chrome.i18n.getMessage("add"),on:["click",function(b){b.preventDefault();b=a.getValues();var f="";try{var c=JSON.parse(b.code);1===c.version&&(c=w.convertV1ToV2(c));
f=l.trackerObjToUserScript(c)}catch(n){throw alert("Error!\n"+n.message),n;}d.setCode(f);a.destroy()}]}),e.el("a",{class:["button","button-cancel"],href:"#cancel",text:chrome.i18n.getMessage("cancel"),on:["click",function(b){b.preventDefault();a.destroy()}]})]})]});a.show();return a};c.on("showCodeDialog",function(){b&&b.destroy();b=a()})})();(function(){var b=function(){var a=[];a.unshift("==UserScript==");a.push("@name New Tracker");a.push("@version 1.0");a.push("@connect ");a.push("==/UserScript==");
a=a.map(function(a){return["//",a].join(" ")});a.push("");return a.join("\n")};c.on("editTracker",function(a){if(!d||d.id!==a){d&&d.destroy();var c=k.trackers[a];c||(c={meta:{},info:{},code:b()},c.id=a,alert("Tracker id not exists!"));d=new q(c)}});c.on("newTracker",function(){d&&d.destroy();var a={meta:{},info:{},code:b()};d=new q(a)})})();g.applyUrl();x()})});
