require.config({baseUrl:"./js",paths:{jquery:"./lib/jquery-3.1.1.min",jqueryUi:"./lib/jquery-ui.min",moment:"./lib/moment-with-locales.min",promise:"./lib/promise.min",EventEmitter:"./lib/EventEmitter.min"}});
require("promise EventEmitter ./module/i18nDom ./module/utils ./module/dom ./module/selectBox ./module/profileManager ./module/resultFilter ./module/profileController ./module/pageController ./module/explore ./module/counter".split(" "),function(n,z,A,l,t,w,x,B,C,D,E,F){(new n(function(g){A();chrome.storage.local.get({trackerListHeight:200,currentProfileId:null,hidePeerRow:!0,hideSeedRow:!1,categoryWordFilter:!0,profiles:[],trackers:{},history:[],sortCells:[["quality",-1]],checkUpdateTime:0,eSections:[],
quickSearch:[],kpFolderId:"1",favoriteSync:!0,originalPosterName:!1,syncProfiles:!0},function(c){c.syncProfiles?chrome.storage.sync.get("profiles",function(l){l.profiles&&(c.profiles=l.profiles);g(c)}):g(c)})})).then(function(g){var c=[],m=g.trackers;0===Object.keys(m).length&&"bitsnoop booktracker brodim extratorrent filebase freeTorrents hdclub inmac kinozal megashara mininova nnmclub opentorrent piratebit rgfootball rutor rutracker tapochek tfile thepiratebay".split(" ").forEach(function(g){!m[g]&&
c.push(new n(function(c){l.request("./trackers/"+g+".js",function(a,e){try{if(a)throw a;m[g]={id:g,meta:l.parseMeta(e.body),info:{},code:e.body}}catch(b){console.error("Load local tracker error!",b)}c()})}))});return n.all(c).then(function(c){return c.length&&new n(function(c){chrome.storage.local.set({trackers:m},c)})}).then(function(){return g})}).then(function(g){document.body.classList.remove("loading");var c=new z,m=new D({useHash:!0});(function(a){a.applyUrl=function(){var e=a.get("query");
e="string"===typeof e?JSON.stringify(e)+" :: TMS":"Torrents MultiSearch";e=document.title=e;var b=a.get("profileId");c.trigger("selectProfileById",[b]);b=a.get("query");"string"===typeof b?(c.trigger("setSearchQuery",[b]),c.trigger("search",[b])):c.trigger("stateReset");b=a.getUrl();history.replaceState(null,e,b)}})(m);(function(){var a=document.querySelector(".explore"),e=new E(g,a,c);c.on("stateReset",function(){e.show()});c.on("search",function(){e.hide()})})();(function(){var a=document.querySelector(".input__input-search"),
e=document.querySelector(".input__clear-search"),b=document.querySelector(".search__submit");c.on("setSearchQuery",function(c){a.value=c;a.dispatchEvent(new CustomEvent("keyup"))});(function(a,b){var k=function(){a.value="";a.dispatchEvent(new CustomEvent("keyup",{detail:"stateReset"}))};a.addEventListener("keypress",function(a){13===a.keyCode&&b.dispatchEvent(new MouseEvent("click",{cancelable:!0}))});a.addEventListener("keyup",function(a){if("stateReset"!==a.detail)c.once("stateReset",k)})})(a,
b);l.bindClearBtn(e,a);(function(a,c){a.addEventListener("click",function(a){a.preventDefault();a=a.detail&&a.detail.query?a.detail.query:c.value;a=a.trim();m.set("profileId",y.profile.id).set("query",a).go()})})(b,a);var p=function(a,c){var e=null,p=function(){var a=null,c=function(c){setTimeout(function(){c(a=g.history)});return{abort:function(){c=null}}},b=function(c,b){var e=c.length,f=c.toLowerCase();c=a.filter(function(a){a=a.query;return 0===e?!!a:0===a.toLowerCase().indexOf(f)}).sort(function(a,
d){a=a.count;d=d.count;return a===d?0:a<d?1:-1}).map(function(a){return a.query});b(c)};return function(f,u){a?b(f,u):e=c(function(){b(f,u)})}}(),q=function(){var a={},c=function(c,b,e){a[c]=b;e(b)};return function(b,f){var u=a[b];u?c(b,u,f):e=l.request({url:"http://suggestqueries.google.com/complete/search",data:{client:"firefox",q:b},json:!0},function(a,e){a||c(b,e.body[1],f)})}}(),v=$(a);b.addEventListener("click",function(){v.autocomplete("close");v.autocomplete("disable");setTimeout(function(){v.autocomplete("enable")},
1E3)});var f=null;v.autocomplete({minLength:0,delay:100,position:{collision:"bottom"},source:function(a,c){e&&(e.abort(),e=null);a=a.term;a.length?q(a,c):p(a,c);f&&f.querySelector(".ui-state-active")&&c()},select:function(a,b){a.preventDefault();c.dispatchEvent(new CustomEvent("click",{cancelable:!0,detail:{query:b.item.value}}))},create:function(){var a=!1;f=document.querySelector("ul.ui-autocomplete");f.addEventListener("scroll",function(){0!==this.scrollTop?!0!==a&&(a=!0,this.style.boxShadow="rgba(0, 0, 0, 0.40) -2px 1px 2px 0px inset"):
!1!==a&&(a=!1,this.style.boxShadow=null)})}})};setTimeout(function(){require(["jquery"],function(){require(["jqueryUi"],function(){p(a,b)})})},50)})();(function(){document.querySelector(".menu__btn-main").addEventListener("click",function(a){a.preventDefault();m.clear().go()})})();(function(){var a=!1,c=document.querySelector(".scroll_top");c.addEventListener("click",function(a){a.preventDefault();window.scrollTo(0,0)});window.addEventListener("scroll",function(b){100<window.scrollY?a||(a=!0,c.classList.add("scroll_top-show")):
a&&(a=!1,c.classList.remove("scroll_top-show"))})})();var n=new B(c);(function(a){var e=!1,b=document.querySelector(".input_box-time-filter"),p=document.querySelector(".input__input-word-filter"),G=document.querySelector(".input__clear-word-filter"),m=document.querySelector(".input__input-size-filter.input__input-range-from"),k=document.querySelector(".input__input-size-filter.input__input-range-to"),H=document.querySelector(".select__select-time-filter"),q=document.querySelector(".input__input-time-filter.input__input-range-from"),
v=document.querySelector(".input__input-time-filter.input__input-range-to"),f=document.querySelector(".input__input-seed-filter.input__input-range-from"),u=document.querySelector(".input__input-seed-filter.input__input-range-to"),I=document.querySelector(".input__input-peer-filter.input__input-range-from"),J=document.querySelector(".input__input-peer-filter.input__input-range-to"),n=null,r=function(){clearTimeout(n);n=setTimeout(function(){a.update()},150)};(function(b,f){var e=function(a){var d=
a.toLowerCase(),c,b="",f=[],e=/\s/;for(a=0;c=d[a];a++)e.test(c)?"\\"!==d[a-1]?(b&&f.push(b),b=""):b=b.substr(0,b.length-1)+c:b+=c;b&&f.push(b);e=null;d=[];c=[];var k=/^[!-].+/;for(a=0;b=f[a];a++)k.test(b)?(e=c,b=b.substr(1)):e=d,b=l.sanitizeTextRe(b),-1===e.indexOf(b)&&e.push(b);a=function(a,d){return a.length>d.length?-1:1};c.sort(a);d.sort(a);a=Array(3);c.length&&(a[0]=new RegExp(c.join("|")));d.length&&(a[1]=new RegExp(d.join("|"),"g"),a[2]=d.length);return(a[0]||a[1])&&a},d=function(){b.value=
"";b.dispatchEvent(new CustomEvent("keyup",{detail:"stateReset"}))},k={type:"word",re:null};l.bindClearBtn(f,b);b.addEventListener("keyup",function(b){k.re=e(this.value);k.re?a.add(k):a.remove(k);r();if("stateReset"!==b.detail)c.once("stateReset",d)})})(p,G);(function(b,e){var f=function(){b.value="";e.value="";b.dispatchEvent(new CustomEvent("keyup",{detail:"stateReset"}));e.dispatchEvent(new CustomEvent("keyup",{detail:"stateReset"}))},d={type:"size",min:0,max:0};b.addEventListener("keyup",function(b){d.min=
1073741824*parseFloat(this.value);if(isNaN(d.min)||d.max&&d.min>d.max)this.value="",d.min=0;0<d.min||0<d.max?a.add(d):a.remove(d);r();if("stateReset"!==b.detail)c.once("stateReset",f)});e.addEventListener("keyup",function(b){d.max=1073741824*parseFloat(this.value);if(isNaN(d.max)||d.min&&d.max<d.min)this.value="",d.max=0;0<d.min||0<d.max?a.add(d):a.remove(d);r();if("stateReset"!==b.detail)c.once("stateReset",f)});l.bindDblClickClear([b,e])})(m,k);(function(b,f,k,d){var g=function(){b.selectedIndex=
0;b.dispatchEvent(new CustomEvent("change",{detail:"stateReset"}))},h={type:"date",min:0,max:0};new w(b);b.addEventListener("change",function(b){0>this.value?e||(e=!0,f.classList.add("input_box-time-filter-visible")):e&&(e=!1,k.value="",d.value="",f.classList.remove("input_box-time-filter-visible"));e?a.remove(h):(h.max=0,h.min=parseInt(this.value)||0,h.min&&(h.min=parseInt(Date.now()/1E3)-h.min),0<h.min?a.add(h):a.remove(h));r();if("stateReset"!==b.detail)c.once("stateReset",g)});k.addEventListener("keyup",
function(b){h.min=parseInt(this.value&&this.dataset.time)||0;h.max&&h.min>h.max&&(this.value="",h.min=0);0<h.min||0<h.max?a.add(h):a.remove(h);r()});d.addEventListener("keyup",function(b){h.max=parseInt(this.value&&this.dataset.time)||0;h.min&&h.max<h.min&&(this.value="",h.max=0);0<h.min||0<h.max?a.add(h):a.remove(h);r()});l.bindDblClickClear([k,d]);var u=function(a,b){$([a,b]).datepicker({defaultDate:"0",changeMonth:!0,numberOfMonths:1,prevText:"",nextText:"",firstDay:1,maxDate:"+1d",hideIfNoPrevNext:!0,
dateFormat:"yy-mm-dd",onClose:function(a,b){b=b.input[0];b.dataset.time=Math.round((new Date(a)).getTime()/1E3);b.dispatchEvent(new CustomEvent("keyup"))}})};setTimeout(function(){require(["jquery"],function(){require(["jqueryUi"],function(){u(k,d)})})},50)})(H,b,q,v);(function(b,e){var f=function(){b.value="";e.value="";b.dispatchEvent(new CustomEvent("keyup",{detail:"stateReset"}));e.dispatchEvent(new CustomEvent("keyup",{detail:"stateReset"}))};g.hideSeedRow&&(t.closest(".parameter-filter",b).style.display=
"none");var d={type:"seed",min:0,max:0};b.addEventListener("keyup",function(b){d.min=parseInt(this.value);if(isNaN(d.min)||d.max&&d.min>d.max)this.value="",d.min=0;0<d.min||0<d.max?a.add(d):a.remove(d);r();if("stateReset"!==b.detail)c.once("stateReset",f)});e.addEventListener("keyup",function(b){d.max=parseInt(this.value);if(isNaN(d.max)||d.min&&d.max<d.min)this.value="",d.max=0;0<d.min||0<d.max?a.add(d):a.remove(d);r();if("stateReset"!==b.detail)c.once("stateReset",f)});l.bindDblClickClear([b,e])})(f,
u);(function(b,e){var f=function(){b.value="";e.value="";b.dispatchEvent(new CustomEvent("keyup",{detail:"stateReset"}));e.dispatchEvent(new CustomEvent("keyup",{detail:"stateReset"}))};g.hidePeerRow&&(t.closest(".parameter-filter",b).style.display="none");var d={type:"peer",min:0,max:0};b.addEventListener("keyup",function(b){d.min=parseInt(this.value);if(isNaN(d.min)||d.max&&d.min>d.max)this.value="",d.min=0;0<d.min||0<d.max?a.add(d):a.remove(d);r();if("stateReset"!==b.detail)c.once("stateReset",
f)});e.addEventListener("keyup",function(b){d.max=parseInt(this.value);if(isNaN(d.max)||d.min&&d.max<d.min)this.value="",d.max=0;0<d.min||0<d.max?a.add(d):a.remove(d);r();if("stateReset"!==b.detail)c.once("stateReset",f)});l.bindDblClickClear([b,e])})(I,J)})(n);var y=new C(g,c,x,n);(function(a){var e=document.querySelector(".button-manage-profile"),b=document.querySelector(".profile__select"),p=document.querySelector(".tracker__list"),l=null;p.parentNode.style.height=g.trackerListHeight+"px";p.style.height=
g.trackerListHeight+"px";e.addEventListener("click",function(b){b.stopPropagation();b.preventDefault();(new x(g.profiles,a,g.trackers,c,g.syncProfiles)).show()});l=new w(b,{editBtn:e});p.addEventListener("click",function(a){a.preventDefault();(a=t.closest("a",a.target))&&a.dataset.id&&c.trigger("selectTracker",[a.dataset.id])});b.addEventListener("change",function(){var b=a.getProfileById(this.value).id;chrome.storage.local.set({currentProfileId:g.currentProfileId=b},function(){c.trigger("selectProfileById",
[b])})});a.setSelectOptions=function(a){var c=b.value,e=0;b.textContent="";t.el(b,{append:a.map(function(a,b){c==a.id&&(e=b);return t.el("option",{text:a.name,value:a.id})})});b.selectedIndex=e;l.update();l.syncSelectedIndex()};a.setSelectValue=function(a,c){var e=0;a.some(function(a,b){if(a.id===c)return e=b,!0});b.selectedIndex!=e&&(b.selectedIndex=e);l.syncSelectedIndex()};a.setTrackerList=function(a){p.textContent="";p.appendChild(a)};a.load();var m=function(){$(p.parentNode).resizable({minHeight:56,
handles:"s",alsoResize:p,stop:function(a,b){chrome.storage.local.set({trackerListHeight:b.size.height})}})};setTimeout(function(){require(["jquery"],function(){require(["jqueryUi"],function(){m()})})},50)})(y);(function(){var a=parseInt(Date.now()/1E3);86400<a-g.checkUpdateTime&&chrome.runtime.sendMessage({action:"update"},function(c){c&&c.success&&chrome.storage.local.set({checkUpdateTime:g.checkUpdateTime=a})});chrome.storage.onChanged.addListener(function(a,b){b=g.history;var e=a.history;e&&(e=
e.newValue||[],b.splice(0),b.push.apply(b,e));var m=g.trackers;if(b=a.trackers){var n=b.newValue||{};b=l.getDiffObj(m,n);b.removed.forEach(function(a){delete m[a];c.trigger("trackerRemoved",[a])});b.modified.forEach(function(a){var b=m[a],e=n[a],f=l.getDiffObj(b,e);f.modified.forEach(function(a){b[a]=e[a]});f.modified.length&&c.trigger("trackerChange",[a,f.modified])});b.new.forEach(function(a){m[a]=n[a];c.trigger("trackerInsert",[a])})}var k=g.profiles;if(a=a.profiles){var t=a.newValue||[],q=k.map(function(a){return a.id}),
v=t.map(function(a){return a.id});q.slice(0).forEach(function(a){var b=q.indexOf(a);-1===v.indexOf(a)&&(q.splice(b,1),a=k.splice(b,1)[0],c.trigger("profileRemoved",[a.id]))});v.forEach(function(a,b){var e=t[b],f=q.indexOf(a);-1===f?(q.splice(b,1,a),k.splice(b,1,e),c.trigger("profileInsert",[e.id])):f!==b&&(q.splice(f,1),q.splice(b,0,a),k.splice(f,1),k.splice(b,0,e),c.trigger("profilesSortChange"))});k.forEach(function(a,b){var e=t[b]||{};b=l.getDiffObj(a,e);b.modified.forEach(function(b){a[b]=e[b]});
b.modified.length&&c.trigger("profileFieldChange",[a.id,b.modified])})}})})();m.applyUrl();F()})});
