require.config({baseUrl:"./js",paths:{jquery:"./lib/jquery-3.1.1.min",baseApi:"./module/baseApi",exKit:"./module/exKit"}});
require("./module/i18nDom ./module/utils ./module/dom ./lib/filesize.min exKit ./module/counter".split(" "),function(y,z,u,A,m,B){y();({domCache:{menu:document.getElementById("menu"),frame:document.querySelector("iframe"),statusBar:document.getElementById("status_bar")},varCache:{lastXhr:null,rootUrl:/([^:]+:\/\/[^\/]+)/,$frameDom:null,frameDoc:null,$frameDoc:null,frameSelect:null,uid:null},nodeList:{},contentFilter:function(a){return a},domFilter:function(a){[].slice.call(a.querySelectorAll(["script",
"link","style","iframe"])).forEach(function(a){var b=u.el(a.tagName,{data:{blockNode:1}});a.parentNode.replaceChild(b,a)});[].slice.call(a.querySelectorAll("*[style]")).forEach(function(a){a.removeAttribute("style")})},openPage:function(a,b,c){var d=this;b=b||"";if(a){var e=this.nodeList.search.request.value,f=this.nodeList.search.query_encoding.value;"utf-8"!==f&&"cp1251"===f&&(e=m.funcList.encodeCp1251(e));a=a.replace("%search%",e);b=b.replace("%search%",e);d.varCache.frameDoc&&(d.varCache.frameDoc.textContent=
"");a={type:"GET",url:a};this.nodeList.search.charset.value&&(a.mimeType="text/plain; charset="+this.nodeList.search.charset.value);b&&(a.type="POST",a.data=b);this.varCache.lastXhr&&(this.varCache.lastXhr.abort(),this.varCache.lastXhr=null);this.varCache.lastXhr=z.request(a,function(a,b){a?c&&c(!1):(a=m.contentFilter(b.body),b=m.parseHtml(a),d.varCache.$frameDom=$(b),a=m.parseHtml(d.contentFilter(a)),d.domFilter(a),b=d.domCache.frame.contentDocument.documentElement,d.varCache.frameDoc=b,d.varCache.$frameDoc=
$(b),b.textContent="",b.appendChild(a),b.appendChild(u.el("style",{text:".kit_select{color:#000 !important;background-color:#FFCC33 !important;cursor:pointer;box-shadow: 0 0 3px red, inset 0 0 3px red !important;}"})),c&&c(!0))})}},getHash:function(a){var b=0;if(0===a.length)return b;for(var c=0,d=a.length;c<d;c++){var e=a.charCodeAt(c);b=(b<<5)-b+e;b&=b}return 0>b?-1*b:b},getRandomColor:function(){return"#"+(16777216+16777215*Math.random()).toString(16).substr(1,6)},getCode:function(){var a=this,
b=this.nodeList,c=b.selectors,d=b.convert,e=function(a){var b=c[a];if(b.enable&&!b.enable.checked)return null;var f={selector:b.input.value};b.attr&&b.attr.value?f.attr=b.attr.value:-1!==["category_link","torrent_link","torrent_dl","next_page_link"].indexOf(a)&&(f.attr="href");1===Object.keys(f).length&&(f=f.selector);return f},f=function(a){a=d[a];var b=[];a&&(a.regexp&&a.regexp.value&&b.push({name:"replaceRe",re:a.regexp.value,text:a.regexp_text.value}),a.today&&a.today.checked&&b.push("replaceToday"),
a.month&&a.month.checked&&b.push("replaceMonth"),a.format&&"-1"!==a.format.value&&b.push({name:"timeFormat",format:a.format.value}),a.convert&&a.convert.checked&&b.push("convertSize"));return 0===b.length?null:b};e={version:2,type:"kit",title:b.desk.tracker.title.value,icon:function(){var c=b.desk.tracker.icon.value;c||(c=a.getRandomColor());return c}(),desc:b.desk.tracker.desk.value,downloadUrl:b.desk.tracker.download_url.value,tVersion:b.desk.tracker.t_version.value,search:{loginUrl:b.auth.url.value,
loginFormSelector:b.auth.input.value,searchUrl:b.search.url.value,nextPageSelector:e("next_page_link"),baseUrl:b.search.root.value,requestType:b.search.post.value?"POST":"GET",requestData:b.search.post.value||null,requestMimeType:function(){var a=null;b.search.charset.value&&(a="text/html; charset="+b.search.charset.value);return a}(),onBeforeRequest:function(){var a=[],c=b.search.query_encoding.value;"utf-8"!==c&&a.push({name:"encode",type:c});return 0===a.length?null:a}(),listItemSelector:b.selectors.list.input.value,
listItemSplice:function(){var a=parseInt(b.selectors.skip.first.value),c=parseInt(b.selectors.skip.last.value);if(!a&&!c)return null;0!==c&&(c*=-1);return[a,c]}(),torrentSelector:{categoryTitle:e("category_name"),categoryUrl:e("category_link"),title:e("torrent_name"),url:e("torrent_link"),size:e("size"),downloadUrl:e("torrent_dl"),seed:e("seed"),peer:e("peer"),date:e("time")},onGetValue:{categoryTitle:f("category_name"),categoryUrl:f("category_link"),title:f("torrent_name"),url:f("torrent_link"),
size:f("size"),downloadUrl:f("torrent_dl"),seed:f("seed"),peer:f("peer"),date:f("time")}}};(function g(a){for(var b in a){var c=a[b];null===c?delete a[b]:"object"!==typeof c||Array.isArray(c)||(g(c),Object.keys(c).length||delete a[b])}})(e);e.uid=this.varCache.uid||this.getHash(JSON.stringify(e));return JSON.stringify(e)},clearForm:function(){var a=this.nodeList;this.varCache.frameDoc&&(this.varCache.frameDoc.textContent="");this.varCache.$frameDom=null;this.varCache.$frameDoc=null;this.varCache.frameDoc=
null;this.varCache.frameSelect=null;this.varCache.uid=null;a.search.url.value="";a.search.query_encoding.selectedIndex=0;a.search.charset.value="";a.search.post.value="";a.search.root.value="";a.auth.url.value="";a.auth.input.value="";a.desk.tracker.icon.value="";a.desk.tracker.icon_file.value="";a.desk.tracker.icon_pic.dispatchEvent(new CustomEvent("updatePic"));a.desk.tracker.title.value="";a.desk.tracker.desk.value="";[].slice.call(document.querySelectorAll(".error")).forEach(function(a){a.classList.remove("error")});
var b=function(a){a.table_mode&&(a.table_mode.checked=!0);a.input&&(a.input.value="");a.output&&(a.output.value="");a.attr&&(a.attr.value="");a.first&&(a.first.value=0);a.last&&(a.last.value=0);a.enable&&(a.enable.checked=!1,a.enable.dispatchEvent(new CustomEvent("change")))},c=function(a){a.regexp&&(a.regexp.value="",a.regexp_text.value="");a.today&&(a.today.checked=!1);a.month&&(a.month.checked=!1);a.format&&(a.format.selectedIndex=0);a.convert&&(a.convert.checked=!1);a.original&&(a.original.value=
"");a.converted&&(a.converted.value="");a.result&&(a.result.value="")},d;for(d in a.selectors){var e=a.selectors[d];b(e)}for(d in a.convert)e=a.convert[d],c(e)},readCode:function(a){var b=this.nodeList,c=b.selectors,d=b.convert;1===a.version&&(a=m.convertV1ToV2(a));if(2===a.version){a.search||(a.search={});var e={categoryTitle:"category_name",categoryUrl:"category_link",title:"torrent_name",url:"torrent_link",size:"size",downloadUrl:"torrent_dl",seed:"seed",peer:"peer",date:"time",nextPageSelector:"next_page_link"},
f=function(a,b){a=c[e[a]];"object"!==typeof b&&(b={selector:b});b.selector&&(a.input.value=b.selector,a.attr&&(a.attr.value=b.attr||""),a.enable&&(a.enable.checked=!0,a.enable.dispatchEvent(new CustomEvent("change"))))},h=function(a,b){var c=d[e[a]];Array.isArray(b)&&b.forEach(function(a){"replaceRe"===a.name?(c.regexp.value=a.re,c.regexp_text.value=a.text):"replaceToday"===a?c.today&&(c.today.checked=!0):"replaceMonth"===a?c.month&&(c.month.checked=!0):"timeFormat"===a.name?c.format&&(a=c.format.querySelector('[value="'+
a.format+'"]'))&&(c.format.selectedIndex=a.index):"convertSize"===a&&c.convert&&(c.convert.checked=!0)})};this.varCache.uid=a.uid;b.desk.tracker.title.value=a.title||"";b.desk.tracker.icon.value=a.icon||"";b.desk.tracker.icon_pic.dispatchEvent(new CustomEvent("updatePic"));b.desk.tracker.desk.value=a.desc;b.desk.tracker.download_url.value=a.downloadUrl||"";b.desk.tracker.t_version.value=a.tVersion||"";b.auth.url.value=a.search.loginUrl||"";b.auth.input.value=a.search.loginFormSelector||"";b.search.url.value=
a.search.searchUrl||"";b.search.root.value=a.search.baseUrl||"";b.search.post.value=a.search.requestData||"";b.search.charset.value=function(){var b=a.search.requestMimeType&&a.search.requestMimeType.match(/charset=(.+)/);return(b=b&&b[1])||""}();(function(){var c=a.search.onBeforeRequest;Array.isArray(c)&&c.some(function(a){if("encode"===a.name&&(a=b.search.query_encoding.querySelector('[value="'+a.type+'"]')))return b.search.query_encoding.selectedIndex=a.index,!0})})();c.list.input.value=a.search.listItemSelector;
(function(){var c=a.search.listItemSplice;Array.isArray(c)&&(b.selectors.skip.first.value=c[0],0!==c[1]&&(c[1]*=-1),b.selectors.skip.last.value=c[1])})();f("nextPageSelector",a.search.nextPageSelector);for(var g in a.search.torrentSelector)f(g,a.search.torrentSelector[g]);for(g in a.search.onGetValue)h(g,a.search.onGetValue[g])}},bindSavePage:function(){var a=this,b=this.nodeList.save.code;b.write.addEventListener("click",function(c){c.preventDefault();b.textarea.value=a.getCode()});b.read.addEventListener("click",
function(c){c.preventDefault();try{var d=JSON.parse(b.textarea.value)}catch(e){alert(chrome.i18m.getMessage("kitTrackerCodeReadError")+"\n"+e);return}a.clearForm();a.readCode(d)})},bindDescPage:function(){var a=this,b=this.nodeList.desk.tracker;b.icon_file.addEventListener("change",function(){var a=this.files[0];if(a)if(-1===["image/x-icon","image/jpeg","image/png","image/svg"].indexOf(a.type)||1048576<a.size)b.icon.value="",b.icon_pic.dispatchEvent(new CustomEvent("updatePic")),b.icon_file.value=
"";else{var d=new FileReader;d.onloadend=function(){b.icon.value=d.result;b.icon_pic.dispatchEvent(new CustomEvent("updatePic"))};d.readAsDataURL(a)}});b.icon_pic.addEventListener("updatePic",function(){var c=b.icon.value;c||(c=a.getRandomColor());this.style.backgroundImage="url("+m.getTrackerIconUrl(c)+")"});b.icon_pic.addEventListener("click",function(a){a.preventDefault();b.icon.value="";b.icon_file.value="";this.dispatchEvent(new CustomEvent("updatePic"))});b.icon_pic.dispatchEvent(new CustomEvent("updatePic"))},
getNodePath:function(a,b){for(var c,d=this.varCache.frameDoc,e=this.varCache.$frameDoc,f=[],h=a;a;){c=a.parentNode;if(!c||1!==c.nodeType)break;if(a===b.node){f.unshift(b.path);break}if(a.id&&1===d.querySelectorAll("#"+a.id).length){f.unshift("#"+a.id);break}var g=a.tagName,l=[].slice.call(a.parentNode.childNodes),n=[].slice.call(a.classList).filter(function(a){return"kit_select"!==a});l=l.filter(function(a){return a.tagName===g});if(1===l.length&&l[0]===a)f.unshift(g.toLowerCase());else{var m=l.filter(function(a){return n.every(function(b){return a.classList.contains(b)})});
if(1===m.length&&m[0]===a)if(a=g.toLowerCase()+"."+n.join("."),f.unshift(a),1===d.querySelectorAll(a).length)break;else{a=c;continue}a=l.indexOf(a);f.unshift(g.toLowerCase()+":eq("+a+")")}a=c}b=f.join(">");try{if(e.find(b).get(0)!==h)throw console.error("Doc is not found! ",b),"Node is not found!";}catch(p){b=""}return b},rmDocKitSelect:function(){var a=this.varCache.frameDoc;a&&[].slice.call(a.querySelectorAll(".kit_select")).forEach(function(a){a.classList.remove("kit_select")})},getSelectMode:function(a){var b=
this,c=this.varCache.frameDoc,d=function(c){c=c.target;if(1===c.nodeType){h&&h.classList.remove("kit_select");h=c;c.classList.add("kit_select");var d=b.getNodePath(c,a.container);g=d;b.domCache.statusBar.textContent=d;a.onOver&&a.onOver(c,d)}},e=function(){c.removeEventListener("mouseover",d);c.removeEventListener("click",f)},f=function(b){b.preventDefault();e();a.onClick&&a.onClick(h,g)},h=null,g=null;this.rmDocKitSelect();c.addEventListener("mouseover",d);c.addEventListener("click",f);this.varCache.frameSelect&&
(this.varCache.frameSelect.abort(),this.varCache.frameSelect=null);this.varCache.frameSelect={abort:function(){e();a.onAbort&&a.onAbort()}}},bindSelector:function(a,b){var c=this,d=a.input,e=a.btn,f=a.enable,h=a.output,g=a.attr,l=a.table_mode,n=this.nodeList.selectors.skip.first,r=this.nodeList.selectors.skip.last,p=c.nodeList.selectors.list.input,k=h&&"next_page_link"!==b,q=function(){var a=n.value;a=parseInt(a);0===a||a?n.classList.remove("error"):(n.classList.add("error"),a=0);return a},t=function(a,
b){b=b||0;var d=null,e=c.varCache.$frameDoc;try{d=k?e.find(p.value).eq(q()).find(a):e.find(a)}catch(D){}(a=d&&d.eq(b).get(0))&&a.classList.contains("kit_select")||c.rmDocKitSelect();a&&a.classList.add("kit_select")},v=function(a){var e=null,f=c.varCache.$frameDom;try{e=k?f.find(p.value).eq(q()).find(a):f.find(a)}catch(C){}e&&e.length?(d.classList.remove("error"),h&&(a=e[0],g&&g.classList.remove("error"),(e=g&&g.value)||-1===["category_link","torrent_link","torrent_dl","next_page_link"].indexOf(b)||
(e="href"),e?(a=a.getAttribute(e),null===a&&g&&g.classList.add("error"),a=a||""):a=a.textContent,a=m.contentUnFilter(a),e=["seed","peer","size","time"],-1!==e.indexOf(b)&&(isNaN(parseInt(a))?h.classList.add("error"):h.classList.remove("error")),h.value=a,-1!==e.indexOf(b)&&c.nodeList.convert[b].regexp.dispatchEvent(new CustomEvent("keyup")))):(d.classList.add("error"),h&&(h.value=""))},w=function(a){if(l&&l.checked){var b=a.match(/(.+>\s*tr)/);(b=b&&b[1])&&(a=b)}k&&0===a.indexOf(p.value)&&(a=a.substr(p.value.length).replace(/^:eq\(\d+\)\s*>\s*/,
""));d.value=a;v(a)};e.addEventListener("click",function(){var a={};if(k){var b=c.varCache.$frameDoc;a.path=p.value+":eq("+q()+")";a.parent=b.find(a.path).get(0)}c.getSelectMode({container:a,onOver:function(a,b){w(b)},onClick:function(a,b){w(b)}})});d.addEventListener("test",function(){v(d.value)});d.addEventListener("keyup",function(){v(d.value);t(d.value)});g&&g.addEventListener("keyup",function(){v(d.value);t(d.value)});l&&l.addEventListener("change",function(){w(d.value)});f&&f.addEventListener("change",
function(){var a=this.checked;e.disabled=!a;d.disabled=!a;g&&(g.disabled=!a)});f&&f.dispatchEvent(new CustomEvent("change"));"list"===b&&(d.addEventListener("selectFirstNode",function(){t(d.value,q())}),d.addEventListener("selectLastNode",function(){var a=d.value,b=r.value;b=parseInt(b);0===b||b?r.classList.remove("error"):(r.classList.add("error"),b=0);t(a,-1*b)}));h&&(h.disabled=!0,h.classList.add("output"));d&&d.classList.add("input");g&&g.classList.add("attr");l&&(l.checked=!0)},bindSelectorPage:function(){var a=
this.nodeList.selectors,b;for(b in a){var c=a[b];c.btn&&c.input&&this.bindSelector(c,b)}a.skip.first.addEventListener("change",function(){for(var b in a){var c=a[b];c.input&&(!c.enable||c.enable&&c.enable.checked)&&(c.input.dispatchEvent(new CustomEvent("test")),"list"===b&&c.input.dispatchEvent(new CustomEvent("selectFirstNode")))}});a.skip.first.addEventListener("keyup",function(){a.list.input.dispatchEvent(new CustomEvent("selectFirstNode"))});a.skip.last.addEventListener("change",function(){a.list.input.dispatchEvent(new CustomEvent("selectLastNode"))});
a.skip.last.addEventListener("keyup",function(){a.list.input.dispatchEvent(new CustomEvent("selectLastNode"))})},bindConvertItem:function(a,b){var c=this,d=a.regexp,e=a.regexp_text,f=a.today,h=a.month,g=a.format,l=a.original,n=a.converted,r=a.convert,p=a.result,k=function(){var a=c.nodeList.selectors.time.output.value,b=e.value,x=g.value,k=a;d.value&&(k=k.replace(new RegExp(d.value,"ig"),b));f.checked&&(k=m.funcList.todayReplace(k));h.checked&&(k=m.funcList.monthReplace(k));"-1"!==x&&(k=m.funcList.dateFormat(x,
k));l.value=a;n.value=k;p.value=new Date(1E3*k)},q=function(){var a=c.nodeList.selectors.size.output.value,b=e.value,f=a;d.value&&(f=f.replace(new RegExp(d.value,"ig"),b));r.checked&&(f=m.funcList.sizeFormat(f));l.value=a;n.value=f;p.value=A(f)},t=function(a){a=c.nodeList.selectors[a].output.value;var b=e.value,f=a;d.value&&(f=f.replace(new RegExp(d.value,"ig"),b));l.value=a;n.value=f;p.value=f};d.addEventListener("keyup",function(){this.classList.remove("error");try{new RegExp(this.value,"ig")}catch(v){this.classList.add("error");
return}"time"===b?k():"size"===b?q():-1!==["seed","peer"].indexOf(b)&&t(b)});e.addEventListener("keyup",function(){"time"===b?k():"size"===b?q():-1!==["seed","peer"].indexOf(b)&&t(b)});f&&f.addEventListener("change",function(){k()});h&&h.addEventListener("change",function(){k()});g&&g.addEventListener("change",function(){k()});r&&r.addEventListener("change",function(){q()});p&&(p.disabled=!0);l&&(l.disabled=!0);n&&(n.disabled=!0)},bindConvertPage:function(){var a=this.nodeList.convert,b;for(b in a)this.bindConvertItem(a[b],
b);u.el(this.nodeList.convert.time.format,{append:function(){var a=[];a.push(u.el("option",{text:"-",value:-1}));for(var b=m.funcList.dateFormat(),e=0,f;f=b[e];e++)a.push(u.el("option",{text:f,value:e}));return a}()})},bindAuthPage:function(){var a=this,b=this.nodeList.auth;b.open.addEventListener("click",function(c){c.preventDefault();a.openPage(b.url.value,null,function(a){a?b.url.classList.remove("error"):b.url.classList.add("error")})});b.url.addEventListener("keyup",function(a){13===a.keyCode&&
b.open.dispatchEvent(new CustomEvent("click"))});this.bindSelector(b)},bindSearchPage:function(){var a=this,b=this.nodeList.search;b.open.addEventListener("click",function(c){c.preventDefault();a.openPage(b.url.value,b.post.value,function(a){a?b.url.classList.remove("error"):b.url.classList.add("error")})});b.request.addEventListener("keyup",function(a){13===a.keyCode&&b.open.dispatchEvent(new CustomEvent("click"))});b.url.addEventListener("keyup",function(c){var d=b.url.value.match(a.varCache.rootUrl);
(d=d&&d[1]||"")&&(d+="/");b.root.value=d;13===c.keyCode&&b.open.dispatchEvent(new CustomEvent("click"))});b.post.addEventListener("keyup",function(a){13===a.keyCode&&b.open.dispatchEvent(new CustomEvent("click"))});[].slice.call(b.query_encoding.childNodes).forEach(function(a){1!==a.nodeType&&a.parentNode.removeChild(a)})},bindMenu:function(){this.domCache.menu.addEventListener("click",function(a){var b=a.target;if("A"===b.tagName){a.preventDefault();a=this.querySelector(".active");var c=document.querySelector(".page.active");
a&&c&&(a.classList.remove("active"),c.classList.remove("active"));a=b.dataset.page;b.classList.add("active");c=document.querySelector(".page."+a);c.classList.add("active")}})},one:function(){var a=this;this.bindMenu();[].slice.call(document.querySelectorAll("[data-id]")).forEach(function(b){var c=b.dataset.id;c=c.split("_").map(function(a){return a.replace(/([A-Z])/g,"_$1").toLowerCase()});var d=c.pop(),e=a.nodeList;c.forEach(function(a,b){e[a]||(e[a]={});e=e[a]});e[d]=b});this.bindSearchPage();this.bindSelectorPage();
this.bindConvertPage();this.bindAuthPage();this.bindDescPage();this.bindSavePage();document.body.classList.remove("loading")}}).one();B()});
