/*

// ==UserScript==
// @name LinguaLeoReadability
// @all-frames true
// @include http://*
// @include https://*
// @include file://*
// @include file:///*
// @exclude http*://lingualeo.com/*
// @exclude http*://lingualeo.ru/*
// @exclude http*://*facebook.com/plugins/*
// @exclude http*://*twitter.com/widgets/*
// @exclude http*://plusone.google.com/*
// ==/UserScript==

 Readability. An Arc90 Lab Experiment.
 Website: http://lab.arc90.com/experiments/readability
 Source:  http://code.google.com/p/arc90labs-readability

 "Readability" is a trademark of Arc90 Inc and may not be used without explicit permission.

 Copyright (c) 2010 Arc90 Inc
 Readability is licensed under the Apache License, Version 2.0.
*/
var Readability=function(s){var n=null,r="undefined"!==typeof console?function(a){}:function(){},c={biggestFrame:!1,flags:7,FLAG_STRIP_UNLIKELYS:1,FLAG_WEIGHT_CLASSES:2,FLAG_CLEAN_CONDITIONALLY:4,regexps:{unlikelyCandidates:/combx|comment|community|disqus|extra|foot|header|menu|remark|rss|shoutbox|sidebar|sponsor|ad-break|agegate|pagination|pager|popup|tweet|twitter/i,okMaybeItsACandidate:/and|article|body|column|main|shadow/i,positive:/article|body|content|entry|hentry|main|page|pagination|post|text|blog|story/i,
negative:/combx|comment|com-|contact|foot|footer|footnote|masthead|media|meta|outbrain|promo|related|scroll|shoutbox|sidebar|sponsor|shopping|tags|tool|widget/i,extraneous:/print|archive|comment|discuss|e[\-]?mail|share|reply|all|login|sign|single/i,divToPElements:/<(a|blockquote|dl|div|img|ol|p|pre|table|ul)/i,replaceIds:/(<.*?)(id=".*?")/gi,replaceClasses:/(<.*?)(class=".*?")/gi,trim:/^\s+|\s+$/g,normalize:/\s{2,}/g,killBreaks:/(<br\s*\/?>(\s|&nbsp;?)*){1,}/g,videos:/http:\/\/(www\.)?(youtube|vimeo)\.com/i,
skipFootnoteLink:/^\s*(\[?[a-z0-9]{1,2}\]?|^|edit|citation needed)\s*$/i,nextLink:/(next|weiter|continue|>([^\|]|$)|\u00bb([^\|]|$))/i,prevLink:/(prev|earl|old|new|<|\u00ab)/i},init:function(){var a=c.createIFrame(s.document.documentElement.innerHTML);n=a.contentDocument;c.prepDocument();var b=n.createElement("div");b.appendChild(c.getArticleTitle());var d="",f=c.grabArticle();f&&(b.appendChild(f),d=c.prepareContentForOutput(b.innerHTML));n=null;domHelper.removeChild(a);return d},createIFrame:function(a){var b=
s.document.createElement("iframe");b.src="javascript:void 0";b.id="lleo_enjoyContentFrame";domHelper.getBody().appendChild(b);b.contentDocument.documentElement.innerHTML=this.cleanHTML(a).replace(c.regexps.replaceTrans,"$1");c.removeHiddenElements(b.contentDocument.documentElement);return b},cleanHTML:function(a){a=$((new DOMParser).parseFromString("<div data-ll-html>"+a+"</div>","text/html"));a.find("footer,style,script,noscript,rel,audio,embed,object,input,select,textarea,br,font").remove();return a.find("[data-ll-html]").html()},
removeHiddenElements:function(a){a=a.getElementsByTagName("*");for(var b=a.length;b--;)"IFRAME"!==a[b].tagName&&domHelper.isElementVisible(a[b])||domHelper.removeChild(a[b])},prepareContentForOutput:function(a){return a.replace(c.regexps.replaceLinks,"").replace(c.regexps.replaceIds,"$1").replace(c.regexps.replaceClasses,"$1")},getArticleTitle:function(){var a="",b="";try{a=b=n.title,"string"!==typeof a&&(a=b=c.getInnerText(n.getElementsByTagName("title")[0]))}catch(d){}if(a.match(/ [\|\-] /))a=b.replace(/(.*)[\|\-] .*/gi,
"$1"),3>a.split(" ").length&&(a=b.replace(/[^\|\-]*[\|\-](.*)/gi,"$1"));else if(-1!==a.indexOf(": "))a=b.replace(/.*:(.*)/gi,"$1"),3>a.split(" ").length&&(a=b.replace(/[^:]*[:](.*)/gi,"$1"));else if(150<a.length||15>a.length){var f=n.getElementsByTagName("h1");1===f.length&&(a=c.getInnerText(f[0]))}a=a.replace(c.regexps.trim,"");4>=a.split(" ").length&&(a=b);b=n.createElement("H1");b.innerHTML=a;return b},prepDocument:function(){if(null===n.body){var a=n.createElement("body");try{n.body=a}catch(b){n.documentElement.appendChild(a),
r(b)}}var d=n.getElementsByTagName("frame");if(0<d.length){for(var a=null,f=0,g=0,e=0;e<d.length;e+=1){var k=d[e].offsetWidth+d[e].offsetHeight,m=!1;try{m=!0}catch(h){r(h)}k>g&&(g=k,c.biggestFrame=d[e]);m&&k>f&&(a=d[e],f=k)}a&&(d=n.createElement("body"),d.innerHTML=a.contentWindow.document.body.innerHTML,d.style.overflow="scroll",n.body=d,(a=n.getElementsByTagName("frameset")[0])&&a.parentNode.removeChild(a))}},prepArticle:function(a){c.cleanStyles(a);c.killBreaks(a);c.cleanConditionally(a,"form");
c.clean(a,"object");c.clean(a,"h1");1===a.getElementsByTagName("h2").length&&c.clean(a,"h2");c.clean(a,"iframe");c.cleanHeaders(a);c.cleanConditionally(a,"table");c.cleanConditionally(a,"ul");c.cleanConditionally(a,"div");for(var b=a.getElementsByTagName("p"),d=b.length-1;0<=d;d-=1){var f=b[d].getElementsByTagName("img").length,g=b[d].getElementsByTagName("embed").length,e=b[d].getElementsByTagName("object").length;0===f&&0===g&&0===e&&""===c.getInnerText(b[d],!1)&&b[d].parentNode.removeChild(b[d])}try{a.innerHTML=
a.innerHTML.replace(/<br[^>]*>\s*<p/gi,"<p")}catch(k){r("Cleaning innerHTML of breaks failed. This is an IE strict-block-elements bug. Ignoring.: "+k)}},initializeNode:function(a){a.readability={contentScore:0};switch(a.tagName){case "DIV":a.readability.contentScore+=5;break;case "PRE":case "TD":case "BLOCKQUOTE":a.readability.contentScore+=3;break;case "ADDRESS":case "OL":case "UL":case "DL":case "DD":case "DT":case "LI":case "FORM":a.readability.contentScore-=3;break;case "H1":case "H2":case "H3":case "H4":case "H5":case "H6":case "TH":a.readability.contentScore-=
5}a.readability.contentScore+=c.getClassWeight(a)},grabArticle:function(a){var b=c.flagIsActive(c.FLAG_STRIP_UNLIKELYS),d=null!==a?!0:!1;a=a?a:n.body;for(var f=a.innerHTML,g=a.getElementsByTagName("*"),e=null,k=[],m=0;e=g[m];m+=1){if(b){var h=e.className+e.id;if(-1!==h.search(c.regexps.unlikelyCandidates)&&-1===h.search(c.regexps.okMaybeItsACandidate)&&"BODY"!==e.tagName){r("Removing unlikely candidate - "+h);e.parentNode.removeChild(e);m-=1;continue}}if("P"===e.tagName||"TD"===e.tagName||"PRE"===
e.tagName)k[k.length]=e;if("DIV"===e.tagName)if(-1===e.innerHTML.search(c.regexps.divToPElements)){h=n.createElement("p");try{h.innerHTML=e.innerHTML,e.parentNode.replaceChild(h,e),m-=1,k[k.length]=e}catch(t){r("Could not alter div to p, probably an IE restriction, reverting back to div.: "+t)}}else for(var h=0,l=e.childNodes.length;h<l;h+=1){var p=e.childNodes[h];if(3===p.nodeType){var q=n.createElement("p");q.innerHTML=p.nodeValue;q.style.display="inline";p.parentNode.replaceChild(q,p)}}}b=[];for(g=
0;g<k.length;g+=1)m=(e=k[g].parentNode)?e.parentNode:null,h=c.getInnerText(k[g]),!e||"undefined"===typeof e.tagName||25>h.length||("undefined"===typeof e.readability&&(c.initializeNode(e),b.push(e)),m&&"undefined"===typeof m.readability&&"undefined"!==typeof m.tagName&&(c.initializeNode(m),b.push(m)),l=0,l+=1,l+=h.split(",").length,l+=Math.min(Math.floor(h.length/100),3),e.readability.contentScore+=l,m&&(m.readability.contentScore+=l/2));k=null;g=0;for(e=b.length;g<e;g+=1)if(b[g].readability.contentScore*=
1-c.getLinkDensity(b[g]),r("Candidate: "+b[g]+" ("+b[g].className+":"+b[g].id+") with score "+b[g].readability.contentScore),!k||b[g].readability.contentScore>k.readability.contentScore)k=b[g];if(null===k||"BODY"===k.tagName)k=n.createElement("DIV"),k.innerHTML=a.innerHTML,a.innerHTML="",a.appendChild(k),c.initializeNode(k);b=n.createElement("DIV");d&&(b.id="readability-content");d=Math.max(10,.2*k.readability.contentScore);g=k.parentNode.childNodes;e=0;for(m=g.length;e<m;e+=1)if(h=g[e],l=!1,h){r("Looking at sibling node: "+
h+" ("+h.className+":"+h.id+")"+("undefined"!==typeof h.readability?" with score "+h.readability.contentScore:""));r("Sibling has score "+(h.readability?h.readability.contentScore:"Unknown"));h===k&&(l=!0);p=0;h.className===k.className&&""!==k.className&&(p+=.2*k.readability.contentScore);"undefined"!==typeof h.readability&&h.readability.contentScore+p>=d&&(l=!0);if("P"===h.nodeName){var p=c.getLinkDensity(h),q=c.getInnerText(h),s=q.length;80<s&&.25>p?l=!0:80>s&&0===p&&-1!==q.search(/\.( |$)/)&&(l=
!0)}if(l){r("Appending node: "+h);l=null;if("DIV"!==h.nodeName&&"P"!==h.nodeName){r("Altering siblingNode of "+h.nodeName+" to div.");l=n.createElement("DIV");try{l.id=h.id,l.innerHTML=h.innerHTML}catch(u){r("Could not alter siblingNode to div, probably an IE restriction, reverting back to original."),l=h,e-=1,m-=1}}else l=h,e-=1,m-=1;l.className="";b.appendChild(l)}}c.prepArticle(b);1===c.curPageNum&&(b.innerHTML='<div id="readability-page-1" class="page">'+b.innerHTML+"</div>");return 250>c.getInnerText(b,
!1).length?(a.innerHTML=f,c.flagIsActive(c.FLAG_STRIP_UNLIKELYS)?(c.removeFlag(c.FLAG_STRIP_UNLIKELYS),c.grabArticle(a)):c.flagIsActive(c.FLAG_WEIGHT_CLASSES)?(c.removeFlag(c.FLAG_WEIGHT_CLASSES),c.grabArticle(a)):c.flagIsActive(c.FLAG_CLEAN_CONDITIONALLY)?(c.removeFlag(c.FLAG_CLEAN_CONDITIONALLY),c.grabArticle(a)):null):b},getInnerText:function(a,b){var d="";if("undefined"===typeof a.textContent&&"undefined"===typeof a.innerText)return"";b="undefined"===typeof b?!0:b;d="Microsoft Internet Explorer"===
navigator.appName?a.innerText.replace(c.regexps.trim,""):a.textContent.replace(c.regexps.trim,"");return b?d.replace(c.regexps.normalize," "):d},getCharCount:function(a,b){b=b||",";return c.getInnerText(a).split(b).length-1},cleanStyles:function(a){a=a||n;var b=a.firstChild;if(a)for("function"===typeof a.removeAttribute&&"readability-styled"!==a.className&&a.removeAttribute("style");null!==b;)1===b.nodeType&&("readability-styled"!==b.className&&b.removeAttribute("style"),c.cleanStyles(b)),b=b.nextSibling},
getLinkDensity:function(a){var b=a.getElementsByTagName("a");a=c.getInnerText(a).length;for(var d=0,f=0,g=b.length;f<g;f+=1)d+=c.getInnerText(b[f]).length;return d/a},getClassWeight:function(a){if(!c.flagIsActive(c.FLAG_WEIGHT_CLASSES))return 0;var b=0;"string"===typeof a.className&&""!==a.className&&(-1!==a.className.search(c.regexps.negative)&&(b-=25),-1!==a.className.search(c.regexps.positive)&&(b+=25));"string"===typeof a.id&&""!==a.id&&(-1!==a.id.search(c.regexps.negative)&&(b-=25),-1!==a.id.search(c.regexps.positive)&&
(b+=25));return b},nodeIsVisible:function(a){return(0!==a.offsetWidth||0!==a.offsetHeight)&&"none"!==a.style.display.toLowerCase()},killBreaks:function(a){try{a.innerHTML=a.innerHTML.replace(c.regexps.killBreaks,"<br />")}catch(b){}},clean:function(a,b){for(var d=a.getElementsByTagName(b),f="object"===b||"embed"===b,g=d.length-1;0<=g;g-=1){if(f){for(var e="",k=0,m=d[g].attributes.length;k<m;k+=1)e+=d[g].attributes[k].value+"|";if(-1!==e.search(c.regexps.videos))continue;if(-1!==d[g].innerHTML.search(c.regexps.videos))continue}d[g].parentNode.removeChild(d[g])}},
cleanConditionally:function(a,b){if(c.flagIsActive(c.FLAG_CLEAN_CONDITIONALLY))for(var d=a.getElementsByTagName(b),f=d.length-1;0<=f;f-=1){var g=c.getClassWeight(d[f]),e="undefined"!==typeof d[f].readability?d[f].readability.contentScore:0;r("Cleaning Conditionally "+d[f]+" ("+d[f].className+":"+d[f].id+")"+("undefined"!==typeof d[f].readability?" with score "+d[f].readability.contentScore:""));if(0>g+e)d[f].parentNode.removeChild(d[f]);else if(10>c.getCharCount(d[f],",")){for(var e=d[f].getElementsByTagName("p").length,
k=d[f].getElementsByTagName("img").length,m=d[f].getElementsByTagName("li").length-100,h=d[f].getElementsByTagName("input").length,n=0,l=d[f].getElementsByTagName("embed"),p=0,q=l.length;p<q;p+=1)-1===l[p].src.search(c.regexps.videos)&&(n+=1);l=c.getLinkDensity(d[f]);p=c.getInnerText(d[f]).length;q=!1;if(k>e)q=!0;else if(m>e&&"ul"!==b&&"ol"!==b)q=!0;else if(h>Math.floor(e/3))q=!0;else if(25>p&&(0===k||2<k))q=!0;else if(25>g&&.2<l)q=!0;else if(25<=g&&.5<l)q=!0;else if(1===n&&75>p||1<n)q=!0;q&&d[f].parentNode.removeChild(d[f])}}},
cleanHeaders:function(a){for(var b=1;3>b;b+=1)for(var d=a.getElementsByTagName("h"+b),f=d.length-1;0<=f;f-=1)(0>c.getClassWeight(d[f])||.33<c.getLinkDensity(d[f]))&&d[f].parentNode.removeChild(d[f])},flagIsActive:function(a){return 0<(c.flags&a)},removeFlag:function(a){c.flags&=~a}};return{parse:c.init}}(window);
