var data = {
    categories: [ {
        id: 1,
        subcategories: [ {
            id: 100
        }, {
            id: 101
        }, {
            id: 102
        } ]
    }, {
        id: 2,
        subcategories: [ {
            id: 200
        }, {
            id: 201
        }, {
            id: 202
        }, {
            id: 203
        }, {
            id: 204
        }, {
            id: 205
        }, {
            id: 206
        }, {
            id: 207
        }, {
            id: 208
        } ]
    }, {
        id: 3,
        subcategories: [ {
            id: 300
        }, {
            id: 301
        }, {
            id: 302
        }, {
            id: 303
        }, {
            id: 304
        }, {
            id: 305
        }, {
            id: 306
        }, {
            id: 307
        }, {
            id: 308
        }, {
            id: 309
        }, {
            id: 310
        }, {
            id: 311
        }, {
            id: 312
        }, {
            id: 313
        }, {
            id: 314
        } ]
    }, {
        id: 4,
        subcategories: [ {
            id: 400
        }, {
            id: 401
        }, {
            id: 402
        }, {
            id: 403
        }, {
            id: 404
        }, {
            id: 405
        } ]
    }, {
        id: 5,
        subcategories: [ {
            id: 500
        }, {
            id: 501
        }, {
            id: 502
        }, {
            id: 503
        }, {
            id: 504
        }, {
            id: 505
        }, {
            id: 506
        }, {
            id: 507
        }, {
            id: 508
        }, {
            id: 509
        }, {
            id: 510
        } ]
    }, {
        id: 6,
        subcategories: [ {
            id: 600
        }, {
            id: 601
        }, {
            id: 602
        }, {
            id: 603
        }, {
            id: 604
        }, {
            id: 605
        }, {
            id: 606
        }, {
            id: 607
        }, {
            id: 608
        }, {
            id: 609
        }, {
            id: 610
        }, {
            id: 611
        }, {
            id: 612
        }, {
            id: 613
        }, {
            id: 614
        }, {
            id: 615
        }, {
            id: 616
        }, {
            id: 617
        }, {
            id: 618
        }, {
            id: 619
        }, {
            id: 620
        }, {
            id: 621
        }, {
            id: 622
        }, {
            id: 623
        }, {
            id: 624
        }, {
            id: 625
        }, {
            id: 626
        }, {
            id: 627
        }, {
            id: 628
        }, {
            id: 629
        }, {
            id: 630
        }, {
            id: 631
        }, {
            id: 632
        }, {
            id: 633
        } ]
    }, {
        id: 700,
        subcategories: []
    } ],
    youtube: [ {
        id: "yt_1"
    }, {
        id: "yt_2"
    }, {
        id: "yt_10"
    }, {
        id: "yt_15"
    }, {
        id: "yt_17"
    }, {
        id: "yt_18"
    }, {
        id: "yt_19"
    }, {
        id: "yt_20"
    }, {
        id: "yt_21"
    }, {
        id: "yt_22"
    }, {
        id: "yt_23"
    }, {
        id: "yt_24"
    }, {
        id: "yt_25"
    }, {
        id: "yt_26"
    }, {
        id: "yt_27"
    }, {
        id: "yt_28"
    }, {
        id: "yt_29"
    }, {
        id: "yt_30"
    }, {
        id: "yt_31"
    }, {
        id: "yt_32"
    }, {
        id: "yt_33"
    }, {
        id: "yt_34"
    }, {
        id: "yt_35"
    }, {
        id: "yt_36"
    }, {
        id: "yt_37"
    }, {
        id: "yt_38"
    }, {
        id: "yt_39"
    }, {
        id: "yt_40"
    }, {
        id: "yt_41"
    }, {
        id: "yt_42"
    }, {
        id: "yt_43"
    }, {
        id: "yt_44"
    }, {
        id: "yt_45"
    } ],
    options: [ {
        name: "Allow"
    }, {
        name: "Block"
    }, {
        name: "Warning"
    } ],
    ytoptions: [ {
        name: "Allow"
    }, {
        name: "Block"
    } ]
};